### PR TITLE
fix TimeDimExtractionFn.apply() under concurrency

### LINKED ISSUE #3983: a bug in groupBy v2?
One of my users (using version 0.9.2) is using time extraction function in a groupBy query.

results are always correct with groupBy-v1 while with groupBy-v2 they are sometimes correct and sometimes not 
however, without the extractionFn in the query groupBy-v2 seems to always produce correct result.

here is what the query looks like...

```
{
  "queryType": "groupBy",
  "dataSource": {
    "type": "table",
    "name": "xxx"
  },
  "intervals": {
    "type": "intervals",
    "intervals": ["2016-03-01T00:00:00.000Z/2016-03-02T00:00:00.000Z", "2016-04-01T00:00:00.000Z/2016-04-02T00:00:00.000Z", "2016-05-01T00:00:00.000Z/2016-05-02T00:00:00.000Z"]
  },
  "filter": {
    "type": "and",
    "fields": [{
      "type": "or",
      "fields": [{
        "type": "selector",
        "dimension": "myDate",
        "value": "20160301"
      }, {
        "type": "selector",
        "dimension": "myDate",
        "value": "20160401"
      }, {
        "type": "selector",
        "dimension": "myDate",
        "value": "20160501"
      }]
    }, {
      "type": "selector",
      "dimension": "xx",
      "value": "xx"
    }, {
      "type": "or",
      "fields": [{
        "type": "selector",
        "dimension": "xx",
        "value": "yy"
      }, {
        "type": "selector",
        "dimension": "xx",
        "value": "yy"
      }, {
        "type": "selector",
        "dimension": "xx",
        "value": "yy"
      }]
    }]
  },
  "granularity": {
    "type": "all"
  },
  "dimensions": [{
    "type": "extraction",
    "dimension": "myDate",
    "outputName": "Month",
    "extractionFn": {
      "type": "time",
      "timeFormat": "yyyyMMdd",
      "resultFormat": "yyyyMM"
    }
  }, {
    "type": "default",
    "dimension": "xx",
    "outputName": "xx"
  }],
  "aggregations": [{
    "type": "longSum",
    "name": "xx",
    "fieldName": "xx"
  }],
  "postAggregations": [],
  "limitSpec": {
    "type": "default",
    "columns": [{
      "dimension": "Month",
      "direction": "ascending",
      "dimensionOrder": {
        "type": "lexicographic"
      }
    }],
    "limit": 1000
  },
  "context": {
    "groupByStrategy": "v2",
    "groupByIsSingleThreaded": true
  },
  "descending": false
}
```

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #3983

### CODE REVIEW

**Comment by patelh** [comment]
Why not migrate to joda time?  Deprecate and add new one using joda time formatter which is thread safe.

**Comment by himanshug** [comment]
@patelh this is only a test patch for verification, not mergeable in druid just yet.

**Comment by gianm** [comment]
@patelh a new one using Joda would be nice, but this one should still be fixed.

@himanshug I added this to 0.10.0 since it's a bug that seems straightforward and nice to fix.

**Comment by gianm** [comment]
@himanshug is this ready for merging or do you need to do more testing?

**Comment by himanshug** [comment]
@gian i'm working to get this deployed on the user cluster and confirm that it fixes the issue. it most likely does from the local analysis so far.

**Comment by himanshug** [comment]
@gianm ok, this fixes the problem on real usage.

I updated ExtractionFn doc also to mention Thread safety expectation.

I also tried to write an UT for concurrency, but it never failed even without this fix .. so the UT is unreliable and hence not added in this PR.

**Comment by gianm** [comment]
thanks @himanshug, this looks good to me 👍

**Pull request merged**
