### PR TITLE
Change default for pendingTasksRunnerNumThreads to 1

### PR DESCRIPTION
**Pull request by drcrallen**
Related to https://github.com/druid-io/druid/issues/3174
Makes default config not encounter the suspected cause

### CODE REVIEW

**Comment by gianm** [comment]
Config was introduced in #2521 (0.9.1)

**Comment by gianm** [comment]
👍

**Comment by fjy** [comment]
@drcrallen can you backport?

**Comment by drcrallen** [comment]
@fjy this already is to 0.9.1  That leaves master with a default of 3.

As per https://groups.google.com/d/msg/druid-development/McGZdcnO0Ws/9gz8UxQDDAAJ we can either leave master as is and put a fix in before 0.9.2, or push this upstream and get to it at some other point.

**Pull request merged**
