### PR TITLE
support PostgreSQL >= 9.5 upsert capability

### PR DESCRIPTION
**Pull request by xvrl**

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by fjy** [comment]
@xvrl what is the advantage of using upsert?

**Comment by xvrl** [comment]
@fjy you could still run into deadlock issues if you're not careful about ordering.

**Comment by fjy** [comment]
👍

**Comment by fjy** [comment]
@xvrl did you test this with local postgres?

**Comment by xvrl** [comment]
@fjy yep, tested it

**Pull request merged**
