### PR TITLE
Update druid-api to 0.3.16

### PR DESCRIPTION
**Pull request by drcrallen**
Fixes https://github.com/druid-io/druid/issues/2316

### CODE REVIEW

**Comment by drcrallen** [comment]
Actual failure... investigating.

**Comment by drcrallen** [comment]
@jon-wei FYI

**Comment by jon-wei** [comment]
@drcrallen cool, thanks for the notice

**Comment by drcrallen** [comment]
```AnnouncerTest.testSessionKilled:176 »  test timed out after 60000 milliseconds```

**Comment by nishantmonu51** [comment]
:+1:

**Pull request merged**
