### PR TITLE
Add ExtractionFn to LookupExtractor bridge

### PR DESCRIPTION
**Pull request by drcrallen**
Makes a bridge between extraction function and lookup extractor.

If it is generally agreed that this is a reasonable thing to do I'll add some docs for it.

### CODE REVIEW

**Comment by navis** [comment]
:+1:

**Comment by b-slim** [comment]
@drcrallen i thought the way to go is to use dimensionSpec lookup implementation instead of having nested lookup with extraction function with dimension. But if you feel we need to support both i am fine with that as well. I will leave it to you. In case you want to support both ways i am ok please add docs.

**Comment by drcrallen** [comment]
@b-slim yes, that is the recommended way, and I will mention that in the docs. Sometimes you just need to do some testing though, or there could be things extraction functions can do that lookups cannot yet (since they are slightly different code paths).

For example, we have UI tooling to handle dimension extraction but not lookup dimension spec yet. I'll be using this to make sure transitions and upgrades go smoothly.

**Comment by b-slim** [comment]
@drcrallen no problem, :+1: after docs.

**Comment by drcrallen** [comment]
@b-slim / @navis added docs.

**Pull request merged**
