### PR TITLE
checking potential fix for build failures on AsyncQueryForwardingServletTest

### PR DESCRIPTION
**Pull request by himanshug**
in test explicitly setting maxThreads=256 for ProxyServlet to work around https://tickets.puppetlabs.com/browse/TK-152

if this gets fixed, then we might want to do this in RouterJettyServerInitializer.java also

### CODE REVIEW

**Comment by himanshug** [comment]
ok, this fixes the build. I don't know whether to wait for original bug to get fixed or put this in the RouterJettyServerInitializer.java also. (this might cause router to just block if jetty server is not initialized with enough threads)

what do you think?

**Comment by drcrallen** [comment]
Adding a thread limit without a way to record the usage seems risky. Is it possible to add the number of used threads as a metric or something?

**Comment by drcrallen** [comment]
Also, can you add a unit test so behavior can be defined for what happens if the thread count limit is met? This might require making the limit configurable.

**Comment by drcrallen** [comment]
In the short term, if there's a way to make this as big or larger than the servlet executor pool would at least provide some limit compared to prior behavior.

**Comment by xvrl** [comment]
@himanshug thanks for tracking this down! I wonder if this affects the router as well or not. I'm a bit puzzled as to why this test started failing, since we didn't change any of that code or updated jetty. Something on the Travis end must have changed that triggers this bug, maybe the default number of threads is tied to the number of cores, and that may have changed.

**Comment by xvrl** [comment]
@himanshug do you mind adding a comment above the line you added to refer to the bug? I'll merge after that.

**Comment by drcrallen** [comment]
As a general FYI, it looks like this behavior is still present in [9.3.0](https://github.com/eclipse/jetty.project/blob/jetty-9.3.0.M2/jetty-proxy/src/main/java/org/eclipse/jetty/proxy/AbstractProxyServlet.java#L244-L259) but in a different place than referenced in the original ticket.

**Comment by himanshug** [comment]
@xvrl added the comment

@drcrallen I believe your comments are towards the conclusion that we should update RouterJettyServerInitializer.java with configurable number of threads and not necessarity wait from jetty to fix the issue?

**Comment by drcrallen** [comment]
@himanshug : yes, especially since the workaround is pretty straight forward.

**Pull request merged**
