### PR TITLE
move table of contents to Markdown and fix broken link

### LINKED ISSUE #2397: Druid TOC (toc.textile) needs to be ported to markdown
Github will stop supporting textile soon

### PR DESCRIPTION
**Pull request by xvrl**
fixes #2397

### CODE REVIEW

**Comment by fjy** [comment]
@xvrl wait for https://github.com/druid-io/druid/pull/2398/files, I made even more changes to the TOC

**Comment by xvrl** [comment]
@fjy I don't see any toc changes in #2398

**Comment by fjy** [comment]
@xvrl Oh I thought I made them, nevermind then

**Comment by xvrl** [comment]
@fjy I think they got merged already, our PRs crossed, need to fix my PR, so don't merge yet

**Comment by xvrl** [comment]
@fjy fixed, should be good to merge

**Comment by fjy** [comment]
:+1:

**Pull request merged**
