### PR TITLE
Don't union with empty bitmap in the end in Filters.matchPredicate()

### PR DESCRIPTION
**Pull request by leventov**
**Problem**
I've inspected the graph of bitmap manipulations which are done before processing the query on Druid historical nodes and seen something like this:
```
union {
  intersection {
    union {dimValue=14, empty=1}=1,
    union {dimValue=3, empty=1}=1
  }=1,
  union {dimValue=7, empty=1}=1
}
```
(BTW if you want such intronspection capabilities to be commited to Druid sooner please review this: #3693)

It means that we often make unions of something + empty bitmap.

**How it is fixed**
Optimized `Iterator<ImmutableBitmap>` implementation inside `Filters.matchPredicate()` so that it doesn't emit empty bitmap in the end of the iteration, and make it to follow `Iterator` contract, that is throw `NoSuchElementException` from `next()` if there are no more bitmaps.

BTW disadvantage of Druid's "anonymous class style" is that it's impossible to add tests to such anonymous interface implementations.

### CODE REVIEW

**Comment by gianm** [comment]
@leventov have you measured the improvement here?

**Comment by leventov** [comment]
@gianm no, I didn't. I don't think improvement is significant, because empty bitmaps in compressed representations (concise and roaring) doesn't take much space and cheap to union with. However for roaring it saves one allocation/merge cycle because roaring doesn't support union (and intersection) of more than 2 bitmaps, for making union of many bitmaps it merges them one-by-one.

**Comment by leventov** [comment]
@gianm thank you very much for quick reviews!

**Comment by jon-wei** [comment]
:+1:

**Pull request merged**
