### PR TITLE
Fix index exceeded msg to give maxRowCount as well

### PR DESCRIPTION
**Pull request by himanshug**

### CODE REVIEW

**Comment by xvrl** [comment]
:+1:

**Comment by drcrallen** [comment]
`DruidCoordinatorTest.testCoordinatorRun:349 expected:<1> but was:<0>`

**Comment by drcrallen** [comment]
:+1: 

Very minor risk if someone is using this exception in an extension and uses `%s` or `%d` or similar in the message. Prior version would not have an issue but this version would fail due to now-missing arguments.

**Comment by drcrallen** [comment]
`io.druid.segment.incremental.OffheapIncrementalIndex#outOfRowsReason` is the most notable risk area. Would it be possible to change `io/druid/segment/incremental/OffheapIncrementalIndex.java:190` to `new IndexSizeExceededException("%s", getOutOfRowsReason());` ? (non-blocking)

**Comment by himanshug** [comment]
@drcrallen I don't see why OffheapIncrementalIndex.java:190 needs to change.
new IndexSizeExceededException("blah") is totally valid.

**Comment by gianm** [comment]
I suppose in the unlikely event that the out of rows reason is "oh no 100%disk full"

**Comment by gianm** [comment]
:+1: tho

**Comment by himanshug** [comment]
@gianm @drcrallen oh, got it... will change that just to be safe then.

**Pull request merged**
