### PR TITLE
Update toc.md

### PR DESCRIPTION
**Pull request by anshbansal**

### CODE REVIEW

**Comment by anshbansal** [comment]
I made these changes based on what is present in the operations folder. But seems that not all are present. http://druid.io/docs/latest/operations/dump-segment.html is not present

**Comment by gianm** [comment]
👍  on change, pending CLA from @anshbansal.

**Comment by anshbansal** [comment]
@gianm  Signed the CLA.

**Comment by gianm** [comment]
@anshbansal thanks, and thank you for the contribution!

**Pull request merged**
