### PR TITLE
Removing the md files created for redirection

### PR DESCRIPTION
**Pull request by himanshug**
they were created so that search engines would be able to update their caches according to new names, it should be safe to delete those now.

### CODE REVIEW

**Comment by xvrl** [comment]
@himanshug maybe let's wait for 0.9.0? It will still break any links in the forums.

**Comment by himanshug** [comment]
@xvrl ok, changed milestone to 0.9.0 .
I would like to get this done because there are many windows users who just want to checkout the code and browse.

**Comment by drcrallen** [comment]
:+1:

**Comment by fjy** [comment]
:+1:

**Pull request merged**
