### PR TITLE
Separate overwrite of Guice modules into 2 steps and minor style fix

### PR DESCRIPTION
**Pull request by guobingkun**
Currently during initialization, cliModules and extension modules are loaded at the same level, which makes extension modules not able to overwrite cliModules(For example, the JettyHttpClientModule installed in CliRouter can't be overwritten by our extension module). This PR separates the overwrite step in Initialization.java into two steps so that extension module can overwrite bindings in cliModule.

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by himanshug** [comment]
+1

**Comment by drcrallen** [comment]
Hmm, I wonder if this affects https://github.com/druid-io/druid/issues/1016 in a good way

@guobingkun would you be able to try https://github.com/druid-io/druid/issues/1016#issuecomment-69077199 on this patch?

**Comment by guobingkun** [comment]
@drcrallen Sure, let me take a look

**Comment by guobingkun** [comment]
@drcrallen  This won't affect #1016 since local module and extension module are loaded at the same level. I replicated the issue on this patch too.

**Comment by drcrallen** [comment]
Doh thanks

**Comment by himanshug** [comment]
@drcrallen I dont think #1016 is solved by current state of PR. That is because extension jars on classpath and extension jars from extension config are added to same ModuleList.

However, it is possible to do something like below to fix #1016 

```
....
    );

    ModuleList actualModules = new ModuleList(baseInjector);
    actualModules.addModule(DruidSecondaryModule.class);
    for (Object module : modules) {
      actualModules.addModule(module);
    }

    Module intermediateModules = Modules.override(defaultModules.getModules()).with(actualModules.getModules());

    ModuleList extensionModules = new ModuleList(baseInjector);
    final ExtensionsConfig config = baseInjector.getInstance(ExtensionsConfig.class);
    for (DruidModule module : Initialization.getFromLocalExtensions(config, DruidModule.class)) {
      extensionModules.addModule(module);
    }

 intermediateModules = Modules.override(intermediateModules .getModules()).with(extensionModules.getModules());
extensionModules = new ModuleList(baseInjector);
    for (DruidModule module : Initialization.getFromRemoteExtensions(config, DruidModule.class)) {
      extensionModules.addModule(module);
    }
    return Guice.createInjector(Modules.override(intermediateModules).with(extensionModules.getModules()));
  }
...

//create getFromRemoteExtensions(..) and getFromLocalExtensions(..) and remove getFromExtensions(..)
```

**Comment by himanshug** [comment]
Anyways, @guobingkun , if possible,  can you please test proposed change and send another PR to fix #1016 . but that doesn't necessarily hold this PR, so I'm merging this.

**Pull request merged**
