### PR TITLE
Math expressions support for missing columns.

### LINKED ISSUE #3627: Math expression should gracefully handle missing columns
Most aggregators are coded to ignore missing columns (sum treats them as zeroes, min treats them as positive infinity, etc). Math expressions, however, fail with a "no binding found" message. A quick fix would be to have them return `0L` for missing columns, but IMO it'd be better to allow expressions to be "nullable" and have the aggregators deal with that as appropriate. The goes is to make `min(MISSING, 1, 2) = 1` instead of an exception or zero.

### PR DESCRIPTION
**Pull request by gianm**
Also add SchemaEvolutionTest to help test this kind of thing.

Fixes #3627.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by fjy** [comment]
@navis can you take a look?

**Comment by gianm** [comment]
@nishantmonu51 I don't think this should block on docs. The original expressions PRs and a few follow ups have gone in without docs already, and behavior has been evolving. I prefer adding docs in a separate PR when we like the behavior.

**Comment by gianm** [comment]
Filed #3634 for that.

**Pull request merged**
