### PR TITLE
Make the Announcer closing and unannouncing atomic.

### PR DESCRIPTION
**Pull request by drcrallen**
This was causing errors on unit tests. There may be other items assumed transactional that are not.

### CODE REVIEW

**Comment by drcrallen** [comment]
Actually, on second look, there's a better way to do the transaction, putting in a quick patch.

**Comment by xvrl** [comment]
Is there a better way to test this than having spurious failures?

**Comment by drcrallen** [comment]
@xvrl : We'd need a "slow zookeeper" implementation

**Comment by drcrallen** [comment]
lol, that's rich.

**Comment by drcrallen** [comment]
@xvrl : I looked into it a bit, and there's not an obvious way to slow down zookeeper in a reliable fashion that I could think of quickly.

**Comment by cheddar** [comment]
Unit test?

**Comment by drcrallen** [comment]
@cheddar : This is in response to randomly failing unit tests.

**Comment by drcrallen** [comment]
@cheddar : I asked the curator folks and they don't have a great way to fake a slow ZK. I was considering tapping into some deep mocking of curator, but haven't really had a burning desire to do so.

**Comment by cheddar** [comment]
Ah, ok, sorry I didn't read the comment string.  I just looked at the title and the code change.  Should've read the conversation too.

Nothing jumps out at me from the code.  If it's fixing a spurious test failure, then I'm +1

**Pull request merged**
