### PR TITLE
Reduce excessive logging

### PR DESCRIPTION
**Pull request by niketh**
@jon-wei This should help with https://github.com/druid-io/druid/issues/4609

### CODE REVIEW

**Comment by drcrallen** [comment]
That if statement is huge, can you flip it to be `currentlyProcessing != null` with this message and return immediately? it should be easier to follow what is going on then.

**Comment by drcrallen** [comment]
since this floods logs for some folks, does this need to go into 0.10.1?

**Comment by niketh** [comment]
@drcrallen There is already a message for when it starts to process. So I think having this is the debug logs should be ok. I think it can go into 0.11.0, more here https://github.com/druid-io/druid/issues/4609

**Comment by gianm** [comment]
@drcrallen 

> since this floods logs for some folks, does this need to go into 0.10.1?

I think no, since the extraneous logging was introduced in 0.10.0 so it's not a fresh bug for 0.10.1.

**Comment by drcrallen** [comment]
I'm not debating debug, I mean can you switch the logic from

```java
if (currentlyProcessing == null) {
// LOTS OF STUFF
} else {
      log.info(
              "Server[%s] skipping doNext() because something is currently loading[%s].",
              basePath,
              currentlyProcessing.getSegmentIdentifier()
      );
    }
```

to 

```java
if (currentlyProcessing != null) {
      log.debug(
              "Server[%s] skipping doNext() because something is currently loading[%s].",
              basePath,
              currentlyProcessing.getSegmentIdentifier()
      );
  return;
}
// LOTS OF STUFF
```

**Pull request merged**
