### PR TITLE
update vs spark doc

### PR DESCRIPTION
**Pull request by fjy**

### CODE REVIEW

**Comment by drcrallen** [comment]
should probably mention `DataFrame`s as well, since that seems to be where people want to go instead of RDDs

**Comment by gianm** [comment]
surely you mean [Datasets](https://databricks.com/blog/2016/01/04/introducing-apache-spark-datasets.html) :)

**Comment by drcrallen** [comment]
@gianm I mean http://spark.apache.org/docs/latest/sql-programming-guide.html#dataframes data frames. But yes, there already seems preference to move to data sets now as well (I had heard of those but forgot what they were called). Anyways, the point is I would avoid mentioning RDDs directly and simply refer to them as generic distributed data.

**Comment by gianm** [comment]
that sounds fair.

**Comment by fjy** [comment]
@drcrallen any suggestions for how to reword things?

**Comment by drcrallen** [comment]
👍

**Comment by drcrallen** [comment]
Docs only, tests won't reveal anything useful

**Pull request merged**
