### PR TITLE
fix kafka-indexing-service pom to not reference specific version 

### PR DESCRIPTION
**Pull request by himanshug**
but parent version for druid core dependencies

### CODE REVIEW

**Comment by gianm** [comment]
👍

**Comment by gianm** [comment]
we should do this for 0.9.2, right? I don't think we want snapshot dependencies in the release.

**Comment by gianm** [comment]
@himanshug gonna change it, but if I'm missing something let me know.

**Comment by himanshug** [comment]
@gianm sure, had put wrong milestone by mistake... it will be needed before we do the 0.9.2 cut.

**Comment by dclim** [comment]
thanks! 👍

**Pull request merged**
