### PR TITLE
Add better concurrency testing to IncrementalIndexTest

### PR DESCRIPTION
**Pull request by drcrallen**
Turned out to be queries running to fast (at least on my system). Added in some looping on the query portion to help make it more likely to hit concurrency conditions.

### CODE REVIEW

**Comment by drcrallen** [comment]
@guobingkun The PR in question

**Comment by drcrallen** [comment]
ugh, works locally fails in travis. Fixing

**Comment by drcrallen** [comment]
Travis good, bouncing to verify not a fluke

**Comment by drcrallen** [comment]
Failed in unrelated `io.druid.indexing.overlord.RemoteTaskRunnerTest` restarting

**Comment by drcrallen** [comment]
Travis good. Firing again to check for errors.

**Comment by xvrl** [comment]
:+1:

**Pull request merged**
