### PR TITLE
Fixes to JDBCExtractionNamespaceTest

### PR DESCRIPTION
**Pull request by drcrallen**
Fixes https://github.com/druid-io/druid/issues/2160

... hopefully

### CODE REVIEW

**Comment by drcrallen** [comment]
@fjy would you mind noting if it was a success or failure before closing it for this PR?

**Comment by fjy** [comment]
@drcrallen Run 1: SUCCESS

**Comment by drcrallen** [comment]
Thanks!

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
Success.

@fjy if this didn't fix it... then it is hard to reproduce.

**Comment by fjy** [comment]
@drcrallen I saw it once every 10 or so runs

**Comment by fjy** [comment]
@drcrallen we can merge this and see if it comes back again

**Comment by fjy** [comment]
:+1:

**Comment by fjy** [comment]
@drcrallen why does changing the order of things to close fix the timeout?

**Comment by drcrallen** [comment]
The way it was working was to drop the table then try to stop the future. This version stops the future first, and then deletes the table. That way the future won't be trying to do crazy stuff on a deleted table, and the drop table command isn't waiting to be interleaved between whatever the future is doing.

**Comment by fjy** [comment]
@drcrallen reopening this issue as it appears to be still happening

**Pull request merged**
