### PR TITLE
fix a bug in select-query.md which the property_form lack of the『granularity』

### PR DESCRIPTION
**Pull request by fanjieqi**
There result would be {"error"=>"Unknown exception",
"errorMessage"=>nil, "errorClass"=>"java.lang.NullPointerException",
"host"=>nil} when the json lack of『granularity』.

### CODE REVIEW

**Comment by fjy** [comment]
@fanjieqi where is teh bug fix? I just see the docs

Also, can you fill out http://druid.io/community/cla.html?

Thx,
FJ

**Comment by fanjieqi** [comment]
Sorry for my poor English.
I mean the property form in the select-query.md has a problem that it lack of the "granularity".
There isn't a bug in the code.

**Comment by fjy** [comment]
@fanjieqi can you fill out the CLA? http://druid.io/community/cla.html

**Comment by fanjieqi** [comment]
@fjy ，I've submitted the CLA. Could you please check Did I submit it successfully?

**Pull request merged**
