### PR TITLE
Replace the deprecated usage of NoneShardSpec

### PR DESCRIPTION
**Pull request by HyukjinKwon**
This PR replaces the deprecated usage for `NoneShardSpec`.

- **from**

```java
new NoneShardSpec()
```

- **to**

```java
NoneShardSpec.instance()
```

It seems this change was introduced in https://github.com/druid-io/druid/pull/2855; however it seems deprecated usage changes were missed.

In addition, this PR adds a newline at the end of file for 

```
benchmarks/src/main/java/io/druid/benchmark/query/SelectBenchmark.java
processing/src/main/java/io/druid/segment/serde/LongGenericColumnPartSerde.java
processing/src/test/java/io/druid/segment/CompressedVSizeIndexedV3SupplierTest.java
processing/src/test/java/io/druid/segment/data/CompressedIntsIndexedWriterTest.java
processing/src/test/java/io/druid/segment/data/CompressedVSizeIndexedV3WriterTest.java
processing/src/test/java/io/druid/segment/data/CompressedVSizeIntsIndexedWriterTest.java
processing/src/test/java/io/druid/segment/data/VSizeIndexedIntsWriterTest.java
processing/src/test/java/io/druid/segment/incremental/OnheapIncrementalIndexTest.java
druid/server/src/test/java/io/druid/segment/realtime/plumber/CoordinatorBasedSegmentHandoffNotifierTest.java
```

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Hi @nishantmonu51 and @gianm,
I just wonder if this is a legitimate change or.. it's just intendedly missed. Could you please take a look?

**Comment by nishantmonu51** [comment]
@HyukjinKwon: thanks for the PR, It was just missed in the refactoring.

**Comment by nishantmonu51** [comment]
👍

**Comment by gianm** [comment]
👍  thanks for the contrib!

@HyukjinKwon, could you please fill out the CLA at: http://druid.io/community/cla.html?

I think you may have already done this, but the record that looks like it might be from you doesn't have the right GitHub name.

**Comment by HyukjinKwon** [comment]
@gianm oh, yes I have already done but wrote the name wrong. I just did this again correctly. Thank you.

**Comment by gianm** [comment]
thanks @HyukjinKwon

**Pull request merged**
