### PR TITLE
add AirBnB Caravel to list of libraries

### PR DESCRIPTION
**Pull request by drcrallen**
@mistercrunch 's project got promoted.

### CODE REVIEW

**Comment by drcrallen** [comment]
@mistercrunch is it better to leave Panoramix on the list, or is that not going to be maintained anymore in favor of Dashed?

**Comment by fjy** [comment]
@drcrallen we should update Druid webpage including front page and remove panoranmix

Also, we need to update the Druid docs including tutorials

**Comment by drcrallen** [comment]
@fjy looks like the name might change in the near future. Suggest either leaving as proposed until there's more stability in naming, or simply waiting on this merge for a week or two (which means it might not get to be a part of 0.9.0)

**Comment by fjy** [comment]
@drcrallen can we update links to https://github.com/airbnb/caravel?

Please also make changes on druid website and in tutorials

**Comment by mistercrunch** [comment]
Caravel is official and the name won't change I promise. Sorry about the inconvenience, I'm really glad this it officially out!

**Comment by drcrallen** [comment]
@fjy fixed

**Comment by fjy** [comment]
👍

**Pull request merged**
