### PR TITLE
Expanded documentation for DataSketches aggregators.

### PR DESCRIPTION
**Pull request by gianm**
Originally written by @AlexanderSaydakov in druid-io/druid-io.github.io#448. I also added redirects and updated links to point to the new datasketches-extension.html landing page for the extension, rather than to the old page about theta sketches.

### CODE REVIEW

**Comment by AlexanderSaydakov** [comment]
Please note that the tuple sketch module is still in a pull request under review, not in master

**Comment by gianm** [comment]
Got it. In that case these should be tied to the same release, so we don't release the docs without the feature.

**Comment by gianm** [comment]
Is #5148 the tuple sketch?

**Comment by AlexanderSaydakov** [comment]
yes, thanks

**Comment by gianm** [comment]
Thanks @AlexanderSaydakov - I updated the milestone on #5148.

**Pull request merged**
