### PR TITLE
updating how to contribute guide

### PR DESCRIPTION
**Pull request by himanshug**
As we are getting more and more contributions, It is good reminder to have following in the guide.

- always update/add documentation.
- do not use author tags
- add license header to java files

### CODE REVIEW

**Comment by nishantmonu51** [comment]
+1

**Comment by drcrallen** [comment]
`JDBCExtractionNamespaceTest.testFindNew:261->assertUpdated:312 update check expected:<ba[z]> but was:<ba[r]>`

**Comment by drcrallen** [comment]
:+1: after travis

**Comment by himanshug** [comment]
@drcrallen build failure can be safely ignored if it was a UT failure and PR only updates the documentation :)

**Pull request merged**
