### PR TITLE
Unit test for BrokerServerView

### PR DESCRIPTION
**Pull request by guobingkun**
Unit test for BrokerServerView

### CODE REVIEW

**Comment by cheddar** [comment]
:+1:  Will leave this for a day or so to see if anyone else wants to read/comment.  If not, we can just merge.

**Comment by fjy** [comment]
:+1:

**Comment by xvrl** [comment]
@cheddar @guobingkun nothing wrong with the test per se, but I feel there's quite a bit of overlap between this and `BatchServerInventoryViewTest`. It seems like we're testing both here. Maybe we can move the ZK related tests to `BatchServerInventoryViewTest`, and simply mock `ServerInventoryView` to focus on testing `BrokerServerView` by itself?

**Comment by guobingkun** [comment]
Hi @xvrl, I prefer to use a concrete ```BatchServerInventoryViewclass``` here since it is easy to create and it makes the test more realistic given ```BrokerServerView``` depends on it heavily. I don't see any harm to conveniently test ```BatchServerInventoryView``` again in a different place though. Not sure if it is trivial to move ZK related stuff since ```BatchServerInventoryViewTest``` doesn't inherit ```CuratorTestBase```

**Pull request merged**
