### PR TITLE
Make segment creation guava 14 friendly

### PR DESCRIPTION
**Pull request by drcrallen**

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by drcrallen** [comment]
I'm testing this internally right now to make sure the fix works as expected, please hold off on merging for a bit.

**Comment by gianm** [comment]
@drcrallen this is for Spark compatibility, right? Is it possible to get Spark to do either classpath reordering or classloader isolation to work around this? I ask because in our testing, it *is* possible to get hadoop to work with the following versions, even when they are built against an older guava (using the properties mentioned in the other-hadoop.md doc file).

If it's possible to make Spark do something similar, I think that'd be good, because then we don't have to worry as much about updating our dependencies.

- emr472
- emr500
- quickstart.cloudera
- sandbox.hortonworks.com
- sequenceiq-230
- sequenceiq-240
- sequenceiq-241
- sequenceiq-250
- sequenceiq-251
- sequenceiq-252
- sequenceiq-260
- sequenceiq-271

**Comment by drcrallen** [comment]
@gianm I agree being able to upgrade reasonably would be nice. I'm testing `spark.driver.userClassPathFirst` to see if it works in this case

**Comment by drcrallen** [comment]
darn, that's a no on `spark.driver.userClassPathFirst` being a magic bullet.

```
16/09/27 23:24:31 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.NoSuchMethodError: com.google.common.io.ByteSource.concat(Ljava/lang/Iterable;)Lcom/google/common/io/ByteSource;
	at io.druid.segment.data.GenericIndexedWriter.combineStreams(GenericIndexedWriter.java:139)
	at io.druid.segment.StringDimensionMergerLegacy.writeValueMetadataToFile(StringDimensionMergerLegacy.java:206)
	at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:696)
	at io.druid.segment.IndexMerger.merge(IndexMerger.java:438)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:186)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:152)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13$$anonfun$21.apply(SparkDruidIndexer.scala:293)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13$$anonfun$21.apply(SparkDruidIndexer.scala:288)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1336)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13.apply(SparkDruidIndexer.scala:309)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13.apply(SparkDruidIndexer.scala:205)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by drcrallen** [comment]
Darn is failing with this patch still. I'm going to try and figure out how to handle this better and report back.

**Comment by drcrallen** [comment]
With this patch:
```
16/09/27 23:39:02 ERROR SparkDruidIndexer$: Error in partition [1]
java.lang.IncompatibleClassChangeError: Class io.druid.segment.data.GenericIndexedWriter$1 does not implement the requested interface com.google.common.io.InputSupplier
	at com.google.common.io.ByteStreams$6.openStream(ByteStreams.java:989)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:202)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:157)
	at io.druid.segment.StringDimensionMergerLegacy.writeValueMetadataToFile(StringDimensionMergerLegacy.java:206)
	at io.druid.segment.IndexMerger.makeIndexFiles(IndexMerger.java:696)
	at io.druid.segment.IndexMerger.merge(IndexMerger.java:438)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:186)
	at io.druid.segment.IndexMerger.persist(IndexMerger.java:152)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13$$anonfun$21.apply(SparkDruidIndexer.scala:293)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13$$anonfun$21.apply(SparkDruidIndexer.scala:288)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:294)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1336)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13.apply(SparkDruidIndexer.scala:309)
	at io.druid.indexer.spark.SparkDruidIndexer$$anonfun$13.apply(SparkDruidIndexer.scala:205)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:801)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$25.apply(RDD.scala:801)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by drcrallen** [comment]
@fjy a bit of a change since you reviewed.

Also @gianm I have verified this patch unblocks us from the spark side.

**Comment by drcrallen** [comment]
backporting

**Pull request merged**
