### PR TITLE
Typo fix in historical doc

### PR DESCRIPTION
**Pull request by ak08**

### CODE REVIEW

**Comment by jihoonson** [comment]
@ak08 thanks! Would you fill CLA http://druid.io/community/cla.html ?

**Comment by ak08** [comment]
@jihoonson Just did. So we need to fill the CLA for every repo we are submitting the PR to?

**Comment by jihoonson** [comment]
@ak08 that's a good question. You don't have to do that for now. But, we're currently migrating to Apache and I think some repositories will move and others are not. In this case, you might need to fill different CLAs for Apache and others.

**Comment by ak08** [comment]
Thanks @jihoonson

**Pull request merged**
