### PR TITLE
Enforce brace formatting with Checkstyle

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by himanshug** [comment]
is https://github.com/druid-io/druid/blob/master/druid_intellij_formatting.xml up-to-date to format code that would be compliant to the rules introduced ?

**Comment by leventov** [comment]
@himanshug yes

**Comment by himanshug** [comment]
:+1:

**Comment by leventov** [comment]
@himanshug could you please merge this PR?

**Pull request merged**
