### PR TITLE
Update IncrementalIndex.getMetricType() to return type name stored by ComplexMetricsSerde

### LINKED ISSUE #3339: Theta sketch column type inconsistency in segmentMetadata
segmentMetadata queries get the type of complex metrics from StorageAdapter's `getColumnTypeName`. On IncrementalIndex, that uses the AggregatorFactory's `getTypeName`. On QueryableIndex, it uses the ComplexColumn object's `getTypeName` (which in turn comes from the ComplexMetricSerde's `getTypeName`).

This works fine for hyperUnique and approximateHistogram, but not for theta sketches. They report "thetaSketch" for QueryableIndexes and "thetaSketchBuild" or "thetaSketchMerge" for IncrementalIndexes. This leads to segmentMetadata column responses looking like:

```
"someThetaSketchColumn": {
  "type": "STRING",
  "hasMultipleValues": false,
  "size": -1,
  "cardinality": null,
  "minValue": null,
  "maxValue": null,
  "errorMessage": "error:cannot_merge_diff_types"
}
```

Not sure what the best solution is, but this situation is not ideal. Probably ideally theta sketches should always be reported as type "thetaSketch".

Fixing this could potentially involve changing the implementation of StorageAdapter's `getColumnTypeName`, since it's not used for anything other than segmentMetadata queries.

### PR DESCRIPTION
**Pull request by himanshug**
… instead of AggregatorFactory.getTypeName()

Fixes #3339

### CODE REVIEW

**Comment by gianm** [comment]
I think this breaks the impl of `IncrementalIndex.getMetricClass`, which does `ComplexMetrics.getSerdeForType(metricDesc.getType())`. It also breaks IndexMerger, which does something similar. Maybe instead we should modify `IncrementalIndexStorageAdapter.getColumnTypeName` to do a ComplexMetrics.getSerdeForType on the type returned by II.

**Comment by gianm** [comment]
hmm, actually maybe it would be "fine" because SketchBuild and SketchMerge act the same way at the points that those methods are called. It still feels more right to defer the translation until the IncrementalIndexStorageAdapter though.

**Comment by himanshug** [comment]
@gianm ComplexMetrics.getSerdeForType(metricDesc.getType()) should always work where metricDesc.getType() is the value for appropriate ComplexMetricSerde.getTypeName() or else segment load/read will be broken.

**Comment by gianm** [comment]
Okay, I think you convinced me. In my understanding aggFactory.getTypeName() is the serde type used for extraction, and ComplexMetrics.getSerdeForType(aggFactory.getTypeName()).getTypeName() is the serde type used for query and storage. So it makes sense that the metricDesc should have the latter one.

ok, looks good 👍

**Comment by fjy** [comment]
👍

**Pull request merged**
