### PR TITLE
Fix static path example in batch ingestion docs

### PR DESCRIPTION
**Pull request by schmee**
Tiny PR that removes invalid whitespace in a path example  (as mentioned in https://groups.google.com/forum/#!searchin/druid-user/hadoop$20path|sort:relevance/druid-user/4L62vjor4NM/zkVbTxS7BwAJ). Also removes some trailing whitespace.

### CODE REVIEW

**Comment by b-slim** [comment]
👍

**Comment by fjy** [comment]
@schmee can you fill out the CLA here? http://druid.io/community/cla.html

**Comment by gianm** [comment]
👍 

@schmee, have you been able to fill out the CLA?

**Comment by Jdban** [comment]
Did @schmee ever fill out the CLA? 

If not, I already filled out the CLA, should I just make a PR for this issue that can be merged? I ran into this issue too, and I'd like to stop others from hitting the issue as well.

**Comment by fjy** [comment]
@Jdban yes please do that.

**Pull request closed without merging**
