### PR TITLE
adding router config to examples/config

### PR DESCRIPTION
**Pull request by himanshug**
for the testing times when I do want to run a router that works with other nodes configs in examples

### CODE REVIEW

**Comment by fjy** [comment]
I'd prefer not to have this in the examples as this is more for advanced use cases. I also want to remove the router at some point and have this logic live on the broker.

**Comment by xvrl** [comment]
:+1:  I believe it's fine to have examples, we have examples for other experimental features. If anything, the router is one of the least experimental features we have, and is actually being used in production at scale, unlike others.

Merging the functionality into the broker sounds like a good idea, but until we have a concrete proposal I don't think we should hold up on making the docs better.

**Comment by himanshug** [comment]
@fjy I added example config for middle manager as well (which I use time to time). 
Regarding router config, We are only putting router config in the code and not putting it in the documentation so it is still not so visible I guess.

**Comment by fjy** [comment]
okay, then I'm :+1:

**Comment by himanshug** [comment]
close/reopen to rebuild

**Pull request merged**
