### PR TITLE
Fix reference to INDEX_MAKER in IndexGeneratorJob.

### PR DESCRIPTION
**Pull request by gianm**
Fix reference missed in #1895

### CODE REVIEW

**Comment by drcrallen** [comment]
I don't think that's a "fix" so much as it is a "change hadoop to use IndexMerger"

**Comment by gianm** [comment]
@drcrallen this method was using IndexMerger before #1895, which unintentionally changed it to use IndexMaker

**Comment by drcrallen** [comment]
nooo.... that PR moved the persist method above it from maker to merger. you are now also moving the merge method from maker to merger.

**Comment by drcrallen** [comment]
https://github.com/druid-io/druid/pull/1895/files#diff-c08808f4e0bf4031ecbaac2cb044ca63L477

**Comment by gianm** [comment]
@drcrallen the intent of that PR was to remove LegacyIndexGeneratorJob and make IndexGeneratorJob behave like LegacyIndexGeneratorJob did. see also this if statement that was removed:

  https://github.com/druid-io/druid/pull/1895/files#diff-0c9aca6f2536c742356ddc0bae3df945L68

"isPersistInHeap" would always be false (because it wasn't documented) so LegacyIndexGeneratorJob would always have got used. So #1895 was trying to collapse those without changing any behavior, by adjusting IndexGeneratorJob to behave like LegacyIndexGeneratorJob did. But this method got missed.

**Comment by himanshug** [comment]
:+1:

**Comment by drcrallen** [comment]
@gianm much better explanation, thanks!

**Comment by drcrallen** [comment]
:+1: after travis

**Pull request merged**
