### PR TITLE
delete System.out.println() in test code

### PR DESCRIPTION
**Pull request by CHOIJAEHONG1**
Sorry for leaving off console debug output in test code.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by fjy** [comment]
this is failing UT

**Comment by navis** [comment]
#2393 didn't merged changes from #2291 correctly. Totally my bad. @CHOIJAEHONG1 Could you add false for map lookup in `GroupByQueryRunnerTest`?

**Comment by CHOIJAEHONG1** [comment]
@navis No problem. I will add it.

**Comment by navis** [comment]
:+1:

**Pull request merged**
