### PR TITLE
Disable cobertura travis portion

### LINKED ISSUE #3067: Stalls after running QueryGranularityTest
See https://github.com/druid-io/druid/pull/3060#issuecomment-223440871 and https://github.com/druid-io/druid/pull/3062#issuecomment-223473989

These stalls seem to be after QueryGranularityTest runs but before the next one runs? Also both were on java7. @jon-wei said he saw the same thing on a third PR, also java 7. Maybe related to `testDeadLock` and java 7 doesn't like having a thousand classloaders get made?

### PR DESCRIPTION
**Pull request by drcrallen**
As per https://groups.google.com/d/msg/druid-development/87cGFkrlqPo/8TOQpDFRBQAJ

Fixes #3067

### CODE REVIEW

**Comment by gianm** [comment]
@drcrallen what signs are there that this step is causing the stalls from #3067?

**Comment by drcrallen** [comment]
Every time I've checked that a failure for the bug in question it is on that step. You scroll back up the log to see what is running.

**Comment by gianm** [comment]
ok, fair enough.

👍

**Comment by nishantmonu51** [comment]
👍

**Pull request merged**
