### PR TITLE
Added more information about mysql

### PR DESCRIPTION
**Pull request by OrRon**
In the first look tutorial added some more information that was hard for me to find

### CODE REVIEW

**Comment by fjy** [comment]
@OrRon Thanks for this info. Where did you go to look at up the first tutorial? We recently changed the default metadata store to be derby to avoid having to set up another dependency. The information for MySQL should still be a part of the 0.8.0 docs

**Comment by OrRon** [comment]
@fjy I went to look for the first tutorial in the docs and in druid.io. I did work on druid 0.8.0 it was the last stable one.

**Comment by fjy** [comment]
@himanshug did we test that all the tutorials work after changing things to use derby?

**Comment by himanshug** [comment]
@fjy switch to derby did not happen in 0.8.0 , that should still use mysql.

@OrRon 
```
druid.metadata.storage.connector.createTables=true
```
is default value, are you sure putting this in changes anything for you?

**Comment by OrRon** [comment]
@himanshug , I created 'druid' user and granted privileges to it. Then I kept getting  sql errors. First I logged in and created druid db. Then the error changed to missing table. This was only solved after I added this flash. Also i made sure manually it open the tables.

I'm new to this code so there's a good chance I missed something. However, even if it is still default, I believe it's worth mentioning a little more details about the mysql connection

**Comment by himanshug** [comment]
@OrRon thanks for trying out and fighting your way through. For those unnecessary complications to new users, we have changed the example to use derby instead which requires no setup by the user. that change will reflect in 0.8.1 release, things will hopefully be better then.
However, given that default value for createTable is true, I think the change proposed in this PR is not necessary.

**Comment by himanshug** [comment]
@OrRon  also we have added more mysql specific notes in the latest docs https://github.com/druid-io/druid/pull/1571/files .

**Comment by OrRon** [comment]
@himanshug That looks really good!

**Pull request closed without merging**
