### PR TITLE
Make DateTime timezone aware

### PR DESCRIPTION
**Pull request by praveev**
#4276

Tested this very briefly on my test environment. May need more testing.

### CODE REVIEW

**Comment by jon-wei** [comment]
Adding this to 0.10.1 milestone since it fixes an issue in the milestone

There's a unit test failure in QueryGranularityTest

**Comment by praveev** [comment]
The unit tests were meant to work with date time not being timezone aware. I'm assuming we want to be consistent with 0.9.2 so I've changed the unit tests to work accordingly.

**Comment by xvrl** [comment]
@praveev @jon-wei It looks like #4276 is a regression somewhere else in the code. I'm not sure fixing it in PeriodGranularity is the right place, since it worked fine in 0.9.x

**Comment by praveev** [comment]
@xvrl this was introduced with support for timezone and refactor of granularity on this PR https://github.com/druid-io/druid/pull/3850 that was released with 0.10.0

**Comment by xvrl** [comment]
@praveev ah yes, I stand corrected, looks like #3850 broke timezones indeed

**Comment by leventov** [comment]
Tranquility probably cannot be updated to use 0.10.0 without this so it should directly go to 0.10.1

**Pull request merged**
