### PR TITLE
[Backport] Use daemon thread pool for AsyncHttpClient in emitters

### PR DESCRIPTION
**Pull request by gianm**
Backport of #5057 to 0.11.0.

### CODE REVIEW

**Comment by leventov** [comment]
@gianm thanks for creating those backports

**Comment by gianm** [comment]
@leventov no problem; I have a script to do it so it's pretty easy :)

**Comment by leventov** [comment]
@gianm could you please fix compilation

**Comment by gianm** [comment]
@leventov should be fixed now

**Comment by himanshug** [comment]
@gianm can you share your script ?

**Comment by gianm** [comment]
@himanshug it's https://gist.github.com/gianm/68145b09a55e6f6460a11ae9adfc25a4

For some reason the "milestone" and "labels" never get set, I'm not sure what's wrong there. If you ever figure it out let me know how to fix it :)

**Pull request merged**
