### PR TITLE
Remove SegmentLoaderConfig.numLoadingThreads config

### LINKED ISSUE #4421: Remove druid.segmentCache.numLoadingThreads config
Because of https://github.com/druid-io/druid/issues/3202#issuecomment-229394962

cc @drcrallen

### PR DESCRIPTION
**Pull request by leventov**
Fixes #4421

### CODE REVIEW

**Comment by jihoonson** [comment]
Looks that the CI failure is not relevant to this patch.

**Comment by drcrallen** [comment]
@leventov can you do the backport please?

**Comment by gianm** [comment]
Marked release notes, it deserves a mention since a config parameter has changed.

**Comment by drcrallen** [comment]
@gianm yeah, I wasn't sure if this one or the backport should get the release notes.

**Comment by himanshug** [comment]
@leventov @drcrallen why did we decide to remove `druid.segmentCache.numBootstrapThreads` config? we do want segment cache to be initialized in parallel on server startup.

**Comment by gianm** [comment]
@himanshug `numBootstrapThreads` is still there, just `numLoadingThreads` has been removed, for reasons from #4421.

**Comment by himanshug** [comment]
@gianm ah sorry, looked more carefully now, false alarm.

**Pull request merged**
