### PR TITLE
use reflection to call hadoop fs.rename to workaround different hadoop jar version in main and hdfs-storage extension class loader

### LINKED ISSUE #3786: BUG: publishing segments with kafka index service failed in druid 0.9.2
```
2016-12-17T22:46:33,776 WARN [task-runner-0-priority-0] io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver - Failed publishAll (try 4), retrying in 14,822ms.
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access method org.apache.hadoop.fs.FileSystem.rename(Lorg/apache/hadoop/fs/Path;Lorg/apache/hadoop/fs/Path;[Lorg/apache/hadoop/fs/Options$Rename;)V from class org.apache.hadoop.fs.HadoopFsWrapper
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-16.0.1.jar:?]
	at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.publishAll(FiniteAppenderatorDriver.java:417) [druid-server-0.9.2.jar:0.9.2]
	at io.druid.segment.realtime.appenderator.FiniteAppenderatorDriver.finish(FiniteAppenderatorDriver.java:256) [druid-server-0.9.2.jar:0.9.2]
	at io.druid.indexing.kafka.KafkaIndexTask.run(KafkaIndexTask.java:522) [druid-kafka-indexing-service-0.9.2.jar:0.9.2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:436) [druid-indexing-service-0.9.2.jar:0.9.2]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:408) [druid-indexing-service-0.9.2.jar:0.9.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalAccessError: tried to access method org.apache.hadoop.fs.FileSystem.rename(Lorg/apache/hadoop/fs/Path;Lorg/apache/hadoop/fs/Path;[Lorg/apache/hadoop/fs/Options$Rename;)V from class org.apache.hadoop.fs.HadoopFsWrapper
	at org.apache.hadoop.fs.HadoopFsWrapper.rename(HadoopFsWrapper.java:51) ~[?:?]
	at io.druid.storage.hdfs.HdfsDataSegmentPusher.push(HdfsDataSegmentPusher.java:119) ~[?:?]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.mergeAndPush(AppenderatorImpl.java:571) ~[druid-server-0.9.2.jar:0.9.2]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl.access$600(AppenderatorImpl.java:93) ~[druid-server-0.9.2.jar:0.9.2]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl$3.apply(AppenderatorImpl.java:467) ~[druid-server-0.9.2.jar:0.9.2]
	at io.druid.segment.realtime.appenderator.AppenderatorImpl$3.apply(AppenderatorImpl.java:455) ~[druid-server-0.9.2.jar:0.9.2]
	at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) ~[guava-16.0.1.jar:?]
	... 3 more
```

this seems related to #3650.

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #3786 with updated version of #3787 

Verified with hadoop-2.7.1 on a dev environment.

### CODE REVIEW

**Comment by b-slim** [comment]
👍 after tests.

**Comment by himanshug** [comment]
marking it WIP as it needs more testing and looks very hacky.

**Comment by himanshug** [comment]
@hamlet-lee  in my testing, straight forward `fs.getClass().getMethod(..)` does not appear to work because `rename` method is not PUBLIC. This is noted in the [javadocs](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getMethod-java.lang.String-java.lang.Class...- ) too
. So, I had to add a recursive impl to go over all superclasses to find the `rename` method. See `findRenameMethodRecursively(..)` added in `HadoopFsWrapper.java` .

I wonder how it is working for you without this recursive search. Have you done anything else special in your setup.

**Comment by himanshug** [comment]
I tested current patch with our hadoop cluster, seems to be working fine.

**Comment by hamlet-lee** [comment]
@himanshug rename is PUBLIC in DistributedFileSystem.  

```
public void rename(Path src, Path dst, final Rename... options) throws IOException {
```

**Comment by himanshug** [comment]
@hamlet-lee i see, it is increasing visibility in the override .. however, one of of my tests tested if for `LocalFileSystem` where it is not overridden to be made public. and in `FileSystem` it is declared to be protected.
So unfortunately, that assumption about it being public can't be made in general and recursion is still necessary.

thanks for pointing that out, now I understand why it worked for you without recursion.

**Pull request merged**
