### PR TITLE
Fix typo in docs (extension name is incorrect)

### PR DESCRIPTION
**Pull request by sherpc**

### CODE REVIEW

**Comment by fjy** [comment]
THanks @sherpc. Do you mind fillng out http://druid.io/community/cla.html?

**Comment by nishantmonu51** [comment]
👍

**Comment by fjy** [comment]
ping @sherpc

**Comment by fjy** [comment]
Moving milestone as author has not responded

**Comment by fjy** [comment]
Fixed by https://github.com/druid-io/druid/pull/3430

**Pull request closed without merging**
