### PR TITLE
Supporting firehoseV2 in RealtimeIndexTask

### PR DESCRIPTION
**Pull request by sirpkt**
Only realtimeManager, used in realtime node, supports firehoseV2 now.
So I modified RealtimeIndexTask to enable firehose V2 in indexing service.

### CODE REVIEW

**Comment by fjy** [comment]
@sirpkt Are you using Kafka to ingest data? If so, I strongly suggest you look at the Kafka Index Task from https://github.com/druid-io/druid/pull/2220. We have a few more PRs coming after that is merged which will provide exactly-once consumption of data from Kafka.

**Comment by fjy** [comment]
@gianm do u mind taking a look at this?

**Comment by sirpkt** [comment]
@fjy Yes, I use Kafka and felt some limitation on Kafka firehose. But #2220 looks great to me! Thank you for the information. I'll check that more.

**Comment by fjy** [comment]
@sirpkt with the new kafka indexing task, which supports exactly once ingestion from Kafka, is this PR still needed?

**Comment by sirpkt** [comment]
@fjy Oh, I forgot to close this issue.
Thanks.

**Pull request closed without merging**
