### PR TITLE
Update toc.md

### PR DESCRIPTION
**Pull request by anshbansal**

### CODE REVIEW

**Comment by fjy** [comment]
@anshbansal can you sign the CLA? http://druid.io/community/cla.html

**Comment by anshbansal** [comment]
@fjy Why do I need to share my mailing address?

**Comment by gianm** [comment]
@anshbansal I'm not sure (I didn't design the CLA form) but if this is a blocker for you then you might be able to get an answer from the email address druid-admin@metamarkets.com listed at http://druid.io/community/cla.html.

I hope you are able to sign the CLA, but if not we'll have to close this patch. Please let us know one way or the other, and thanks for your interest in the project.

**Comment by anshbansal** [comment]
@gianm  Signed the CLA.

**Pull request merged**
