### PR TITLE
fail task if finishjob throws any exception

### PR DESCRIPTION
**Pull request by pjain1**
Even if `plumber.finishJob()` throws any exception, the Task returns with Success status. In one of the cases persist and merge failed but still the Task status was success.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
LGTM, can we add a Unit test too ?

**Comment by pjain1** [comment]
sure

**Comment by gianm** [comment]
:+1:

**Comment by pjain1** [comment]
added unit test

**Comment by gianm** [comment]
test looks good, although a larger timeout might be useful for certain slowpoke CI systems.

**Comment by pjain1** [comment]
@gianm added method level timeout on tests. I guess 4 second is sufficient ?

**Comment by gianm** [comment]
sure, if we see travis failures we can increase it.

**Pull request merged**
