### PR TITLE
Indexing: Add forceExtendableShardSpecs option.

### LINKED ISSUE #3241: Hadoop indexing - use NumberedShardSpec instead of NoneShardSpec
Currently if Hadoop indexing has only one shard to generate for a particular time range, it will use NoneShardSpec. Using NumberedShardSpec(0, 1) instead of NoneShardSpec would help allocateSegment flows (like the Kafka indexing service) coexist with Hadoop indexing. allocateSegment (see #1896) depends on existing segment sets being extensible, which NoneShardSpec is not.

This could be an across the board change or it could be optional. I don't see any real usefulness for NoneShardSpec, so I lean towards making this change across the board.

### PR DESCRIPTION
**Pull request by gianm**
Fixes #3241. Optimistically adding to 0.9.2 as discussed on the dev sync today.

### CODE REVIEW

**Comment by dclim** [comment]
LGTM 👍

**Comment by nishantmonu51** [comment]
we need to add this flag to IndexTask also ?

**Comment by linbojin** [comment]
👍

**Comment by fjy** [comment]
👍

**Comment by gianm** [comment]
@nishantmonu51 I was hoping to get away without that, but since you asked, I added an option to IndexTask as well.

**Comment by dclim** [comment]
👍 for new changes

**Pull request merged**
