### PR TITLE
0.9.2

### PR DESCRIPTION
**Pull request by jacob-koren**
Aws key and secret should not be printed to log.

### CODE REVIEW

**Comment by leventov** [comment]
@jacob-koren thanks for contribution. Could you please make a PR against `master`, not `0.9.2` branch? We don't support old branches anyway.

**Comment by gianm** [comment]
@jacob-koren it's important to retain the job properties in the json, otherwise they cannot be sent down to the cluster. Perhaps a better approach would be masking known sensitive properties, like GuiceRunnable does when the CLI starts up.

**Comment by drcrallen** [comment]
Note that if you do a `PasswordProvider` for your aws secret, then you don't have to print anything delicate in logs. Also hadoop should be able to pull from classpath site xml's

**Comment by b-slim** [comment]
@jacob-koren can you please send a PR against master?  this PR is not going anywhere.

**Pull request closed without merging**
