### PR TITLE
remove need for tmp extensions dir

### PR DESCRIPTION
**Pull request by pjain1**
follow-up on #3130

### CODE REVIEW

**Comment by pjain1** [comment]
@fjy

**Comment by fjy** [comment]
@pjain1 can we do a quick test to make sure loading extensions (esp community extensions) works?

**Comment by pjain1** [comment]
@fjy I ran pull-deps to get the distinct-count module and verified that it was downloaded and druid process was able to load it. 

Also, I changed the classpath to be relative to the base distribution dir in the pull-deps command.

**Comment by gianm** [comment]
👍

**Comment by guobingkun** [comment]
Thanks @pjain1 !

**Pull request merged**
