### PR TITLE
[WIP] Skip the page cache when pulling data

### PR DESCRIPTION
**Pull request by bolkedebruin**
This PR addresses #4746 . The idea is as follows:

1. It is assumed that when a unzip/gunzip/copy from input stream happens it needs to skip the page cache (might need to be more fine-grained, need advice here)
2. It reads and writes in chunks, in order ti impact the cache as little as possible: every chunk will shortly reside in memory and then gets flushed. This could be user configurable (how to?) or could be the same size as the segment size. If the latter it means that at most one segment that is being pulled will be in the cache for a bit. It would probably mean the same speed for pulling, but little impact on the  cache.

This is WIP: it doesn't address Azure/AWS/GCP stuff yet. As mentioned I need some advice in how to deal with when the unpacking gets called. Is this only used for pulling? Sometimes byteSources with retries are used and implemented differently. Should those also be updated?

cc: @gianm @drcrallen

### CODE REVIEW

**Comment by bolkedebruin** [comment]
O interesting the check style errors do not happen locally.

**Comment by drcrallen** [comment]
While we've never had full support for Windows, we've never actually included code that explicitly forbade it. Can you document more about what will and won't work after this patch?

**Comment by bolkedebruin** [comment]
It will still work on Windows, but it will use the os cache then. There is no change in functionality for other oses.

**Comment by bolkedebruin** [comment]
Errors seem unrelated?

**Pull request closed without merging**
