### PR TITLE
Respect server-side sorting of tasks in coordinator console

### PR DESCRIPTION
**Pull request by gvsmirnov**
This is to replace https://github.com/druid-io/druid/pull/3349

The new behavior is thus:

* On load, the order as returned by the server is preserved
* Tables can be sorted by any column by clicking it

### CODE REVIEW

**Comment by gianm** [comment]
👍  LGTM

**Comment by fjy** [comment]
@gvsmirnov can you sign our CLA? http://druid.io/community/cla.html

**Comment by gianm** [comment]
@fjy he already did.

**Comment by fjy** [comment]
@gianm thanks

**Pull request merged**
