### PR TITLE
SegmentLoadDropHandler: Fix deadlock when segments have errors loading on startup.

### PR DESCRIPTION
**Pull request by gianm**
The "lock" object was used to synchronize start/stop as well as synchronize removals
from segmentsToDelete (when a segment is done dropping). This could cause a deadlock
if a segment-load throws an exception during loadLocalCache. loadLocalCache is run
by start() while it holds the lock, but then it spawns loading threads, and those
threads will try to acquire the same lock if they want to drop a corrupt segment.

I don't see any reason for these two locks to be the same lock, so I split them.

### CODE REVIEW

**Comment by jihoonson** [comment]
Does it make sense to backport to 0.12.1 even though this bug existed even before 0.12.0?

**Comment by gianm** [comment]
I think probably not, since it's not a regression and we already started the RC train. Although if we end up doing an rc2 for some other reason, maybe we could include this one too, since why not.

**Comment by b-slim** [comment]
👍

**Comment by jihoonson** [comment]
Since we will create another rc for 0.12.1, I think this is also worthwhile to backport.

**Comment by gianm** [comment]
@jihoonson sounds good to me, it's in #5755.

**Comment by jihoonson** [comment]
@gianm thanks!

**Pull request merged**
