### PR TITLE
HLL: More avoiding allocations

### PR DESCRIPTION
**Pull request by navis**
For https://github.com/druid-io/druid/pull/3314#issuecomment-237418119. 

Realized it's really a trivial now, but here it is.

### CODE REVIEW

**Comment by drcrallen** [comment]
@navis cool, are you able to get basic benchmarks for this?

**Comment by navis** [comment]
@drcrallen I did some tests and found it's barely meet the situation (swap and fold). The numbers are mostly identical. If we do some parallel folding it would be a little helpful but currently it seemed not useful. Can we close this?

**Comment by drcrallen** [comment]
@navis I would rather not add complexity unless it has specific results. The results don't have to be much (5% improvement is totally worth it), but they should be measurable.

**Comment by drcrallen** [comment]
@navis I'm going to remove milestone until you figure out if its reasonable to get benchmarks on it or not.

**Comment by navis** [comment]
@drcrallen I can only see one or two swapping case from 1000+ rows merging and seemed not possible to make any improvement on performance under varied data / conditions. I can definitely say that we can ignore this.

**Pull request closed without merging**
