### PR TITLE
fix bug in method reset() of ByteBufferHashTable.

### PR DESCRIPTION
**Pull request by zhangxinyu1**
see [issue](https://github.com/druid-io/druid/issues/5086)

### CODE REVIEW

**Comment by leventov** [comment]
@zhangxinyu1 thanks. please fix checkstyle

**Comment by zhangxinyu1** [comment]
@leventov thanks, I have fixed it.

**Comment by gianm** [comment]
@zhangxinyu1 Have you seen this issue in the wild, and if so what error message gets reported? Could you write a test that reproduces the problem and verifies the fix?

**Comment by zhangxinyu1** [comment]
@gianm Yes, I recently encountered this problem. The exception is 

_2017-11-14 19:10:12,201- epinephelinae.GroupByMergingQueryRunnerV2: Exception with one of the sequences!
java.lang.IllegalArgumentException
        at java.nio.Buffer.limit(Buffer.java:275) ~[?:1.8.0_121]
..._

I set druid.query.groupBy.bufferGrouperInitialBuckets=2147483647, so `maxBuckets` will always be `tableArenaSize/bucketSizeWithHash`.
 In the bad case,  tableArenaSize=1717986912, bucketSizeWithHash=16.  Then there is:

```
    tableStart = tableArenaSize - maxBuckets * bucketSizeWithHash;  // tableStart = 0
    int nextBuckets = maxBuckets * 2; //nextBuckets=1717986912/16*2= 214748364
    while (true) {
      // int nextTableStart = 0 - 214748364 * 16 = 858993472. However, long nextTableStart = (long) 0 - 214748364 * 16 = -3435973824
      final int nextTableStart = tableStart - nextBuckets * bucketSizeWithHash; 

      //858993472 >  tableArenaSize / 2, but -3435973824 <  tableArenaSize / 2
      if (nextTableStart > tableArenaSize / 2) {
        tableStart = nextTableStart;
        nextBuckets = nextBuckets * 2;
      } else {
        break;
      }
    }
   ...
    bufferDup.position(tableStart);  // postition(858993472)
    bufferDup.limit(tableStart + maxBuckets * bucketSizeWithHash); // 858993472 + 1717986912 = -1717986912, limit(-1717986912) will throw the illegalArgumentException.
```

**Comment by zhangxinyu1** [comment]
@gianm I use `git rebase master`, the return message is "Current branch fix-reset-bug-in-ByteBufferHashTable is up to date."

**Comment by leventov** [comment]
@zhangxinyu1 `git rebase upstream/master`, or whatever `https://github.com/druid-io/druid/tree/master` is called in your local repo

**Comment by leventov** [comment]
@zhangxinyu1 and `git fetch upstream master` before that

**Comment by zhangxinyu1** [comment]
@leventov Thanks! I have updated my local repo.

**Comment by leventov** [comment]
@zhangxinyu1 now you need force push to your fork on github

**Comment by zhangxinyu1** [comment]
@leventov I have forced push to my fork.

**Comment by leventov** [comment]
@zhangxinyu1 no, your branch: https://github.com/zhangxinyu1/druid/tree/fix-reset-bug-in-ByteBufferHashTable is still "305 commits behind master".

**Comment by zhangxinyu1** [comment]
@leventov ah thanks! now, https://github.com/zhangxinyu1/druid/tree/fix-reset-bug-in-ByteBufferHashTable is "5 commits ahead of druid-io:master".

**Comment by leventov** [comment]
It shouldn't be 5 commits ahead of master, it should be 2 or 3 commits ahead of master, only those that you made. Please don't use this thread for free Git & Github usage training.

**Comment by zhangxinyu1** [comment]
@leventov I'm so sorry. Thanks for your training, you're so nice. I only know the simplest usage of git. I will close this pr, and reopen another pr.

**Pull request closed without merging**
