### PR TITLE
Even faster stupid pool

### PR DESCRIPTION
**Pull request by drcrallen**
Improvement over #1601 
now 4~5x as fast by recycling the objecthandler itself instead of just the object

#1601 : 4.7~5.1 ops/us
This PR: 22.752 ± 0.136  ops/us

### CODE REVIEW

**Comment by himanshug** [comment]
improvement is great. But, if I am reading it right then, now that ObjectResourceHolder itself is recycled, it will not in general be GC'd and hence finalize() is not called and warning about "Not Closed" is never printed if client code forgets to call close and that can potentially cause memory leak.
At one point I was tempted to change this but I remember @cheddar had very strong opinion about it.

**Comment by drcrallen** [comment]
@himanshug that's a good point. Is the finalize just a memory leak tool then? to find out who takes resources and doesn't release them?

**Comment by himanshug** [comment]
yes, i think so.
BTW, if the change in this PR is acceptable then I think we can remove that finalize() as well because it will not be serving any purpose anymore and if there is not a strong reason then one should in general avoid overriding finalize() for all sorts of reasons.

**Comment by cheddar** [comment]
So, from what @himanshug found in the past, the mere existence of the `finalize()` causes significant increased cost in creating the object.

It does exist there for memory leak protection and has caught memory leaks in the past.  Memory leaks of this kinda are pretty gnarly and I'm still very wary of removing this check.  As I said on the previous "improve stupid pool perf" PR, I believe that the speed of `StupidPool` is a symptom and the actual problem is that the ObjectStrategy objects are checking one of these out every time it needs to decompress something.  A better fix, in my mind, would be to restructure it so that a single buffer is checked out for each column and that reference is re-used as long as that column is in use.

**Comment by drcrallen** [comment]
@cheddar Given the significant changes to debugging I'm going to close for now. At a cursory glance the re-use of compression buffers is not a drop-in solution due to some of the key areas they would be needed lacking a `close()` to put the buffers back in the pool.

**Pull request closed without merging**
