### PR TITLE
fix mvn soft link for integration tests

### PR DESCRIPTION
**Pull request by nishantmonu51**

### CODE REVIEW

**Comment by fjy** [comment]
can you add some info on why this was needed?

**Comment by nishantmonu51** [comment]
its not needed for running the tests, when building jars outside container as we do in tests, it was there to run the tests from fetching the via git, I came across this broken link while doing some testing in container, have commented out the mvn installation by default and added comment

**Comment by xvrl** [comment]
@nishantmonu51 the maven link works for me. If this is not needed for integration testing, let's just remove it from the docker image.

**Comment by nishantmonu51** [comment]
removed

**Pull request merged**
