### PR TITLE
Make buildV9Directly the default.

### PR DESCRIPTION
**Pull request by gianm**
Reviving #3417.

I think it makes sense to make this the default in 0.9.3 and aim to remove the old code path in 0.10.0.

We've been using this code path in our clusters for a long time and there are a number of community members using it as well. It's also well unit tested; lots of tests parameterize and verify behavior against both code paths.

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
We are also using this in production without any problems.

**Comment by b-slim** [comment]
👍

**Comment by fjy** [comment]
👍

**Comment by drcrallen** [comment]
I need to re-iterate here that this will slow down the validation process for 0.9.3 from our side as we do thorough evaluation of the v9 directly vs v8 then v9 build methods.  So please have some extra patience.

**Pull request merged**
