### PR TITLE
remove min/max aggregator factory 

### PR DESCRIPTION
**Pull request by himanshug**
they have been replaced by double[min/max] . we've supported both for transitioning in past few releases.

### CODE REVIEW

**Comment by xvrl** [comment]
Have we officially deprecated them in the docs? We didn't put anything in any previous release notes about deprecating them. I would suggest we make a clear effort to message the deprecation in the next release before removing them.

**Comment by himanshug** [comment]
@xvrl how about putting the messaging of deprecation in 0.8.3 release and then removing in 0.9.0 ?
min/max had been removed from docs when we implemented double[min/max] .

**Comment by xvrl** [comment]
@himanshug that sounds like a plan, unless of course we plan to one day have type-agnostic operators in which case we could just leave things in until then :)

**Comment by himanshug** [comment]
@xvrl noted the deprecation in https://github.com/druid-io/druid/pull/2022

**Comment by himanshug** [comment]
deprecation has been noted in 0.8.3 release notes, so this is safe to be merged.

**Comment by fjy** [comment]
:+1:

**Comment by guobingkun** [comment]
:+1:

**Pull request merged**
