### PR TITLE
Update Apache Avro to 1.8.2

### PR DESCRIPTION
**Pull request by Fokko**
Hi all,

I still experience some error while importing datetime columns:
```
2017-11-10T20:41:37,813 ERROR [main] org.apache.hadoop.mapred.YarnChild - Error running child : java.lang.NoSuchMethodError: org.apache.avro.Schema.setLogicalType(Lorg/apache/avro/LogicalType;)V
	at org.apache.avro.LogicalType.addToSchema(LogicalType.java:72)
	at org.apache.parquet.avro.AvroSchemaConverter.convertField(AvroSchemaConverter.java:309)
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:241)
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:231)
	at org.apache.parquet.avro.DruidParquetReadSupport.prepareForRead(DruidParquetReadSupport.java:98)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.initialize(InternalParquetRecordReader.java:175)
	at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:190)
	at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:147)
	at org.apache.hadoop.mapreduce.lib.input.DelegatingRecordReader.initialize(DelegatingRecordReader.java:84)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:548)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:786)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

I need to exclude some of the avro pulled in with other dependancies. I'm also working to get all the Avro dependancies on the same level:
https://github.com/apache/parquet-mr/commit/ba7b8ba69984bd2c91c41eeab9a2f030661e5a49
But this is something for the future, but it would be nice to have Druid compatible with Avro 1.8.2

Old Dependancy tree:
https://gist.github.com/Fokko/e2f6d805c4f9a0b70f8ff34f12c952f0
New one:
https://gist.github.com/Fokko/7bcce0b547bc79caa7bd95ad54c63a4c

I did a test and I'm able to parse datetime fields in Parquet.

Cheers, Fokko

### CODE REVIEW

**Comment by Fokko** [comment]
@gianm Do you have time to take a look at this? We've deployed this on our acceptance cluster and it works as expected. We're now able to ingest Parquet DateTime columns. This is a nice feature because it is much cheaper to extract the datetime from this DateTime field instead of parsing it using jodatime.

Cheers, Fokko

**Comment by gianm** [comment]
@Fokko a few of the unit tests are failing with "java.lang.NoClassDefFoundError: org/apache/avro/io/DatumReader", see the Travis link for details: https://travis-ci.org/druid-io/druid/jobs/300659465

This may be some artifact of the tests or it may point to a real issue; maybe avro is used out of the box for something in the packages where you have excluded it.

Could you take a look into the tests please?

**Comment by Fokko** [comment]
Hi @gianm 

Thanks for pointing out. I've removed one exclusion for the test scope and it seems to work again. Right now I'm stuck at the flakey test again. Do you have any tricks to get that one passing?

Cheers, Fokko

**Comment by gianm** [comment]
I don't have any tricks there, but I'll retry it for you now. @jihoonson is trying to make it more reliable in #5077, at least.

**Comment by gianm** [comment]
@Fokko could you please merge master into your branch and re-push it? It should help with the flaky test.

**Comment by gianm** [comment]
Oh nevermind, I missed that they look good now. This looks good to me so I'll commit it.

**Pull request merged**
