### PR TITLE
Kafka Indexing - optionally reset dataSourceState when topic in state has gone stale 

### PR DESCRIPTION
**Pull request by freakyzoidberg**
The proposed change is to reset the datasourceMetadata when it is detected that the topic in the state doesn't match the one in the config, if and only if the supervisor is configured with the pre-existing flag **resetOffsetAutomatically** set to true.

Currently changing the topic of a datasource after a previous commit, cause subsequent task to fail when publishing, arguing that the datasource state doesn't match the config.

There is reset endpoint that can be called to solve the issue, but this require the supervisor to be started.

### CODE REVIEW

**Comment by jihoonson** [comment]
I'm not sure the travis failure relates to this patch. Would you please close and reopen this pr to restart travis ci?

**Comment by freakyzoidberg** [comment]
Sure, there was an issue in the test, which was causing the travis run to timeout, should be solved now

**Comment by freakyzoidberg** [comment]
Closed this PR to cleanup the commits

**Comment by leventov** [comment]
@freakyzoidberg please don't close and recreate PR in this situation in the future, just add commits on top.

**Comment by freakyzoidberg** [comment]
Sure, sorry about that

**Pull request closed without merging**
