### PR TITLE
Attempt to fix RTRTest transient failures

### PR DESCRIPTION
**Pull request by nishantmonu51**

### CODE REVIEW

**Comment by nishantmonu51** [comment]
attempt 1 passed, retrying.

**Comment by nishantmonu51** [comment]
Attempt 2 passed, retrying

**Comment by fjy** [comment]
@nishantmonu51 any idea what the failure could be?

**Comment by fjy** [comment]
it is very difficult to reproduce the error, even with constant travis runs

**Comment by nishantmonu51** [comment]
the failure seemed to be related to the task assignment timeout (1 sec) being low for travis machines. 
Have increased it to 5 sec now.

**Comment by nishantmonu51** [comment]
this seems good to go now and it should hopefully fix #2199 & fix #2185

**Comment by fjy** [comment]
@nishantmonu51 okay, merging the fixes and will keep an eye out on if they occur again

**Comment by fjy** [comment]
:+1:

**Pull request merged**
