### PR TITLE
(Backport #1681) Fix overlapping segments in IngestSegmentFirehose, DatasourceInputFormat.

### PR DESCRIPTION
**Pull request by drcrallen**

### CODE REVIEW

**Comment by fjy** [comment]
Will merge after travis

**Comment by xvrl** [comment]
this broke for real, not a spurious test failure this time :(

**Comment by himanshug** [comment]
@drcrallen is there an automated way of generating backport PRs or is this created manually with specific commits cherry-picked?

**Comment by drcrallen** [comment]
@himanshug cherry-picked.

**Comment by drcrallen** [comment]
@xvrl Problem in test, not code

**Pull request merged**
