### PR TITLE
fix zkcoordinator inject

### PR DESCRIPTION
**Pull request by fjy**

### CODE REVIEW

**Comment by gianm** [comment]
:+1:

**Comment by drcrallen** [comment]
can `io.druid.server.coordination.ZkCoordinatorTest` have an injection test?

**Comment by drcrallen** [comment]
Or at least file a github issue about lack of injection test and do it after fix goes in

**Comment by fjy** [comment]
@drcrallen i file an issue

**Comment by drcrallen** [comment]
:+1:

**Comment by xvrl** [comment]
I'm not sure I understand what this PR is fixing, was something broken? How did it work before?

**Comment by xvrl** [comment]
ah I see, this was broken by #1895

**Pull request merged**
