### PR TITLE
Fix some unemitted alerts.

### PR DESCRIPTION
**Pull request by gianm**
Fixes some cases where alert objects were created but not emitted.

### CODE REVIEW

**Comment by jihoonson** [comment]
+1 after travis.

**Comment by leventov** [comment]
Is there a way to prevent this situation in the future on type-level system or with static analysis?

**Comment by gianm** [comment]
Maybe it's possible to have a static analysis check for ignored return values of type `AlertBuilder`. It's suspicious if one is created and then neither emitted nor assigned to a variable.

Or maybe change the API to

```java
log.makeAlert().withData("x", "y").emit("message");
```

rather than

```java
log.makeAlert("message").withData("x", "y").emit();
```

which may make it tougher to forget to emit.

**Comment by drcrallen** [comment]
@gianm can you log that as an improvement request issue? That sounds like the right thing to do.

**Comment by gianm** [comment]
@drcrallen raised #5154

**Pull request merged**
