### PR TITLE
I'm not your mom, indexing-service/test... cleanup after yourself

### PR DESCRIPTION
**Pull request by drcrallen**

### CODE REVIEW

**Comment by guobingkun** [comment]
Changes in TaskLifecycleTest.java are covered in #1480  :)

**Comment by drcrallen** [comment]
@guobingkun good call. Removed that part from the PR

**Comment by guobingkun** [comment]
:+1:

**Comment by drcrallen** [comment]
Transient error in Java8 test: `AnnouncerTest.testSanity:97 Wait for /test1 to be created` re-opening to try again

**Comment by fjy** [comment]
:+1:

**Pull request merged**
