### PR TITLE
backport #3506 and #3456

### PR DESCRIPTION
**Pull request by pjain1**
#3506 -secure BrokerQueryResource endpoints
#3456 - stop supervisor in case of metadata failures

### CODE REVIEW

**Comment by gianm** [comment]
Appears to be a backport of #3506 and #3456.

👍  after travis

**Comment by drcrallen** [comment]
Please update the description to be more descriptive.

**Comment by gianm** [comment]
@pjain1 could you add the PRs being backported to the title or description? Just asking because that way, the squashed commit message will have them, and the git logs for 0.9.2 will be easier to read.

**Comment by pjain1** [comment]
updated description

**Pull request merged**
