### PR TITLE
Make HadoopTasks's classloader a single one

### PR DESCRIPTION
**Pull request by drcrallen**
While having control of classloaders is a noble goal, it looks like the reality is that we aren't there yet.

The prior isolation method worked fine in the "normal" case, but enough industry deployments do weird stuff with classpaths that I'm proposing a more simplistic approach to classpath isolation in hadoop jobs as per this PR.

This would be worth revisiting at some point in the future.

### CODE REVIEW

**Comment by fjy** [comment]
@drcrallen don't forget about CLI hadoop indexer

also, can you update the docs if necessary?

**Comment by drcrallen** [comment]
@fjy this only pertains to things which extend HadoopTask and use the HadoopTask way of isolating things. As such I don't think it affects the Cli Hadoop Indexer

**Comment by drcrallen** [comment]
This shouldn't require any doc updates because all the config is handled in the same manner, it is just more lenient about weird jar packings that deployments might use.

**Comment by himanshug** [comment]
@guobingkun can you pls run this patch on our mirror to confirm if this fixes the issue?

**Comment by drcrallen** [comment]
@himanshug I spoke with him earlier and he confirmed it fixed the issue, would be worth hearing directly from him though.

**Comment by guobingkun** [comment]
Yes, this fixed our internal build. I assume this still fixes #2428. 
@gianm Would you like to try this on EMR as well?

**Comment by drcrallen** [comment]
@guobingkun yes, it still loads extension jars into HadoopTask classloader

**Comment by himanshug** [comment]
:+1:

**Comment by fjy** [comment]
@drcrallen does this work with extensions included such as datasketches?

**Comment by drcrallen** [comment]
@fjy the PRs I've been putting in about HadoopTask's classloader don't change the behavior of the job once it is running in hadoop. It only changes the behavior on the peon before the task gets registered with hadoop. As such the Y! data scketches or other extensions (like the spark indexer) should be at least as functional as they were in the 0.8.x series.

**Comment by himanshug** [comment]
@fjy our build tests sketches in a hadoop task (soon to be contributed) as well which passed with this patch.

**Comment by guobingkun** [comment]
@drcrallen I tried this patch with the generated tarball, unfortunately it still gave me ```java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream```.

To replicate this, you could use the tarball to run overlord in local mode, and then submit a hadoop index task.

**Comment by drcrallen** [comment]
@guobingkun thanks will try

**Comment by drcrallen** [comment]
I get the error also... grrr... but `Class.forName("org.apache.hadoop.fs.FSDataInputStream", false, classLoader)` works just fine. Investigating

**Comment by drcrallen** [comment]
full error is ```        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:168) ~[druid-indexing-service-0.9.0-rc2-SNAPSHOT.jar:0.9.0-rc2-SNAPSHOT]
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
        at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[druid-indexing-service-0.9.0-rc2-SNAPSHOT.jar:0.9.0-rc2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:168) ~[druid-indexing-service-0.9.0-rc2-SNAPSHOT.jar:0.9.0-rc2-SNAPSHOT]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_73]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_73]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_73]
        at io.druid.indexing.common.task.HadoopIndexTask$HadoopDetermineConfigInnerProcessing.runTask(HadoopIndexTask.java:277) ~[druid-indexing-service-0.9.0-rc2-SNAPSHOT.jar:0.9.0-rc2-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
        at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:168) ~[druid-indexing-service-0.9.0-rc2-SNAPSHOT.jar:0.9.0-rc2-SNAPSHOT]
        ... 7 more```

**Comment by drcrallen** [comment]
thread context classloader at HadoopIndexTask.java:277 contains class in question.

**Comment by drcrallen** [comment]
ah

`Class.forName("io.druid.indexer.HadoopDruidIndexerConfig", false, Thread.currentThread().getContextClassLoader()).getClassLoader()` reveals `AppClassLoader`

something didn't get isolated properly. Investigating

**Comment by drcrallen** [comment]
Fixed, was missing null in `final ClassLoader classLoader = new URLClassLoader(localClassLoaderURLs.toArray(new URL[localClassLoaderURLs.size()]), null);`

works now

**Comment by gianm** [comment]
@guobingkun yes, I can test it out today.

**Comment by gianm** [comment]
@drcrallen @guobingkun works for me on EMR. :+1:

**Pull request merged**
