### PR TITLE
Fix issue-4690

### PR DESCRIPTION
**Pull request by akashdw**
Fix issue  https://github.com/druid-io/druid/issues/4690

### CODE REVIEW

**Comment by himanshug** [comment]
:+1:

**Comment by leventov** [comment]
@akashdw please give readable titles to PRs in the future, because having "Fix issue #4690" is not helpful in Git history. If there are no better options the title of the PR may simply repeat the title of the issue being fixed.

**Comment by akashdw** [comment]
@leventov 👍

**Comment by himanshug** [comment]
@gianm @jon-wei : @pjain1 reminded me that this is broken in 0.10.1 release , however it is not severe enough a issue to require 0.10.1 patching. we should probably note this as a known issue in 0.10.1 release notes and point to this PR.
makes sense ?

**Comment by jon-wei** [comment]
@himanshug sounds good, I'll add this to the release notes

**Comment by himanshug** [comment]
@jon-wei sure, thanks

**Comment by jon-wei** [comment]
@himanshug strange, 0.10.1 seems to have this PR already:

https://github.com/druid-io/druid/blob/0.10.1/examples/conf-quickstart/druid/_common/common.runtime.properties

the history doesn't show it however:
https://github.com/druid-io/druid/commits/0.10.1/examples/conf-quickstart/druid/_common/common.runtime.properties

**Comment by akashdw** [comment]
@himanshug @jon-wei This was broken in master build not in 10.1.

**Comment by himanshug** [comment]
@akashdw thanks, sounds like it was a false alarm  :) .

**Pull request merged**
