### PR TITLE
better faster smaller roaring bitmaps

### PR DESCRIPTION
**Pull request by xvrl**

### CODE REVIEW

**Comment by drcrallen** [comment]
:+1:

**Comment by gianm** [comment]
Are there any compatibility concerns? (can this version read the older bitmaps? can older versions read these newer bitmaps?)

**Comment by drcrallen** [comment]
@gianm I asked the same thing here: https://github.com/metamx/bytebuffer-collections/pull/15#issuecomment-132376385

**Comment by gianm** [comment]
So it sounds like this version can read older bitmaps, but older versions cannot read the newer bitmaps (because we are going to be writing optimized bitmaps). That sounds OK, since we tell people to update historicals first anyway.

On the [bytebuffer-collections diff](https://github.com/metamx/bytebuffer-collections/pull/15/files#diff-600376dffeb79835ede4a0b285078036R112) I think we should change the roaring version to a specific version rather than a range. Builds with version ranges are not reproducible, and it is good for builds to be reproducible.

**Comment by xvrl** [comment]
@gianm released a new version with fixed dependency

**Comment by gianm** [comment]
:+1:

**Pull request merged**
