### PR TITLE
SQL + VirtualColumns = best friends forever.

### PR DESCRIPTION
**Pull request by gianm**
The idea is that for doing projections we need "one layer to rule them all" rather than the hodge podge we have now where some combination of the following features needs to be used:

- extractionFns
- dimensionSpecs
- expression based aggregators
- postAggregators

But the bridges between features are lacking. So for example, you can't write a math expression that refers to the output of an extractionFn. Or vice versa. One example of how this hurts is that in SQL we can translate `SUM(x + y)` (using an expression based aggregator) but we cannot translate `GROUP BY x + y` (there's no equivalent construct that works from dimension specs). On the flip side, we can do `GROUP BY CHARACTER_LENGTH(x)` (using an extractionFn) but we can't do `AVG(CHARACTER_LENGTH(x))` (aggregators can't refer to extractionFns).

So the idea with this patch is to make virtual columns the "one layer to rule them all" by building a bridge from extractionFns to virtual columns (there's already a bridge from math expressions). That makes it possible to translate all of the examples above. The SQL translator will only use virtual columns if necessary in this patch, so not all queries need them, but some do. See some of the new tests in CalciteQueryTest for examples.

I'm willing to accept that virtual columns might not be the right answer for this, and maybe instead the "one layer to rule them all" should be something else, like extractionFns or math expressions. But we do need something and this patch shows what the world would be like if that thing was virtual columns.

Changes in this patch:

- SQL can use virtual columns as a projection layer for queries.
- Add ExtractionFnVirtualColumn, which allows creating a virtual column based on an extractionFn.
- Add "requiredColumns" method to DimFilter, which the SQL/VC code needed.
- Allow math expressions to implicitly treat strings as numbers.

Not included in this patch, but some future work might include (for context while reviewing):

- Ability to do projections for post-groupby "select", "order by", and "having", for example a query like `SELECT SUBSTRING(dim, 1, 2) FROM tbl GROUP BY dim` or like `SELECT dim1 FROM druid.foo GROUP BY dim1 ORDER BY SUBSTRING(dim1, 2)`. We can't do either of those queries right now, because we can't apply functions to columns after grouping. We could make this possible via a similar projection layer like `postGroupingVirtualColumns`. Or something else along those lines.
- Revive the "arity" addition to extractionFns from #3091 (see https://github.com/druid-io/druid/pull/3091#issuecomment-281859566) and maybe also the ability to have different return types too, not just strings, so extractionFns can become more useful.
- Implement a case/when that can return either strings or numbers somehow, maybe as an extractionFn.

### CODE REVIEW

**Comment by fjy** [comment]
:+1: I like the idea

**Comment by jihoonson** [comment]
I love this idea too. Maybe we need to rename ```VirtualColumn``` to something more general like ```ProjectionExpression```?

**Comment by gianm** [comment]
@jihoonson hmm, I don't mind the current name. But yeah it could be thought of either way.

**Comment by gianm** [comment]
I have to admit. Sometimes I think that a better approach, instead of this, would be to extend expressions to be able to return strings, and implement some extra functions for expressions like strlen, substring, etc. Then expressions could be the one layer to rule them all.

**Comment by gianm** [comment]
Closing this as I'm now thinking about doing it a different way.

**Pull request closed without merging**
