### PR TITLE
Fixing the regression caused by #1172

### PR DESCRIPTION
**Pull request by himanshug**
Fixing the regression caused by #1172

Reverted the use of ChainedExecutionQueryRunner and used simple approach to enforce eagerness.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by nishantmonu51** [comment]
this failure was undetected from a long time, 
can we also add a UT that catches it ?

**Comment by xvrl** [comment]
@himanshug Happy to merge once you squash commits. Tests would be nice indeed

**Comment by himanshug** [comment]
Sure, I'm going to add the UT pretty soon.

However, I wanted to keep the commit history as it has the story of what happened. If I squash them then the information of how really eagerness is applied is lost. currently, one could go to the specific commit (https://github.com/himanshug/druid/commit/5473f7aa4fbc2a1a35d1e588fd912a59c79f065e) to see what really changed overall. Please let me know if that does not sound reasonable to you.

**Comment by xvrl** [comment]
@himanshug sounds reasonable. In that case let's update the second commit message to indicates what this fixes, so it doesn't look like we undo and redo the same thing.

**Comment by himanshug** [comment]
@xvrl @nishantmonu51  added the UT

**Comment by xvrl** [comment]
@himanshug great, once build passes I'll merge, and then we can cherry-pick into 0.7.x branch to hopefully release 0.7.3 as stable :)

**Pull request merged**
