### PR TITLE
Include hybrid and caffeine in cache docs and show caffeine as default

### PR DESCRIPTION
**Pull request by stuartmclean**
Please see discussion here: https://groups.google.com/forum/#!topic/druid-user/U0q_fHJtUwo

### CODE REVIEW

**Comment by gianm** [comment]
Merging this without Travis passing, since the changes are just to the docs, and they can't possibly affect tests passing.

**Comment by stuartmclean** [comment]
Great stuff - I've signed the CLA.

**Comment by gianm** [comment]
Thanks

**Comment by leventov** [comment]
Related: #6161

**Pull request merged**
