### PR TITLE
fix SketchEstimate post aggregator's getComparator() and test changes to verify same

### PR DESCRIPTION
**Pull request by himanshug**

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by gianm** [comment]
@himanshug i think this doesn't work if `errorBoundsStdDev` is set (as that makes the post aggregator return `SketchEstimateWithErrorBounds` which has no natural ordering).

**Comment by gianm** [comment]
it sounds ok to me to use a comparator that works off the `estimate` in that object, although because that is not consistent with equals, it may be better for that to be a separate Comparator instance rather than the natural ordering.

**Comment by himanshug** [comment]
@gianm thanks, fixed that.

**Comment by gianm** [comment]
:+1: after travis

**Comment by fjy** [comment]
@himanshug needs to be backported

**Pull request merged**
