### PR TITLE
Allow user to set cost balancer threads more than or equal to the number of cores.

### PR DESCRIPTION
**Pull request by nishantmonu51**
Allow user to set cost balancer threads more than or equal to the number of cores.
FWIW, I am unable to set balancer threads to 4 on a machine having 2 cpu cores.

### CODE REVIEW

**Comment by xvrl** [comment]
👍

**Comment by himanshug** [comment]
:+1: for the code change
but wondering if it helps to have more threads than cores as compute cost appears to be cpu bound really?

**Comment by xvrl** [comment]
@himanshug the current code caps at cores - 1, which is a problem for us when we have 2 cores

**Comment by xvrl** [comment]
we currently spend most of our time doing those cost calculations, so being able to use all cores is beneficial

**Comment by himanshug** [comment]
ok so you really want to set num to be equal to cores not more than that really, that makes sense.

**Pull request merged**
