### PR TITLE
Add timestampSpec to metadata.drd and SegmentMetadataQuery

### PR DESCRIPTION
**Pull request by kaijianding**
Here is the requirement [https://groups.google.com/d/msg/druid-development/3sdpPR_d_iQ/rCZszfwxDwAJ](url).

In this patch, 
1. add timestampSpec to metadata.java
2. add timestampSpec info in SegmentMetadataQuery and update the doc

### CODE REVIEW

**Comment by gianm** [comment]
👍

**Comment by fjy** [comment]
@kaijianding can you sign the CLA here? http://druid.io/community/cla.html

**Comment by kaijianding** [comment]
signed. @fjy

**Comment by fjy** [comment]
👍

**Pull request merged**
