### PR TITLE
update kafka client for kafka indexing service to 0.9.0.1

### PR DESCRIPTION
**Pull request by dclim**

### CODE REVIEW

**Comment by gianm** [comment]
👍 

back story: 0.9.0.1 fixes some critical bugs in the new consumer, which we use in this extension.

**Comment by dclim** [comment]
We hit a nasty bug where problems talking to a Kafka broker would cause the Kafka consumer to go into an infinite loop which wouldn't exit even when the Kafka broker came back. This effectively brought down the supervisor. The fix was introduced in 0.9.0.1 as part of this issue: https://issues.apache.org/jira/browse/KAFKA-2880

**Comment by fjy** [comment]
👍

**Comment by drcrallen** [comment]
@dclim pleas remember to backport.

**Pull request merged**
