### PR TITLE
Add gs:// hdfs support

### PR DESCRIPTION
**Pull request by erikdubbelboer**
Used to access google cloud storage.

### CODE REVIEW

**Comment by fjy** [comment]
java.lang.RuntimeException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /druid
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1073)
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:274)
	at org.apache.curator.utils.EnsurePath$InitialHelper$1.call(EnsurePath.java:156)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.utils.EnsurePath$InitialHelper.ensure(EnsurePath.java:148)
	at org.apache.curator.utils.EnsurePath.ensure(EnsurePath.java:102)
	at io.druid.server.coordination.ZkCoordinator.start(ZkCoordinator.java:129)
	at io.druid.server.coordination.ZkCoordinatorTest.testInjector(ZkCoordinatorTest.java:547)

**Comment by erikdubbelboer** [comment]
What did you do to cause that error? We have been running with this change for over a month now.

**Comment by himanshug** [comment]
@erikdubbelboer can google cloud storage handle ':' in the path names?

**Comment by himanshug** [comment]
also, it appears that google cloud storage can be used via native hdfs filesystem implementation?

**Comment by erikdubbelboer** [comment]
@himanshug yes it handles ':' in path names normally. To use google cloud storage with hadoop you need the gs:// paths. Otherwise it will just store the files in the normal hdfs filesystem. As far as I know it's not possible to tell hadoop to store hdfs:// files in google cloud storage. See https://cloud.google.com/hadoop/google-cloud-storage-connector

We have been using this patch for over a month now to store our indexes in hadoop on google cloud storage.

**Comment by himanshug** [comment]
and, does google cloud storage come with an implementation of hadoop FileSystem api which you use in your hadoop jobs to read/write data in gs://path/ and use hdfs deep storage with that FileSystem impl at historicals etc to load the data?

**Comment by fjy** [comment]
@erikdubbelboer I was just noting the error so we can fix our transient unit tests. It has nothing to do with your PR, your PR is fine.

**Comment by fjy** [comment]
:+1:

**Comment by erikdubbelboer** [comment]
@himanshug Yes, as you can see on this page: https://cloud.google.com/hadoop/google-cloud-storage-connector there is a FileSystem impl for gs://bucket/path
We use https://cloud.google.com/dataproc/ which is a managed hadoop cluster from Google which preinstalles and configures the connector.
We do need to copy this connector jar to all nodes that want to use it (historical for downloading segments, others for storing task logs in google cloud storage).
The connector uses `com.google.http-client` so it's important to have #2646 merged as well.

Maybe after this is merged I can contribute some documentation on how we got druid to work with dataproc and google cloud storage.

**Comment by himanshug** [comment]
ok, cool, some docs would be good. it appears like everything else to talk to google cloud storage is already in place.

**Pull request merged**
