### PR TITLE
Reorder Before/After in JDBCExtractionNamespaceTest

### PR DESCRIPTION
**Pull request by drcrallen**
* Fixes https://github.com/druid-io/druid/issues/2120

### CODE REVIEW

**Comment by drcrallen** [comment]
new failure in java7: 

```
Running io.druid.server.audit.SQLAuditManagerTest
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by drcrallen** [comment]
failed at

```
Failed tests: 
  RemoteTaskRunnerTest.testWorkerRemoved:423 expected null, but was:<13,13,1450809261973,1450809261973,0,1,0,0,0,1,16
>
  SimpleResourceManagementStrategyTest.testProvisionAlert:242 
  Unexpected method call ServiceEmitter.emit(com.metamx.emitter.service.AlertBuilder$1@2eb27091):
    ServiceEmitter.emit(<any>): expected: 1, actual: 2
```

**Comment by fjy** [comment]
@drcrallen file issues for new test failures you encounter

**Comment by drcrallen** [comment]
@fjy New failure I saw was regression in prior version of this pr :)

**Comment by drcrallen** [comment]
```io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
testReverseFunction[[.dat]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)
```

**Comment by drcrallen** [comment]
```
CoordinatorServerViewTest.testMultipleServerAddedRemovedSegment:168->CuratorTestBase.setupZNodeForServer:83 » NodeExists
```

**Comment by drcrallen** [comment]
@fjy I haven't received this error again. I also added timeouts in the startup and tear down methods to make it more clear where it is failing.

**Comment by fjy** [comment]
:+1:

**Pull request merged**
