### PR TITLE
fix timeout check bug in DirectDruidClient

### PR DESCRIPTION
**Pull request by himanshug**
regression from #4229

### CODE REVIEW

**Comment by himanshug** [comment]
@drcrallen there are tests with mocks which did not cover this specific change. i tried that today but looks like it would need some refactoring in there to make it testable where in the response handler could be exercised. 
anyways, I have now tested it on our integration testing environment and its working.

**Comment by pjain1** [comment]
@himanshug are you trying to add unit test or is this mergeable ?

**Comment by drcrallen** [comment]
Does this solve https://github.com/druid-io/druid/issues/1415 ?

**Comment by himanshug** [comment]
@drcrallen this (and #4229 ) solve #1415 partially , timeout handling probably needs to be handled in many different places to fully solve #1415 . this should solve it at broker for queries which are processed fully in streams.

@pjain1 no, not in this pr at least. this is mergeable.

**Pull request merged**
