### PR TITLE
JavaScript: Ability to disable.

### LINKED ISSUE #2852: Config to disable JavaScript
JavaScript is cool but since it runs un-sandboxed, it is a potential security risk. This is
especially important for a multi-tenant cluster where we want dataSource level security.

It does not seem trivial to sandbox Rhino (see links below), so we should provide a config
to disable it completely.

- http://codeutopia.net/blog/2009/01/02/sandboxing-rhino-in-java/
- http://stackoverflow.com/questions/4314222/how-to-configure-sandbox-security-in-in-rhino-javascript-engine
- https://github.com/cloudbees/rhino-sandbox

### PR DESCRIPTION
**Pull request by gianm**
Fixes #2852.

### CODE REVIEW

**Comment by xvrl** [comment]
@gianm is there any good reason to change the optimization level?

**Comment by gianm** [comment]
@xvrl Changing to interpreted mode (-1) for some reason? Experimentation? Working around (potentially not yet discovered) bugs in the optimizer?

**Comment by himanshug** [comment]
disable flag is good
:+1:

**Comment by nishantmonu51** [comment]
👍 , this can be merged once @xvrl comments are addressed.

**Comment by xvrl** [comment]
@gianm I wonder how much we'll want to support this Rhino specific optimization flag given that in the future most of the Rhino code should be replaced with Nashorn whenever run in JDK 8. But if people think it's useful I don't have a strong objection.

**Comment by gianm** [comment]
Ok, I'll remove it, I just did it since it was easy to add but it sounds like there is no real use case for it.

**Comment by gianm** [comment]
removed.

**Comment by fjy** [comment]
@gianm merge conflicts, can merge after that

**Comment by gianm** [comment]
@fjy fixed

**Pull request merged**
