### PR TITLE
Added info about Google Cloud Storage

### PR DESCRIPTION
**Pull request by erikdubbelboer**
See: https://github.com/druid-io/druid/pull/2645#issuecomment-196632625

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by drcrallen** [comment]
@fjy since we are going to have an RC2 for 0.9.1 can we just add this to rc2?

👍

**Comment by fjy** [comment]
@drcrallen sounds good but we should remember to backport

**Comment by fjy** [comment]
@erikdubbelboer do you mind backporting this PR to the 0.9.1 branch?

**Pull request merged**
