### PR TITLE
Checkstyle checks for AvoidStaticImport, UnusedImports.

### PR DESCRIPTION
**Pull request by gianm**
Many times I see comments like "unused import" and "avoid static imports" in PRs,
this will automate that kinds of review. I also removed the small number of those we
already had in production code.

This excludes tests from AvoidStaticImport, since those are used often there and
I didn't want to make this changeset too large.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by dclim** [comment]
👍

**Comment by gianm** [comment]
From travis on jdk7,

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project druid: Execution validate of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check: java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/CheckstyleException : Unsupported major.minor version 52.0
```

Maybe the newer checkstyle doesn't support java7, will look into that.

**Comment by gianm** [comment]
Downgraded to Checkstyle 6.19, which supports jdk7.

**Comment by leventov** [comment]
@gianm maybe activate different versions of checkstyle depending on the build jdk?

**Comment by gianm** [comment]
@leventov I don't see a really compelling reason to do that rather than just using the same version for both jdks.

**Comment by gianm** [comment]
Merging, since the only change since two 👍s was to fix the jdk7 issue.

**Pull request merged**
