### PR TITLE
Add PMD and prohibit unnecessary fully qualified class names in code

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by jihoonson** [comment]
Looks good to me!

**Comment by leventov** [comment]
@jihoonson could you please merge this PR?

**Comment by leventov** [comment]
@jihoonson could you please merge this PR?

**Comment by jihoonson** [comment]
@leventov sorry, i forgot. Merged now.

**Comment by leventov** [comment]
@jihoonson thanks

**Pull request merged**
