### PR TITLE
Add hashCode and equals to DruidNode

### PR DESCRIPTION
**Pull request by drcrallen**

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by fjy** [comment]
Why does DruidNode need this?

**Comment by drcrallen** [comment]
@fjy I have some unit tests in other PRs that use the equals method of DruidNode. namely Objects.equals(X, Y) where X and Y contain DruidNode fields.

**Comment by drcrallen** [comment]
And the IntelliJ generated equals function just checks the equals methods of the fields.

**Comment by xvrl** [comment]
:+1:

**Pull request merged**
