### PR TITLE
fixed createIndex

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**
a row was lost every time the index size was exceeded

### CODE REVIEW

**Comment by drcrallen** [comment]
Hi @AlexanderSaydakov! Thanks for the contrib. Can you elaborate more on which tests this was causing issues in?

**Comment by AlexanderSaydakov** [comment]
This is a test code. I used it in my tests and discovered this issue.

**Comment by drcrallen** [comment]
Cool. Would you mind filling out the CLA? http://druid.io/community/cla.html
We should be able to get this merged pretty fast (assuming automated testing passes)

**Comment by cheddar** [comment]
:+1:

Alex will be covered under the Yahoo Corporate CLA.  I'll get a copy sent with his name on it.

**Comment by drcrallen** [comment]
ok cool
:+1: after travis

**Pull request merged**
