### PR TITLE
[WIP] Make timeouts more explicit on what is failing in JDBCExtractionNamespaceTest

### PR DESCRIPTION
**Pull request by drcrallen**
Will be closing/opening to try and encounter errors

### CODE REVIEW

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
Success.

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
Success... I can't tell if that is bad or good.

**Comment by drcrallen** [comment]
Success

**Comment by drcrallen** [comment]
success

**Comment by drcrallen** [comment]
Success.

Looks like all I have to do for this error not to show up is for ME to submit the PRs.

**Comment by drcrallen** [comment]
Success

**Comment by fjy** [comment]
@drcrallen I suspect it'll be a pain to make the JDBC namespace test fail as well. We can merge this and hope more useful info comes out when it fails.

**Comment by drcrallen** [comment]
@fjy ok, no failures. Suggest merging and hopefully the answer will present itself.

**Comment by fjy** [comment]
@drcrallen Okay, will do

**Pull request merged**
