### PR TITLE
add section: "What to Do When You Have a Firewall"

### PR DESCRIPTION
**Pull request by solimant**
Added the section to tell users what to do when trying the first tutorial from behind a firewall.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
+1

**Comment by solimant** [comment]
Thank you!

**Comment by fjy** [comment]
@solimant do you mind signing the CLA: druid.io/community/cla.html
and we can merge this

**Comment by solimant** [comment]
@fjy I thought the CLA was for code contributions. I am only contributing to the documentation.

**Comment by fjy** [comment]
@solimant we had a discussion awhile ago and decided that CLAs for everything in the druid repo. Do you have a concern with the CLA? If so, we can discuss about it

**Comment by solimant** [comment]
Not at all, I just wasn't aware. Anyways, I've signed the CLA.

**Comment by fjy** [comment]
@solimant Thanks for the contrib!

**Comment by solimant** [comment]
@fjy My pleasure. Thank you for the support. I was wondering, when would this be published on druid.io?

**Pull request merged**
