### PR TITLE
[Backport] Fix metrics for inserting segments

### PR DESCRIPTION
**Pull request by jihoonson**
Backport of #5749 to 0.12.1.

---
This change is [Reviewable](https://reviewable.io/reviews/druid-io/druid/5759)

### CODE REVIEW

**Comment by gianm** [comment]
@jihoonson the Travis error seems related,

```
[ERROR] /home/travis/build/druid-io/druid/indexing-service/src/main/java/io/druid/indexing/common/actions/SegmentTransactionalInsertAction.java:132: '.' has incorrect indentation level 6, expected level should be 8. [Indentation]
[ERROR] /home/travis/build/druid-io/druid/indexing-service/src/main/java/io/druid/indexing/common/actions/SegmentTransactionalInsertAction.java:133: '.' has incorrect indentation level 6, expected level should be 8. [Indentation]
Audit done.
```

**Comment by jihoonson** [comment]
@gianm thanks. Fixed.

**Comment by jihoonson** [comment]
I don't think the TeamCity failure is related to this change. Would anyone restart it?

**Comment by gianm** [comment]
@jihoonson I restarted it

**Pull request merged**
