### PR TITLE
fixing regressions

### PR DESCRIPTION
**Pull request by himanshug**
from #2138 and #2295

### CODE REVIEW

**Comment by rasahner** [comment]
+1  after checks
(but I'm curious as to why you chose not to divide the test code into two separate tests.)

**Comment by himanshug** [comment]
@rasahner purely because all of if was related and still kept test simple.

**Comment by guobingkun** [comment]
#2138 is a pretty big PR, is it fully backward compatible?

**Comment by fjy** [comment]
:+1:

**Pull request merged**
