### PR TITLE
Added link to Gitter chat

### PR DESCRIPTION
**Pull request by pdeva**

### CODE REVIEW

**Comment by drcrallen** [comment]
Hi @pdeva If Gitter is to be officially adopted as a communications means has not been discussed overall yet (as per https://github.com/druid-io/druid/pull/1767 )

Here are a few key concerns I have:

1. How does it relate to IRC as far as our intended use?
1. Are both intended to be used (please no)?
1. If we only keep one, is Gitter the choice?
1. Gitter needs access to private github repositories. This is a problem for some organizations (and something I personally really don't want to give out to a service). Can connectivity with Gitter be accomplished without having people give up access to their private repositories?
1. Is there still an appropriate means of communication available to people who either do not or cannot have Github accounts?

**Comment by pdeva** [comment]
my big reason to use it is
- msg history is kept even if i close the window
- way better formatting
- *not* 20 years old

**Comment by gianm** [comment]
Closing as there was not consensus around switching from IRC to Gitter.

**Comment by vogievetsky** [comment]
For any one looking for a chat room, Druid now has its channel as part of the ASF slack: https://druid.apache.org/community/join-slack

**Pull request closed without merging**
