### PR TITLE
[Backport] Use Double.NEGATIVE_INFINITY and Double.POSITIVE_INFINITY 

### PR DESCRIPTION
**Pull request by gianm**
Backport of #4496 to 0.10.1.

### CODE REVIEW

**Comment by jon-wei** [comment]
Anyone know what the failure with the TeamCity inspection is? I don't think I have login access to that..

**Comment by gianm** [comment]
It looked spurious to me (didn't see any new errors) so I tried bouncing the teamcity job.

**Comment by leventov** [comment]
@jon-wei you have to click "Log in as guest" that will just redirect inside without any extra steps. It's silly that it's not done automatically.

**Comment by jon-wei** [comment]
@leventov cool, thanks for the info!

**Pull request merged**
