### PR TITLE
Explicitly set code coverage maven plugin versions (DO NOT MERGE, STRESS TESTING TRAVIS)

### LINKED ISSUE #3067: Stalls after running QueryGranularityTest
See https://github.com/druid-io/druid/pull/3060#issuecomment-223440871 and https://github.com/druid-io/druid/pull/3062#issuecomment-223473989

These stalls seem to be after QueryGranularityTest runs but before the next one runs? Also both were on java7. @jon-wei said he saw the same thing on a third PR, also java 7. Maybe related to `testDeadLock` and java 7 doesn't like having a thousand classloaders get made?

### PR DESCRIPTION
**Pull request by drcrallen**
Fixes #3067 

The test mentioned in the issue still "fails", but coverage tests continue locally.

### CODE REVIEW

**Comment by fjy** [comment]
@drcrallen can we stress test travis after 0.9.1 release is done? travis is really blocked right now

**Comment by drcrallen** [comment]
@fjy that's fine. I'll not re-test until at least 0.9.1-rc2 is cut

**Comment by drcrallen** [comment]
still passing, this is good

**Comment by drcrallen** [comment]
still passing

**Comment by drcrallen** [comment]
Darn it! https://travis-ci.org/druid-io/druid/jobs/136238960  .... oh well

**Pull request closed without merging**
