### PR TITLE
update druid console version to 0.0.3

### PR DESCRIPTION
**Pull request by xvrl**
minor fixes

### CODE REVIEW

**Comment by gianm** [comment]
@xvrl what's fixed? are they needed for 0.9.1?

**Comment by nishantmonu51** [comment]
👍

**Comment by fjy** [comment]
can we move this to 0.9.2?

**Comment by xvrl** [comment]
@fjy we've deployed and tested the changes on our end in production.

**Comment by gianm** [comment]
👍 

I'm OK with 0.9.1 if you can do a backport @xvrl

**Pull request merged**
