### PR TITLE
Remove types from TimeAndDims, they aren't needed.

### PR DESCRIPTION
**Pull request by gianm**

### CODE REVIEW

**Comment by navis** [comment]
I think @jon-wei has a plan for that.

**Comment by gianm** [comment]
I was thinking the types are still known and available through `dimensionDescs`, so it should not be necessary to put them in the TimeAndDims too.

**Comment by himanshug** [comment]
it depends on what is the eventual plan , can same dimension column have different type while data is ingested (say user was using dimension-less ingestion and hadn't specified any type in the beginning)... now what should be the final type of that dimension column given that we see some events with type float, some with long, some with string etc.

FWIW, i think it is good to not have it in TimeAndDims and have concept of fixing the dimension column type somehow.

**Comment by gianm** [comment]
@jon-wei any thoughts – do you think this patch makes sense given #2760 or not? If it doesn't make sense feel free to close this PR.

**Comment by jon-wei** [comment]
@gianm From our discussion yesterday, I think it makes sense to get rid of types and reference DimensionDesc list instead

**Comment by fjy** [comment]
@gianm @jon-wei keep this PR?

**Comment by jon-wei** [comment]
@fjy let's keep this

**Comment by fjy** [comment]
👍

**Pull request merged**
