### PR TITLE
Fix broken GenericRecord.Arrays in avro parsing

### PR DESCRIPTION
**Pull request by Igosuki**
Not only avro files coming from pig avro storage use generic avro arrays but any avro records coming into the parser as well.
This has fixed having byteArrays in segments instead of actual values for us.

### CODE REVIEW

**Comment by Igosuki** [comment]
I only found this out because we are using arrays in avro payloads serialized by tranquility through the Avro druid-avro-extensions.

**Comment by gianm** [comment]
@Igosuki could you add a test please?

**Comment by Igosuki** [comment]
I can't reproduce it on the druid api side alone, MapBasedRow should take care of transforming list values to strings, however when embedded with Tranquility (druid 0.9.2, but the avrostreamparser code was written before that release ?) it produces byte array representation of avro.Utf8 instead of java.lang.String. 
I have to create integration tests on tranquility to reproduce it.

**Comment by leventov** [comment]
@gianm I'm fine to merge this without a test

**Comment by jon-wei** [comment]
@Igosuki  @gianm  This was only merged into 0.11.0, is this relevant for master/0.12.0?

**Comment by gianm** [comment]
That's a good question, I'm sorry to report that I didn't even notice it was not a PR for master.

**Comment by zhaown** [comment]
@Igosuki I think it should work if you set `fromPigAvroStorage` to false which is default, how did you get hit by this issue?

**Comment by Igosuki** [comment]
@zhaown The content of a GenericData.Array may not be a GenericRecord but
just avro.Utf8 for instance. Furthermore, that is true all the time for
avro generated code (I used 1.8.1 and 1.8.2) so fromPigAvroStorage became a
useless clause.
Specifically, this occurred when when deserializing Avro binary data
serialized as specific records, sent over to the http firehose by
tranquility.

**Comment by zhaown** [comment]
@Igosuki , as you said, when set fromPigAvroStorage  to false, MapBasedRow should take care of transforming list values of Utf8 to strings, I'm using Druid 0.10 and the Hadoop batch job works fine in extracting strings in avro array, though I'm not using Tranquility. The `MapBasedRow` produced by `AvroHadoopInputRowParser` should be the same as produced by `AvroStreamInputRowParser`, how the `MapBasedRow` produce byte array representation of avro.Utf8 in Tranquility?

**Pull request merged**
