### PR TITLE
Replace guava Charsets with native java StandardCharsets

### LINKED ISSUE #4872: Use StandardCharsets instead of Charsets.
Charsets should be added to forbidden-apis.

### PR DESCRIPTION
**Pull request by yuppie-flu**
Closes #4872
com.google.common.base.Charsets was added to forbidden-apis also

### CODE REVIEW

**Comment by yuppie-flu** [comment]
Integration tests failed twice for some unclear reasons. For sure, it's not related with changes.
I'll try to rerun build later...

**Comment by b-slim** [comment]
@yuppie-flu could you please fill CLA http://druid.io/community/cla.html ?

**Comment by jihoonson** [comment]
@b-slim he has already done.

BTW, is this refactoring?

**Comment by jihoonson** [comment]
I have no opinion, but was just curious which types of PRs are refactoring. 
I'm merging this PR.

**Pull request merged**
