### PR TITLE
upgrade skeches-core to version 0.8.3

### PR DESCRIPTION
**Pull request by himanshug**

### CODE REVIEW

**Comment by gianm** [comment]
- jdk8 test failure looks transient (AnnouncerTest)
- jdk7 test failure looks legit, sketches-core is no longer built for jdk7: `java.lang.UnsupportedClassVersionError: com/yahoo/memory/Memory : Unsupported major.minor version 52.0`

**Comment by drcrallen** [comment]
Can probably add data-sketches to the build method used for the caffeine cache extension.

**Comment by drcrallen** [comment]
buuut, would be worth calling out in the java8 thread in the dev list

**Comment by himanshug** [comment]
@gianm @drcrallen I forgot the java8 catch, I guess ...for now I would let datasketches work with java-7 and not upgrade sketches-core unless necessary.

**Comment by gianm** [comment]
Datasketches previously supported jdk7 so imo it should continue to do so until Druid itself moves on.

**Pull request closed without merging**
