### PR TITLE
remove convertProperties

### PR DESCRIPTION
**Pull request by nishantmonu51**
fixes https://github.com/druid-io/druid/issues/2335

### CODE REVIEW

**Comment by nishantmonu51** [comment]
@himanshug @fjy : can you have a look ?

**Comment by nishantmonu51** [comment]
Added Release Notes label to note that we removed the convertProperties in 0.9

**Comment by fjy** [comment]
:+1:

**Comment by himanshug** [comment]
@nishantmonu51 is this mentioned somewhere in the documentation? then we might need to remove there as well.

**Comment by gianm** [comment]
I don't see any mention of "convertProps" in the docs, so :+1:

**Comment by nishantmonu51** [comment]
@himanshug: did a quick search in docs, could not find it mentioned in docs.

**Pull request merged**
