### PR TITLE
Enable GenericIndexed V2 for built-in(druid-io managed) complex columns.

### PR DESCRIPTION
**Pull request by akashdw**
This PR is to enable GenericIndexed V2 for complex columns.

### CODE REVIEW

**Comment by gianm** [comment]
This seems like something that should be 0.10.0 to complete the "large columns" stuff… @akashdw should we add it to the milestone?

**Comment by akashdw** [comment]
@gianm Yes, we need this to complete the large column stuff. I was going through the release notes and realized its disabled by default including druid managed complex metrics. I left a note in release notes on how to enable it. https://github.com/druid-io/druid/issues/3944#issuecomment-283220177

**Comment by gianm** [comment]
Okay cool, I added this to the milestone.

**Comment by fjy** [comment]
👍

**Pull request merged**
