### PR TITLE
remove confusing docs on setting up clusters

### PR DESCRIPTION
**Pull request by fjy**
- from multiple discussions with the community, the example production cluster docs are extremely confusing to readers 
- no one sets up a cluster that looks like the production cluster described
- much of this info is redundant now with http://druid.io/docs/0.9.0/tutorials/cluster.html

### CODE REVIEW

**Comment by gianm** [comment]
👍 

agree these are a bit confusing, the druid configs are kind of out of date and I think the hadoop configs have a bunch of stuff in them that was never really relevant to druid. we also have cluster-ready configs in the tarball now https://github.com/druid-io/druid/tree/master/examples/conf

**Comment by drcrallen** [comment]
I'm torn on this in a few ways:

1. Imply and MMX both benefit from not having suggested configurations in the wild (this is an argument for having another party comment on this)
1. Best config values vary GREATLY depending on actual production workload. 
1. The configurations are pretty out dated (m1.large, wat?)
1. We should strive as a community to make default configs pretty good for most use cases, especially just starting up use cases.
1. The configs are explained better and in more detail elsewhere in the docs.
1. I have no interest in maintaining these configs as time goes on.
1.  If we need to have example config files or suggested templates, I think in the quickstart is a better place to host them.

So in general I'm 👍  but have a conflict of interest here so would like to hear if these docs to be removed are useful for anyone in the community before zapping them completely.

**Comment by gianm** [comment]
I actually have no problem with having a good starting point for production configs out there. I don't think Imply stands to gain anything from having suboptimal defaults – if anything we really want people to have a great experience benchmarking Druid out of the box.

I agree with your (2), (3), (4), (5), (6), and (7) though @drcrallen :)

Personally I think it's best to focus on,

- https://github.com/druid-io/druid/tree/master/examples/conf-quickstart as a good set of defaults for a single-machine setup,
- https://github.com/druid-io/druid/tree/master/examples/conf as a good set of defaults for a cluster,
- and the reference docs explain all the other options for people that want to really get into it.

**Comment by himanshug** [comment]
:+1:
I agree with @gianm here regarding focusing on quick start and make it such that extending that into production configuration is  a matter of updating key config values.

as far as suggested configuration is concerned, my experience is that there is no single good answer there... it greatly depends upon the use case, batch/realtime ingestion time , ingestion and query load.  we have various clusters with fairly different production configuration.

**Pull request merged**
