### PR TITLE
Add fallback to groupBy strategy V1 in GroupByStrategySelector if no merge buffers are configured

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by gianm** [comment]
I don't think it should be automatic. In 0.10.0 merge buffers are available by default on all node types unless you explicitly disable them. And if you explicitly disable them, then you can explicitly switch to groupBy v1 through `druid.query.groupBy.defaultStrategy`. At any rate, I think we should get rid of groupBy v1 at some point, so this patch goes in the "wrong" direction.

**Comment by leventov** [comment]
@gianm we cannot get rid of groupBy strategy V1, because we are very short on memory and had to set numMergeBuffers=0, because groupBy queries are very unimportant on our nodes. OTOH, we don't want to make groupBy queries impossible completely.

The message in the PR could say "please set up defaultStrategy=v1", but note that a query with explicit v2 configuration may come also. I think it's better to process such queries somehow than fail altogether.

**Comment by gianm** [comment]
> @gianm we cannot get rid of groupBy strategy V1, because we are very short on memory and had to set numMergeBuffers=0, because groupBy queries are very unimportant on our nodes. OTOH, we don't want to make groupBy queries impossible completely.

That's valid, in this case it makes sense to set `druid.query.groupBy.defaultStrategy=v1`. Alternatively it could also make sense to add a new config to size merge buffers, so you can create 1 merge buffer and have it be smaller than your processing buffers, minimizing the amount of memory reserved for it.

> The message in the PR could say "please set up defaultStrategy=v1", but note that a query with explicit v2 configuration may come also. I think it's better to process such queries somehow than fail altogether.

On the other hand, it seems weird to me to ignore what the user asked for in their query. If a user asks for v2 but v2 is not available, I think it's best to tell them that (in the form of an error) rather than silently use v1 instead. That's because the user is not always the same as the cluster operator, and the user deserves to know that what they asked for is not possible, even if they don't have access to cluster logs.

At any rate, I expect that queries that ask for a specific groupBy strategy will be uncommon anyway, outside of benchmarking or testing situations. So I expect that the impact of returning errors there is low in production, and it's a good thing for testing, since it lets users confirm they are actually using what they think they're using.

Finally, separate from the above points: I'm not totally sure this patch will work properly as-is, since IIRC groupBy v2 on the broker assumes results from historicals are sorted, but groupBy v1 on historicals does not sort results. So the patch may cause results to not be merged properly. But I haven't reviewed this closely to determine if this is really the case or not.

**Comment by gianm** [comment]
Regardless of whether we decide to apply this patch or not, I don't think it needs to be considered a blocker in 0.10.1, since the described issue exists in 0.10.0 as well and there is a good workaround (set defaultStrategy). So I would consider it for 0.11 if we are going to do it.

**Pull request closed without merging**
