### PR TITLE
HdfsDataSegmentPusher bug fix

### PR DESCRIPTION
**Pull request by akashdw**
Fixes https://github.com/druid-io/druid/issues/3997
Hdfs namespace optimization changes #3877 introduced a bug in HdfsDataSegmentPusher causing exceptions during segment push (if an interval has more than one shard.)

### CODE REVIEW

**Comment by himanshug** [comment]
:+1:

**Comment by gianm** [comment]
Taking a look now. @akashdw have you tried this on a live cluster to confirm the fix?

**Comment by akashdw** [comment]
@gianm  tested puller pusher and it worked, but found a small correction to be made. Uploading a new patch.

**Comment by himanshug** [comment]
@akashdw  what is the "small correction" ?

**Comment by akashdw** [comment]
Written descriptor file in hdfs is missing load spec https://github.com/druid-io/druid/pull/4003/files#diff-43eb9286d827e862f82f83f06e495fe1R137. Adding a test to actually read the value of descriptor file instead of only relying on returned DataSegment object after the push.

**Comment by himanshug** [comment]
thanks for testing and catching that. :+1:

**Comment by gianm** [comment]
@akashdw is the PR updated with the new patch? If so I'll take a look

**Comment by akashdw** [comment]
@gianm I tested out the puller/pusher with the last version and both worked. Found load spec is missing while doing manual validation of descriptor file stored in hdfs. 
Sorry for missing out that check and creating this PR without validating actual content of the file.

**Pull request merged**
