### PR TITLE
[Don't merge]Another effort on fixing the transient error for XXXServerViewTest

### LINKED ISSUE #2128: Non-deterministic io.druid.client.CoordinatorServerViewTest
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.822 sec <<< FAILURE! - in io.druid.client.CoordinatorServerViewTest
testMultipleServerAddedRemovedSegment(io.druid.client.CoordinatorServerViewTest)  Time elapsed: 1.158 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /druid/segments/locahost:0
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:727)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:703)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:699)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:477)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:467)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:447)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:355)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:291)
	at io.druid.client.CoordinatorServerViewTest.setupZNodeForServer(CoordinatorServerViewTest.java:363)
	at io.druid.client.CoordinatorServerViewTest.testMultipleServerAddedRemovedSegment(CoordinatorServerViewTest.java:171)

### PR DESCRIPTION
**Pull request by guobingkun**
Will trigger the build about 30 times to see if there is no transient error on travis build.
Try to fix #2128

### CODE REVIEW

**Comment by navis** [comment]
Can see 3 kind of failures.
```
io.druid.indexing.overlord.RemoteTaskRunnerTest
testWorkerRemoved(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 3.97 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testWorkerRemoved(RemoteTaskRunnerTest.java:411)
```

```
io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[tsColumn](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 4.331 sec  <<< FAILURE!
org.junit.ComparisonFailure: update check expected:<ba[z]> but was:<ba[r]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.assertUpdated(JDBCExtractionNamespaceTest.java:347)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.testFindNew(JDBCExtractionNamespaceTest.java:288)
```

```
io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
testReverseFunction[[.dat]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.105 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)
```

**Comment by navis** [comment]
```
io.druid.indexing.overlord.TaskLifecycleTest
testRealtimeIndexTaskFailure[taskStorageType=MetadataTaskStorage](io.druid.indexing.overlord.TaskLifecycleTest)  Time elapsed: 4.878 sec  <<< ERROR!
java.lang.Exception: test timed out after 4000 milliseconds
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1259)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:709)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:337)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2247)
	at io.druid.metadata.SQLMetadataStorageActionHandler$4.withHandle(SQLMetadataStorageActionHandler.java:195)
	at io.druid.metadata.SQLMetadataStorageActionHandler$4.withHandle(SQLMetadataStorageActionHandler.java:184)
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281)
	at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:110)
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:38)
	at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:115)
	at io.druid.metadata.SQLMetadataStorageActionHandler.getStatus(SQLMetadataStorageActionHandler.java:182)
	at io.druid.indexing.overlord.MetadataTaskStorage.getStatus(MetadataTaskStorage.java:178)
	at io.druid.indexing.overlord.TaskStorageQueryAdapter.getStatus(TaskStorageQueryAdapter.java:64)
	at io.druid.indexing.overlord.TaskLifecycleTest.testRealtimeIndexTaskFailure(TaskLifecycleTest.java:940)
```

```
io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest
testReverseFunction[[.gz]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)
```

```
io.druid.indexing.common.task.RealtimeIndexTaskTest
testBasics(io.druid.indexing.common.task.RealtimeIndexTaskTest)  Time elapsed: 12.411 sec  <<< ERROR!
java.lang.Exception: test timed out after 10000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at io.druid.indexing.common.task.RealtimeIndexTaskTest.testBasics(RealtimeIndexTaskTest.java:207)
```

```
io.druid.server.coordinator.DruidCoordinatorTest
testCoordinatorRun(io.druid.server.coordinator.DruidCoordinatorTest)  Time elapsed: 2.486 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at io.druid.server.coordinator.DruidCoordinatorTest.testCoordinatorRun(DruidCoordinatorTest.java:355)
```

```
io.druid.indexing.worker.WorkerTaskMonitorTest
testRunTask(io.druid.indexing.worker.WorkerTaskMonitorTest)  Time elapsed: 12.166 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.druid.indexing.worker.WorkerTaskMonitorTest.testRunTask(WorkerTaskMonitorTest.java:200)
```

```
io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[tsColumn](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 4.362 sec  <<< FAILURE!
org.junit.ComparisonFailure: update check expected:<ba[z]> but was:<ba[r]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.assertUpdated(JDBCExtractionNamespaceTest.java:347)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.testFindNew(JDBCExtractionNamespaceTest.java:288)
```

**Comment by fjy** [comment]
@guobingkun I think we can merge this now. Issues need to be filed for the rest of the test failures.

**Comment by drcrallen** [comment]
yeah... a squash would have been nice

**Pull request merged**
