### PR TITLE
Add nicer locking and shorter timeouts to JDBCExtractionNamespaceTest

### PR DESCRIPTION
**Pull request by drcrallen**
Fixes https://github.com/druid-io/druid/issues/2120

### CODE REVIEW

**Comment by drcrallen** [comment]
Unrelated failures
` CoordinatorServerViewTest.testSingleServerAddedRemovedSegment:103->setupZNodeForServer:363 » NodeExists` and ```testReverseFunction[[.dat]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.107 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)```

**Comment by drcrallen** [comment]
```
testSimpleRename(io.druid.query.extraction.namespace.TestKafkaExtractionCluster)  Time elapsed: 0.087 sec  <<< FAILURE!
java.lang.AssertionError: expected:<bar> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.query.extraction.namespace.TestKafkaExtractionCluster.testSimpleRename(TestKafkaExtractionCluster.java:352)
```

Other failure

**Comment by drcrallen** [comment]
```
testReverseFunction[[.dat]:[io.druid.server.namespace.cache.OffHeapNamespaceExtractionCacheManager]](io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest)  Time elapsed: 0.136 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:621)
	at org.junit.Assert.assertNotNull(Assert.java:631)
	at io.druid.server.namespace.URIExtractionNamespaceFunctionFactoryTest.testReverseFunction(URIExtractionNamespaceFunctionFactoryTest.java:325)
```

unrelated and known test failure

**Comment by drcrallen** [comment]
`DruidCoordinatorTest.testCoordinatorRun:296 »  test timed out after 1500 milli...`

**Comment by drcrallen** [comment]
odd failure that time:
```
testRunExistingTaskThatHasStartedRunning(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 5.148 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testRunExistingTaskThatHasStartedRunning(RemoteTaskRunnerTest.java:171)
testWorkerRemoved(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 5.815 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testWorkerRemoved(RemoteTaskRunnerTest.java:411)
Running io.druid.indexing.overlord.ForkingTaskRunnerTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in io.druid.indexing.overlord.ForkingTaskRunnerTest
Running io.druid.indexing.overlord.TaskLifecycleTest
Tests run: 24, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.897 sec <<< FAILURE! - in io.druid.indexing.overlord.TaskLifecycleTest
testRealtimeIndexTask[taskStorageType=HeapMemoryTaskStorage](io.druid.indexing.overlord.TaskLifecycleTest)  Time elapsed: 2.325 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.druid.indexing.overlord.TaskLifecycleTest.testRealtimeIndexTask(TaskLifecycleTest.java:883)
```

**Comment by drcrallen** [comment]
@fjy this passes. I didn't see the error it aims to fix in ANY of the above travis runs.

**Comment by fjy** [comment]
@drcrallen sounds good, will merge :+1:

**Pull request merged**
