### PR TITLE
Enable "fromNext" by default from druid-0.10.0

### PR DESCRIPTION
**Pull request by navis**
Based on #2576. As discussed in https://github.com/druid-io/druid/pull/2576#discussion_r57653173, enable "fromNext" by default from druid-0.10.0.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by fjy** [comment]
@navis can we fix merge conflicts?

**Comment by nishantmonu51** [comment]
@navis: can you fix conflicts ?

**Comment by gianm** [comment]
IMO, if we're going to change the default of fromNext, we should also make it mandatory to specify either `fromNext: false` or `fromNext: true`. This means that people that don't pass fromNext in their queries will get failures starting in 0.10.0, which I think is better than getting wrong results.

**Comment by gianm** [comment]
Hmm, actually, my comment was kind of nonsensical. There's no such thing as "changing the default" for something that's mandatory. I still think that silent wrong results on older client code is bad, but also, making fromNext mandatory is kind of silly.

I would be ok with adding a runtime property that controls the default behavior, like `druid.query.select.fromNextDefault` and have that default to "true" in 0.10.0. Then users that need to support older client code could set it to "false" to get the old Druid behavior.

The important thing, imo, is that many Druid deployers are not the same people as the ones that write the queries, and we have to recognize that dynamic when making changes like this.

@fjy @nishantmonu51 @navis what do you think?

**Comment by nishantmonu51** [comment]
@gianm: your suggestion seems good to me.

**Comment by fjy** [comment]
@gianm 👍

**Comment by jon-wei** [comment]
Closing this, discussion can continue at https://github.com/druid-io/druid/pull/3986

**Pull request closed without merging**
