### PR TITLE
Fix an error in the xml file

### PR DESCRIPTION
**Pull request by ttawi**
Deleting an extra tag

### CODE REVIEW

**Comment by fjy** [comment]
Thanks @ttawi . Do you mind filling out the CLA http://druid.io/community/cla.html

**Comment by nishantmonu51** [comment]
👍

**Comment by ttawi** [comment]
@fjy done

**Comment by gianm** [comment]
This patch was filed against 0.9.1 rather than master, so it won't actually make it into a release.

**Pull request merged**
