### PR TITLE
RemoteTaskRunner: Fix for starting an overlord before any workers ever existed.

### PR DESCRIPTION
**Pull request by gianm**
If the NoNodeException bubbles up, it'll stop the overlord's leader lifecycle from being able to start up and the overlord will not actually be able to do things.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by nishantmonu51** [comment]
a unit test for this case would be good to have.

**Comment by drcrallen** [comment]
Failed on `DruidCoordinatorTest.testCoordinatorRun:353->Object.wait:502->Object.wait:-2`

Agree with unit test

**Comment by himanshug** [comment]
LGTM, an UT if possible would be nice

**Comment by gianm** [comment]
@drcrallen @himanshug @nishantmonu51 added a test that fails in master.

**Comment by fjy** [comment]
:+1:

**Pull request merged**
