### PR TITLE
druid production architecture diagram

### PR DESCRIPTION
**Pull request by janakg**
We have added a production cluster architecture diagram based on the druid development forum discussions. Can you merge it to your docs repo. Let us know, if you need any changes

### CODE REVIEW

**Comment by xvrl** [comment]
Thanks @janakg! This is quite useful.
Is there any way you can share the source file for the diagram, so we can update it in the future?
 
A few notes based on our past experience with those types diagrams:
- Can we replace MySQL with Metadata Storage? People often get confused by that and dismiss Druid thinking it's just built on top of MySQL.
- We might also want list both Samza and Storm as the stream processor piece.

**Comment by fjy** [comment]
I'm not entirely sure what the arrows are implying. If it is implying the flow of data I think there are a few mistakes. One other way to structure the diagram is similar to what we've done in the design docs and create two diagrams, minimizing the complexity of each one.

**Comment by janakg** [comment]
@xvrl and @fjy , Thanks for your feedback. 
I have pushed the source file (SVG).

@fjy: We have started exploring druid a week back, our current knowledge is limited. Please make corresponding changes to the diagram, if we can push the final version to production cluster page, that would be helpful.

**Comment by janakg** [comment]
Hi @xvrl , I have incorporated your suggestions.
@fjy , I have made some flow changes based on the design page diagram. Let me know what you think.

Thanks

**Comment by fjy** [comment]
@janakg Sorry for the delay. A few comments:
1) There is a mixture of the query path and the flow of data in the diagram, but the flow of data is not fully illustrated. If we choose to display both, I think we should include the flow for segment handoff.
2) The handoff process consists of compacting intermediate segments and creating the final merged segment, uploading the segment to deep storage, writing and entry in the metadata store, having the coordinator pick up info about the segment, having the coordinator assign the segment to historicals via zookeeper, having historicals download the segment, having realtimes notice the segment is now served by historicals, and having realtimes drop the segment.
3) I don't think this diagram should go into example production configuration as it involves Kafka and Samza/Storm, which are not required to run Druid. I think after I rework the documentation, there will be a more mature place for this diagram.

**Comment by fjy** [comment]
@janakg Any chance to look at my comments?

**Comment by janakg** [comment]
@fjy   Sorry, last two weeks were crazy for us. 
Sure, it make sense to move it to a different page in documentation. I tried adding the suggested segment handoff flow, the diagram is becoming increasingly complex to consume. I think, we should be splitting the diagram (one for data flow & one for query flow) based on your new documentation plan.

**Comment by fjy** [comment]
@janakg Just to follow up with our in person sync up, I'd be happy to merge this once the diagram is hosted on a different page

**Comment by janakg** [comment]
@fjy   Great! 
Thanks
Ram

**Comment by fjy** [comment]
@janakg Did you get a chance to update this PR? I think creating a new doc titled "Integrating Druid with Other Technologies" under the Development section would be a good place for this image

**Comment by janakg** [comment]
@fjy Sure, I will get some time in next week, will create a new page and submit it.

**Comment by janakg** [comment]
Hey @fjy , I have pushed a new page "Integration" under Development
section, please let me know, what you think?

Thanks
Ram

On Wed, May 6, 2015 at 8:14 PM, Fangjin Yang <notifications@github.com>
wrote:

> @janakg
> <https://t.yesware.com/tl/13cb24356c503fc826a70c2179d9db70d189348d/1c7cdd04be7edeb2c53ceb04c83031d9/eb19f5dfd7ff8e3cf4856a30e2c9a595?ytl=https%3A%2F%2Fgithub.com%2Fjanakg>
> Did you get a chance to update this PR? I think creating a new doc titled
> "Integrating Druid with Other Technologies" under the Development section
> would be a good place for this image
>
> —
> Reply to this email directly or view it on GitHub
> <https://t.yesware.com/tl/13cb24356c503fc826a70c2179d9db70d189348d/1c7cdd04be7edeb2c53ceb04c83031d9/404287af81b23380bbfeacb687012ef0?ytl=https%3A%2F%2Fgithub.com%2Fdruid-io%2Fdruid%2Fpull%2F1220%23issuecomment-99696924>
> .
>



-- 
Thanks,
Ram
CEO, MineWhat, Inc
408.921.9520

**Comment by fjy** [comment]
@janakg This looks awesome! There appear to be some merge conflicts, but once those are resolved, I can merge. Have you signed the CLA already?

http://druid.io/community/cla.html

**Comment by janakg** [comment]
Thanks! @fjy, I have signed the CLA.

On Wed, May 27, 2015 at 9:59 AM, Fangjin Yang <notifications@github.com>
wrote:

> @janakg <https://github.com/janakg> This looks awesome! There appear to
> be some merge conflicts, but once those are resolved, I can merge. Have you
> signed the CLA already?
>
> http://druid.io/community/cla.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/druid-io/druid/pull/1220#issuecomment-105994726>.
>



-- 
Thanks,
Ram
CEO, MineWhat, Inc
408.921.9520

**Comment by fjy** [comment]
@janakg Cool, can you take a look at the merge conflicts? I bet they are minor and concern the TOC

**Comment by fjy** [comment]
@janakg I resolved the conflicts for you and squashed the commits. You still have credit for all contribution :)

the new PR is now at: https://github.com/druid-io/druid/pull/1396. I am closing this one

**Comment by janakg** [comment]
@fjy,
Great!
Thanks for the help.
--Ram

On Wed, May 27, 2015 at 5:08 PM, Fangjin Yang <notifications@github.com>
wrote:

> @janakg
> <https://t.yesware.com/tl/13cb24356c503fc826a70c2179d9db70d189348d/f92915aa093c6920a0346ed992715a4d/7bf6921d22b712f51787577186aa186c?ytl=https%3A%2F%2Fgithub.com%2Fjanakg>
> I resolved the conflicts for you and squashed the commits. You still have
> credit for all contribution :)
>
> the new PR is now at: #1396
> <https://t.yesware.com/tl/13cb24356c503fc826a70c2179d9db70d189348d/f92915aa093c6920a0346ed992715a4d/2a5587b285c35c5fde0cfa9d8008946a?ytl=https%3A%2F%2Fgithub.com%2Fdruid-io%2Fdruid%2Fpull%2F1396>.
> I am closing this one
>
> —
> Reply to this email directly or view it on GitHub
> <https://t.yesware.com/tl/13cb24356c503fc826a70c2179d9db70d189348d/f92915aa093c6920a0346ed992715a4d/902eb2ec6de6312da7160286ba67a5f4?ytl=https%3A%2F%2Fgithub.com%2Fdruid-io%2Fdruid%2Fpull%2F1220%23issuecomment-106116800>
> .
>



-- 
Thanks,
Ram
CEO, MineWhat, Inc
408.921.9520

**Pull request closed without merging**
