### PR TITLE
fix spurious failure of RTR concurrency test

### LINKED ISSUE #2911: RemoteTaskRunnerRunPendingTasksConcurrencyTest Transient testing issue
`io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest` can fail in the following way:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.193 sec <<< FAILURE! - in io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest
testConcurrency(io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest)  Time elapsed: 1.191 sec  <<< ERROR!
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /test/druid/indexer/tasks/worker1/task2
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:873)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:243)
	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:237)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:234)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:218)
	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:42)
	at io.druid.indexing.overlord.RemoteTaskRunnerTestUtils.mockWorkerRunningTask(RemoteTaskRunnerTestUtils.java:161)
	at io.druid.indexing.overlord.RemoteTaskRunnerRunPendingTasksConcurrencyTest.testConcurrency(RemoteTaskRunnerRunPendingTasksConcurrencyTest.java:123)
```

### PR DESCRIPTION
**Pull request by himanshug**
fixes #2911

in certain scenario when 3 tasks are pending to run, any 2 can get scheduled and this patch is taking same into account and also fixes the condition for task announcement by checking state in zookeeper.

i will run the build multiple times to be sure.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by fjy** [comment]
Running io.druid.curator.CuratorUtilsTest
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.04 sec <<< FAILURE! - in io.druid.curator.CuratorUtilsTest
testCreateIfNotExists(io.druid.curator.CuratorUtilsTest)  Time elapsed: 14.891 sec  <<< ERROR!
java.lang.Exception: test timed out after 10000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at org.apache.curator.framework.state.ConnectionStateManager.blockUntilConnected(ConnectionStateManager.java:215)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.blockUntilConnected(CuratorFrameworkImpl.java:223)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.blockUntilConnected(CuratorFrameworkImpl.java:229)
	at io.druid.curator.CuratorUtilsTest.testCreateIfNotExists(CuratorUtilsTest.java:46)

**Comment by himanshug** [comment]
https://github.com/druid-io/druid/pull/2915#issuecomment-216692904 is unrelated to this PR.

**Comment by himanshug** [comment]
ok, i think this is ready and should fix the issue.

**Pull request merged**
