### PR TITLE
Added JSON Parse Spec support to Avro Input Row Parser

### PR DESCRIPTION
**Pull request by SpotXPeterCunningham**
Added support for JSON parse spec to the Avro parser. 

Currently the Avro parser does not support nested fields and can only consume top level fields in an Avro record. This feature allows nested field support using a JSON Parse Spec. If an ingestion spec using an Avro Stream or Avro Hadoop parser contains a JSON parse spec then the extension will allow extraction of nested properties using the JSON parse spec / Flatten spec. 

The implementation is basic and is probably lacking in some areas but I've created it to allow us to get off the ground without a lot of effort for a prototype. I've not documented this feature as did not think it was worth it until seeing if it would be pulled in. If it's of use to the community then I can document it via another commit. Alternatively if there is a better way of doing this without a lot of effort or I am fundamentally doing something wrong then let me know.

Basically it works such that If the ingestion spec supplied is a JSON parse spec then at runtime a new Converter is used which essentially calls GenericRecord.toString to turn the GenericAvroRecord into JSON and passes this to the standard JSON parser to do it's dimension mapping. If any other type of parse spec is supplied then the existing implementation is used.

Some of the important bits of code.

- GenericRecordRowConverter 
```java
  public MapBasedInputRow convert(GenericRecord record)
  {
    GenericRecordAsMap genericRecordAsMap = new GenericRecordAsMap(record, fromPigAvroStorage, false);
    TimestampSpec timestampSpec = parseSpec.getTimestampSpec();
    DateTime dateTime = timestampSpec.extractTimestamp(genericRecordAsMap);
    return new MapBasedInputRow(dateTime, dimensions, genericRecordAsMap);
  }
```

- GenericRecordJSONConveter

```java
  @Override
  public MapBasedInputRow convert(GenericRecord record)
  {
    Map<String, Object> map = parser.parse(record.toString()); //note the tostring
    TimestampSpec timestampSpec = parseSpec.getTimestampSpec();
    DateTime dateTime = timestampSpec.extractTimestamp(map);
    return new MapBasedInputRow(dateTime, dimensions, map);
  }
```

- Factory method to instantiate correct converter based on spec type. 
```java
  public static GenericRecordRowConverter fromParseSpec(
      ParseSpec parseSpec,
      boolean fromPigAvroStorage,
      boolean binaryAsString
  )
  {
    return parseSpec instanceof JSONParseSpec ?
           new GenericRecordJSONRowConverter(parseSpec, fromPigAvroStorage) :
           new GenericRecordRowConverter(parseSpec, fromPigAvroStorage, binaryAsString);
  }
```
- Example Spec.
```java
 "parser": {
            "type": "avro_stream",
            "parseSpec": {
              "format": "json",
              "timestampSpec": {
                "format": "posix",
                "column": "timestamp"
              },
              "flattenSpec": {
                "useFieldDiscovery": true,
                "fields": [{
                  "type": "root",
                  "name": "timestamp"
                }, {
                  "type": "path",
                  "name": "markers_forecasting_projected_impression",
                  "expr": "$.markers.forecasting.projected_impression"
                }, {
                  "type": "path",
                  "name": "targeting_geo_country",
                  "expr": "$.targets.geo.country"
...
```

### CODE REVIEW

**Comment by gianm** [comment]
@SpotXPeterCunningham I'm really sorry, I didn't notice your patch here before writing #4832, which is in master now. Would that new functionality work for you?

Sorry again for not noticing this, it would have probably made my life easier that day!

**Comment by SpotXPeterCunningham** [comment]
Hi Gian,

It's no problem at all. I have been off work for a month as was in an
accident. Stuff got put on hold so never chased the change and I'm not
surprised it fell by the wayside.

I am pretty new to the Druid codebase so the change i made was probs not
the most sensible way to do things anyway but was enough to get us going in
the direction we needed at the time without too much change. I just took
the whole JsonParser and reused that as it was just the first thing that
made sense to me with my limited understanding of the code base.

I've not actually looked at your patch yet as am on a mobile phone right
now with no access to a computer. I return to work on Thursday and will
check it out then and hopefully it works for us. If not we can sort
something out.

Thanks
Peter


On 10 Oct 2017 6:00 p.m., "Gian Merlino" <notifications@github.com> wrote:

@SpotXPeterCunningham <https://github.com/spotxpetercunningham> I'm really
sorry, I didn't notice your patch here before writing #4832
<https://github.com/druid-io/druid/pull/4832>, which is in master now.
Would that new functionality work for you?

Sorry again for not noticing this, it would have probably made my life
easier that day!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/druid-io/druid/pull/4749#issuecomment-335540524>, or mute
the thread

**Comment by gianm** [comment]
Oh gosh, I hope you're ok!

Let us know if you've got any questions when you get back…

**Comment by SpotXPeterCunningham** [comment]
Hi Gianm,

 Closing this pull request as your version works for us and has much better performance. Thanks.

Thanks again,
Peter

**Pull request closed without merging**
