### PR TITLE
Fix NPE in TopNLexicographicResultBuilder.addEntry()

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes an NPE introduced in https://github.com/druid-io/druid/pull/2607

### CODE REVIEW

**Comment by drcrallen** [comment]
@jon-wei can you add a test for this?

**Comment by jon-wei** [comment]
@drcrallen this came up in a running system, still trying to find out how to trigger it via test

**Comment by jon-wei** [comment]
@drcrallen added test

**Comment by fjy** [comment]
👍

**Comment by drcrallen** [comment]
:+1:

**Comment by gianm** [comment]
👍

**Pull request merged**
