### PR TITLE
Timeout and maxScatterGatherBytes handling for queries run by Druid SQL

### PR DESCRIPTION
**Pull request by jon-wei**
This PR sets timeout and maxScatterGatherBytes parameters (https://github.com/druid-io/druid/pull/4229) in the query context/responseContext for SQL-originated queries.

Without this, SQL queries fail with a NullPointerException at this line in DirectDruidClient.run():
```
      long timeoutAt = ((Long) context.get(QUERY_FAIL_TIME)).longValue();
```

### CODE REVIEW

**Comment by jon-wei** [comment]
@gianm Addressed your comments

**Comment by gianm** [comment]
@jon-wei, compilation issue:

```
/home/travis/build/druid-io/druid/sql/src/main/java/io/druid/sql/calcite/schema/DruidSchema.java:317: error: cannot find symbol
                                                            QueryMaker.makeResponseContextForQuery(segmentMetadataQuery)
                                                                      ^
```

**Comment by jon-wei** [comment]
@gianm my bad, fixed

**Comment by gianm** [comment]
@jon-wei thanks; it looks like there's a different error now, from checkstyle.

**Pull request merged**
