### PR TITLE
Revert "[maven-release-plugin] prepare for next development iteration"

### PR DESCRIPTION
**Pull request by akashdw**
This reverts commit 1f5617a0cf02a792efede0cae1b7094358f8a916.

The pom in branch 0.10.1 is wrongly tagged as 0.11.0-SNAPSHOT, this PR fixes it.

@himanshug

### CODE REVIEW

**Comment by himanshug** [comment]
:+1:

**Comment by akashdw** [comment]
Thanks @gianm, will change the version to 0.10.1-SNAPSHOT. I also found 0.9.1 tag is not pointing to latest commit of 0.9.1 branch. https://github.com/druid-io/druid/commit/04f6b2279899967ccb7d75b4967fc0f51910961b is missing in 0.9.1 tag.

**Comment by jihoonson** [comment]
@akashdw would you merge the master branch? It looks that the broken CI relates to https://github.com/druid-io/druid/pull/4755.

**Comment by gianm** [comment]
master shouldn't be merged into the 0.10.1 branch, but the CI-fixing commits could be cherry-picked.

**Comment by jihoonson** [comment]
@gianm ah sure.

**Pull request closed without merging**
