### PR TITLE
Finalize fields in postaggs

### PR DESCRIPTION
**Pull request by gianm**
Fixed some conflicts from #2883, otherwise it's unchanged. Thanks @jaehc for the original patch.

### CODE REVIEW

**Comment by gianm** [comment]
I'm not sure if my +1 still counts, but I didn't change that much so maybe it does :)

Anyway I'm (obviously) still +1 on this.

**Comment by nishantmonu51** [comment]
👍

**Comment by gianm** [comment]
Ugh, some bad code got into master somehow and is fouling up the tests for this. Will look into that.

**Comment by gianm** [comment]
#3958 will fix the bad code in master, appears to be a "test conflict" between #3950 and #3953.

**Comment by fjy** [comment]
👍

**Comment by gianm** [comment]
thx @fjy and @nishantmonu51 for review

**Pull request merged**
