### PR TITLE
Forwards compatibility in S3 Indexer for new ingestion schema

### PR DESCRIPTION
**Pull request by nicktate**
Removed null check precondition to enable compatibility with new ingestion format.

### CODE REVIEW

**Comment by drcrallen** [comment]
Hello @nicktate . Thanks for the PR!  Can you please explain a little more on the issue you were encountering?

**Comment by nicktate** [comment]
@drcrallen The new ingestion schema moves the parser underneath `ioConfig`. The S3 firehose expected the parser to be defined inside it (per the old schema), but the new schema follows more of a true "factory" pattern. The parser should no longer be tightly coupled do the firehose, but it had left a null precondition check that caused the index task to fail if you didn't leave the parser inside the firehose definition. I left the parser property for backwards compatibility in-case people were still using the 0.6.x ingestion schema.

**Comment by xvrl** [comment]
@nicktate we are removing support for the old ingestion schema in 0.7, so we can probably remove the field entirely. @fjy can you confirm?

**Comment by fjy** [comment]
@xvrl yes, we can remove the field directly. It was left there for backwards compatibility and should be removed.

**Pull request closed without merging**
