### PR TITLE
make sure CliCoordinator initializes and starts DerbyMetadataStorage first if configured

### PR DESCRIPTION
**Pull request by himanshug**
coordinator node sets up the derby server when configured to use derby as metadata store, it is supposed to setup the server first or else other db dependent things fail to start. due to the ambiguity in the setup process, it fails to start derby server first as soon as other things get loaded (I realized this while making changes to CliCoordinator to enable https://github.com/druid-io/druid/issues/3696 where derby was not getting setup early enough)

this patch takes away the ambiguity and ensures that metadata storage is created and started first in the process startup.

### CODE REVIEW

**Comment by pjain1** [comment]
👍

**Comment by cheddar** [comment]
Hrm, I'm not sure about this solution actually.  The reason there wasn't a "FIRST" stage created before was because the object dependency graph is supposed to ensure that dependees are created and registered before dependers.  That seems to be getting broken here, likely because it is going through `LifecycleModule.register()` to actually bootstrap instead of the normal object dependency graph.

Can you explore if it is possible to adjust the object dependency graph so that the things which require this to be started actually depend on it?

**Comment by himanshug** [comment]
@cheddar if stage FIRST is not to be introduced, then updated patch also solves the problem.
i have to make MetadataStorage a dependency of DerbyConnector even if it is not used by that, but this ensures that DerbyMetadataStorage gets created and started upfront.

**Comment by gianm** [comment]
@cheddar the issue is that the dependency is a network dependency (client depends on server) but that is not expressed in the object graph, because why would it be? We could include a "fake" object graph dependency like Himanshu did in the most recent patch, but that doesn't seem obviously better than something stage-based in the lifecycle.

**Comment by gianm** [comment]
@himanshug would it work to have the client side retry until the server is available, so even if the server starts up "late" then things will still work? Clients should be retrying until servers are available anyway.

**Comment by himanshug** [comment]
i see that tests are failing in the current patch, but I will fix those once we reach conclusion (so, ignore the build failure for now)

@gianm client already has ability to retry but when I'm doing #3711 , JacksonConfigManagerModule's getConfigManater(..)'s lifecycle handler fails. it seems everything inside.
currently startup of derby server is non-deterministic to certain degree as DerbyConnector or noone else is forcing the startup.

**Comment by himanshug** [comment]
adding some context to @cheddar 's +1
we had an offline conversation and concluded that lifecycle stuff should be taken out of MetadataStorage and should rather be made part of the specific connector (DerbyConnector in this case) , and this makes the dependency on MetadataStorage genuine rather than just for side effect.

**Pull request merged**
