### PR TITLE
Fix build issues with checkstyles

### PR DESCRIPTION
**Pull request by niketh**

### CODE REVIEW

**Comment by jon-wei** [comment]
There's another failure with GranularityPathSpecTest as well, this PR covers them both:

https://github.com/druid-io/druid/pull/3761

**Comment by gianm** [comment]
Travis detects merge conflicts but not checkstyle conflicts, bummer!

Closing in favor of #3761.

**Comment by niketh** [comment]
👍

**Comment by jon-wei** [comment]
@niketh the build failures have been fixed in #3761, thanks for the PR!

**Pull request closed without merging**
