### PR TITLE
allow one cache connection per processing thread

### PR DESCRIPTION
**Pull request by xvrl**
The memcached client uses a single connection and bulks operations together, causing processing threads to time out waiting for results of other threads when lots of cache items get requested. This adds a setting to allow each processing thread its own cache connection.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
+1

**Comment by drcrallen** [comment]
Can you put a comment at https://github.com/metamx/druid/blob/cache-connection-per-processing-thread/server/src/main/java/io/druid/client/cache/MemcachedCache.java#L554 that the clients are thread-local, so if there ever are resources to cleanup, making sure the correct client instance does the cleaning would be essential?

**Comment by xvrl** [comment]
@drcrallen the `close(String namespace)` method on the cache is there to invalidate cache items for overshadowed segments and free up memory, the comment is a bit misleading.

**Comment by drcrallen** [comment]
@xvrl Gotcha, :+1:  then

**Comment by gianm** [comment]
Spoke with @xvrl about this earlier, but just for the record, what we talked about was that it would probably be better to have a configurable number of cache clients rather than ThreadLocals. Having it be ThreadLocal will probably mean a lot more connections to the cache than we really need or want.

Side note, on the broker the cache checking would potentially sometimes happen in jetty threads and sometimes happen in processing threads. (the IntervalChunkingQueryRunner sometimes uses the processing pool and sometimes doesn't)

**Comment by drcrallen** [comment]
@gianm IMHO any sort of processing should be occurring in processing threads, so the number of clients should be controlled via that aspect. If the interval chunking query runner is doing work in a jetty thread then that seems like a bug.

**Comment by xvrl** [comment]
@gianm @drcrallen I've got a simple connection balancing almost done, will replace this PR when done.
Closing for now. Agree we should always use processing executor even if we don't use IntervalChunkingQueryRunner to be consistent.

**Comment by xvrl** [comment]
closed in favor of #1744

**Pull request closed without merging**
