### PR TITLE
Update libraries.md

### PR DESCRIPTION
**Pull request by r4ruchir**
Adding embedded-druid information in helper libraries

### CODE REVIEW

**Comment by fjy** [comment]
@r4ruchir Thanks for the contrib. I can merge this after http://druid.io/community/cla.html is filled out

**Comment by nishantmonu51** [comment]
:+1:

**Comment by r4ruchir** [comment]
Hi Fangjin,
I am working with our legal team to get CLA and hoping I will get in 1-2 days.
Thanks,
Ruchir

**Comment by fjy** [comment]
@r4ruchir any luck with the CLA?

**Comment by r4ruchir** [comment]
@fjy : looks like we need to get VP sign on this document. Hoping to get it soon and will update you.

**Comment by fjy** [comment]
@r4ruchir any update on this?

**Comment by r4ruchir** [comment]
Sorry Fangjin. It is still in pending state.

**Comment by fjy** [comment]
@r4ruchir anything?

**Comment by r4ruchir** [comment]
Finally got it signed and attached here.

Thanks,
Ruchir

**Comment by fjy** [comment]
Conflicts resolved in https://github.com/druid-io/druid/pull/2757

**Pull request closed without merging**
