### PR TITLE
fix ConcurrentModificationException in CachingClusteredClient.run()

### PR DESCRIPTION
**Pull request by kaijianding**
I had encountered an error in broker log
```
java.util.ConcurrentModificationException
at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207)
at java.util.TreeMap$KeyIterator.next(TreeMap.java:1261)
at io.druid.client.CachingClusteredClient.run(CachingClusteredClient.java:224)
```
this exception is thrown from line 2 of this block
```java
    for (TimelineObjectHolder<String, ServerSelector> holder : filteredServersLookup) {
      for (PartitionChunk<ServerSelector> chunk : holder.getObject()) {
        ServerSelector selector = chunk.getObject();
        final SegmentDescriptor descriptor = new SegmentDescriptor(
            holder.getInterval(), holder.getVersion(), chunk.getChunkNumber()
        );

        segments.add(Pair.of(selector, descriptor));
      }
    }
```
The iteration of holder.getObject() is actually the iteration of TreeSet < PartitionChunk  <  T  >  > holderSet in PartitionHolder, and TreeSet is not thread safe.

In BrokerServerView,  will finally add a new chunk to holderSet by
`timeline.add(segment.getInterval(), segment.getVersion(), segment.getShardSpec().createChunk(selector))`
when I have a realtime task using LinearShardSpec, a new chunk will be announced and added in BrokerServerView.

And in broker, the CachingClusteredClient will iterate the holderSet when query.

Thus, the holderSet is written and read by different threads which causing ConcurrentModificationException

This patch just modify `VersionedIntervalTimeline.lookup` to use `new PartitionHolder<ObjectType>(val.getPartitionHolder())` to obtain a new copy of holderSet

### CODE REVIEW

**Comment by drcrallen** [comment]
@kaijianding thanks for the PR, do you have a unit test that reproduces the behavior?

**Comment by kaijianding** [comment]
Don't have a unit test yet, I found this error in our production env log. Will write a test to reproduce this behavior.

**Comment by kaijianding** [comment]
Here is the unit test https://github.com/kaijianding/druid/blob/testCME/server/src/test/java/io/druid/client/BrokerServerViewTest.java
Please check the testSingleServerAddedSegmentAndRead, it will throw ConcurrentModificationException
@drcrallen

**Comment by gianm** [comment]
Perhaps it would be better for `VersionedIntervalTimeline.lookup` to return a snapshot using ImmutablePartitionHolders (like findEntry does). That way callers don't have to worry about their looked-up timelines being wibbly-wobbly.

**Comment by kaijianding** [comment]
Agree, I modified the fix to obtain a new  copy of PartitionHolder instead. @gianm 
Changing to ImmutablePartitionHolders can't pass the old unit test, so I just simply change to `new PartitionHolder<ObjectType>(val.getPartitionHolder())` which means the same thing.

**Comment by gianm** [comment]
👍 , that looks good to me. There would be some additional overhead for the new tree set, but it shouldn't be too bad (we aren't actually copying the underlying chunk objects, just the references).

**Comment by navis** [comment]
I can see some more `new TimelineObjectHolder()` in the class, like line of 244, 471, 483. Is it ok?

**Comment by gianm** [comment]
@navis the others in `lookup` (471, 483) I think are okay, since they re-use safe copies already created (not going back to original objects).

There's another one in `findOvershadowed` (244). I don't think that one causes bugs in production, because it's only used in one place (DruidCoordinatorCleanupOvershadowed), which doesn't do multithreaded writes. But it does look suspicious and might cause problems if it's used for other stuff in the future… it could be made into a copy too, to be safe.

**Comment by fjy** [comment]
👍 @navis any more comments?

**Comment by gianm** [comment]
👍

**Comment by navis** [comment]
👍

**Pull request merged**
