### PR TITLE
SQL: Add context and contextual functions to planner.

### PR DESCRIPTION
**Pull request by gianm**
Added support for context parameters specified as JDBC connection properties
or a JSON object for SQL-over-JSON-over-HTTP.

Also added features that depend on context functionality:

- Added CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP functions.
- Added support for time zones other than UTC via a "timeZone" context.
- Pass down query context to Druid queries too.

Also some bug fixes:

- Fix DATE handling, it was largely done incorrectly before.
- Fix CAST(__time TO DATE) which should do a floor-to-day.
- Fix non-equality comparisons to FLOOR(__time TO X).
- Fix maxQueryCount property.

### CODE REVIEW

**Comment by gianm** [comment]
This probably could be broken up into two smaller PRs (1- context, 2- time related stuff), but I did it as one since I ended up developing a few related things together (context ability + current_timestamp function + timezone stuff + DATE fixes).

**Comment by gianm** [comment]
Merged with master to pick up changes from #3838.

**Comment by fjy** [comment]
👍

**Comment by jon-wei** [comment]
looks good so far, will take another look after conflict fix

**Comment by gianm** [comment]
thx for the review @jon-wei, pushed a fix for conflicts.

**Comment by jon-wei** [comment]
:+1:

**Pull request merged**
