### PR TITLE
Make using implicit system Charset an error

### PR DESCRIPTION
**Pull request by leventov**
The rule is enforced via Error Prone.

Implicit system charset is replaced with explicit UTF-8, with a single exception in `LocalDataSegmentPuller`, where system charset is used explicitly.

### CODE REVIEW

**Comment by drcrallen** [comment]
Do any of these accept the `String` argument instead of the `Charset` argument? IIRC `String` is generally better to use.

Also, does this mean https://github.com/druid-io/druid/blob/druid-0.10.0/java-util/src/main/java/io/druid/java/util/common/StringUtils.java#L79 should be updated as well?

**Comment by leventov** [comment]
@drcrallen replaced usages of `String.getBytes()` and `new String()` with fast methods from `StringUtils`. 

Regarding https://github.com/druid-io/druid/blob/druid-0.10.0/java-util/src/main/java/io/druid/java/util/common/StringUtils.java#L79, added English locale, but a bigger problem is that there are more than 700 direct usages of `String.format()` in the project, made #4335 issue to track that.

**Comment by leventov** [comment]
BTW @nishantmonu51 I'm not sure that UTF-8 should be used here: https://github.com/druid-io/druid/pull/4326/files#diff-642712b19dd6ec8879e4288fef68a75fR84, could you please review that?

**Comment by leventov** [comment]
@gianm thanks for review, are you sure about https://github.com/druid-io/druid/pull/4326#issuecomment-304366983? Also pinging @nishantmonu51 again

**Comment by gianm** [comment]
I think the change in https://github.com/druid-io/druid/pull/4326#issuecomment-304366983 is fine, because the base64 encode should return a byte array in ascii encoding, and decoding ascii as utf-8 will work as expected.

**Comment by leventov** [comment]
It would better to explicitly decode the strings using `StandardCharsets.ASCII` in this case.

**Pull request merged**
