### PR TITLE
add test to OverlordResourceTest

### PR DESCRIPTION
**Pull request by pjain1**
Added test for getRunningTasks() and little refactoring

### CODE REVIEW

**Comment by himanshug** [comment]
LGTM (after travis is successful)

**Comment by fjy** [comment]
@pjain1 these tests do not pass travis

**Comment by pjain1** [comment]
@fjy let me check

**Comment by pjain1** [comment]
@fjy it is passing now

**Comment by fjy** [comment]
@pjain1 were changes required? if not, the test is not deterministic and we should understand why

**Comment by pjain1** [comment]
@fjy existing OverlordResourceTest in Druid master is deterministic. I added one test for getRunningTasks (the previous PR) and that was not deterministic. However, I have fixed it in this PR and all tests are deterministic now.

**Pull request merged**
