### PR TITLE
buildV9Directly in MergeTask and AppendTask

### PR DESCRIPTION
**Pull request by kaijianding**
#3688 missed these two tasks

### CODE REVIEW

**Comment by b-slim** [comment]
@kaijianding can you please update the docs as well ?

**Comment by b-slim** [comment]
👍

**Comment by b-slim** [comment]
looks like we have some timeout issue with this test.
```java
java.lang.Exception: test timed out after 60000 milliseconds

	at java.util.zip.ZipFile.read(Native Method)

	at java.util.zip.ZipFile.access$1400(ZipFile.java:61)

	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)

	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:420)

	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)

	at sun.misc.IOUtils.readFully(IOUtils.java:65)

	at java.util.jar.JarFile.getBytes(JarFile.java:425)

	at java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:555)

	at java.util.jar.JarFile.hasClassPathAttribute(JarFile.java:518)

	at java.util.jar.JavaUtilJarAccessImpl.jarFileHasClassPathAttribute(JavaUtilJarAccessImpl.java:37)

	at sun.misc.URLClassPath$JarLoader.getClassPath(URLClassPath.java:985)

	at sun.misc.URLClassPath.getLoader(URLClassPath.java:335)

	at sun.misc.URLClassPath.getResource(URLClassPath.java:198)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:364)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Class.java:344)

	at io.druid.granularity.QueryGranularityTest.testDeadLock(QueryGranularityTest.java:783)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:483)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by kaijianding** [comment]
UT issue reported: https://github.com/druid-io/druid/issues/3978  @b-slim

**Pull request merged**
