### PR TITLE
Fix analysisTypes docs for SegmentMetadataQuery.

### PR DESCRIPTION
**Pull request by gianm**

### CODE REVIEW

**Comment by jon-wei** [comment]
:+1:

**Comment by drcrallen** [comment]
:+1:

**Comment by nishantmonu51** [comment]
Tests in error: 
io.druid.indexing.worker.WorkerTaskMonitorTest.testRestartCleansOldStatus(io.druid.indexing.worker.WorkerTaskMonitorTest)
  Run 1: WorkerTaskMonitorTest.testRestartCleansOldStatus:331 »  test timed out after 3...
  Run 2: WorkerTaskMonitorTest.tearDown:205 » IllegalState not started

**Comment by jon-wei** [comment]
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 67.246 sec <<< FAILURE! - in io.druid.curator.announcement.AnnouncerTest
testSanity(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 61.121 sec  <<< ERROR!
java.lang.Exception: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.apache.curator.test.Timing.awaitLatch(Timing.java:120)
	at io.druid.curator.announcement.AnnouncerTest.testSanity(AnnouncerTest.java:101)

**Pull request merged**
