### PR TITLE
datasketches module updates

### PR DESCRIPTION
**Pull request by himanshug**
this PR
- updates the module to use latest released version sketches-core-0.2.2
- adds support for "cardinality" aggregator i.e. ability to run `thetaSketch` aggregator on non theta-sketch columns (similar to `hyperUniqueCardinality`)
- removes creation of one theta sketch per event at ingestion time, this is about 3x faster

@cheddar can you please review this one? thanks.

### CODE REVIEW

**Comment by drcrallen** [comment]
Are the data sketches backwards compatible? Meaning anything made with 1.x will be readable by 2.x?

**Comment by himanshug** [comment]
@drcrallen yes, they are.

there is backward compatibility baked in with old api that we use too, as soon as this is released , we will stop using the old module that we have internally.. migrate users to new apis and eventually remove support for those.
druid community users (or any other new users) would just use the new documented APIs.

**Comment by cheddar** [comment]
LGTM, :+1:

**Comment by fjy** [comment]
:+1:

**Pull request merged**
