### PR TITLE
Add context map to AuthenticationResult

### PR DESCRIPTION
**Pull request by jon-wei**
Adds a String->Object map to AuthenticationResult, for Authenticator/Authorizer combinations that require storing more information about the request than just an identity string.

This PR also removes the JSON property annotations from AuthenticationResult, since it shouldn't need to be serialized/deserialized.

### CODE REVIEW

**Comment by gianm** [comment]
@jon-wei please fix the conflicts.

**Comment by jon-wei** [comment]
@gianm merged and fixed conflicts, thanks

**Comment by pjain1** [comment]
@jon-wei does this need to be backported to 0.11.0 ?

**Comment by jon-wei** [comment]
@pjain1 Hm, it'd be nice to have, but 0.11.0 is code-frozen and this isn't a bug fix, so let's keep it out

**Comment by gianm** [comment]
This was in fact backported.

**Pull request merged**
