### PR TITLE
fix doc for druid.[host,port,service] etc

### PR DESCRIPTION
**Pull request by himanshug**

### CODE REVIEW

**Comment by xvrl** [comment]
In that case we should also change all the other default service names, since they currently all use `druid/` as prefix. It wouldn't make senose to mix and match.

**Comment by himanshug** [comment]
@xvrl , makes sense.. I thought druid.service was not set by default. updated that too.

**Comment by xvrl** [comment]
@himanshug since 0.7 host, port, and service all have proper defaults to make it easier to get started.

If we change service we need to also make a note in the release notes since it could affect people expecting to use the default.

The reasoning behind having the Druid prefix was to make it easier to integrate for users that are already using curator for service discovery.

**Comment by himanshug** [comment]
@xvrl yeah, I noticed that today in DruidNode code. Actually having "druid/" node as prefix is not that big of a deal. I removed it believing that was simplest and consistent to do. I don't think this is big enough to introduce backward incompatibility.
Let us just fix the documentation. how does that sound?

**Comment by xvrl** [comment]
It looks like we forgot to update the docs back when we did that change. We only updated examples to reflect the changes for some reason.

**Comment by himanshug** [comment]
OK, I am going to revert the code changes and just updating the doc

**Comment by xvrl** [comment]
Updating the docs sounds like a reasonable thing to do. My bad for missing that in the first place.

**Pull request merged**
