### PR TITLE
Queries: Restore old prepareAggregations method.

### PR DESCRIPTION
**Pull request by gianm**
For backwards compatibility, post-#4394.

### CODE REVIEW

**Comment by leventov** [comment]
@gianm I think 0.10.2 is going to be 0.11.0, so this PR should probably just not go to master, only to 0.10.1

**Comment by gianm** [comment]
I don't think there's an issue in 0.10.1, since #4394 wasn't included there. I'm still ok with this patch in master, it makes life a little easier for people upgrading, and that's always good. (just because we _can_ break an API doesn't mean we _should_)

**Comment by gianm** [comment]
Oops, 0.10.1 did include #4394, I was looking at 0.10.0. Point about master still stands though.

If we merge it to master I can do a backport to 0.10.1 after that. Or if we decide not to merge to master it could go directly to 0.10.1.

**Comment by jihoonson** [comment]
+1 for going directly to 0.10.1

**Pull request merged**
