### PR TITLE
Fix for file not found exception from the resource loader. 

### PR DESCRIPTION
**Pull request by b-slim**
Fix for https://github.com/druid-io/druid/issues/2916

### CODE REVIEW

**Comment by l15k4** [comment]
@b-slim LGTM, thanks !

**Comment by drcrallen** [comment]
@b-slim can you make the title of the commit and the master comment a bit more descriptive on what this is doing?

**Comment by b-slim** [comment]
@drcrallen sure will do.

**Comment by b-slim** [comment]
@drcrallen done

**Comment by drcrallen** [comment]
Since this is community contrib 👍

**Comment by fjy** [comment]
👍

**Pull request merged**
