### PR TITLE
updated dependency on sketches-core

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**
Let's use the latest release of sketches-core. The only change required in the Druid code was to implement one more update method, which takes char[]. Historical data must be fully compatible.

### CODE REVIEW

**Comment by gianm** [comment]
was there any change in storage format?

if not then 👍

**Comment by AlexanderSaydakov** [comment]
The serialized format must be the same.

**Comment by AlexanderSaydakov** [comment]
I didn't realize that Druid gets built for both JDK7 and JDK8. Support for JDK7 has been dropped in sketches-core-0.5.0. So if this is a barrier, the latest version we can use is 0.4.1

**Comment by AlexanderSaydakov** [comment]
I was going to work on a new aggregator using latest sketches. This issue makes this plan questionable. Is there a plan to stop building Druid for JDK7?

**Comment by fjy** [comment]
@AlexanderSaydakov See https://groups.google.com/forum/#!topic/druid-user/aTGQlnF1KLk

**Comment by gianm** [comment]
@AlexanderSaydakov the approach taken with the caffeine (#3028), which also requires Java 8, is to have that particular extension target Java 8 but the rest of Druid target Java 7.

In this case since the datasketches extension already supported Java 7, we probably want to keep supporting it, but it should be ok to make a new datasketches-xxx extension for your new "xxx" aggregator.

**Comment by gianm** [comment]
👍  on the update to 0.4.1

**Comment by fjy** [comment]
👍

**Pull request merged**
