### PR TITLE
Update bytebuffer-collections to 0.2.4

### PR DESCRIPTION
**Pull request by drcrallen**
Fixes https://github.com/druid-io/druid/issues/2218
Pulls in fix for https://github.com/RoaringBitmap/RoaringBitmap/issues/61

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by gianm** [comment]
:+1: after travis

**Comment by drcrallen** [comment]
```
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 71.126 sec <<< FAILURE! - in io.druid.server.namespace.cache.JDBCExtractionNamespaceTest
testFindNew[null](io.druid.server.namespace.cache.JDBCExtractionNamespaceTest)  Time elapsed: 60.92 sec  <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.druid.server.namespace.cache.JDBCExtractionNamespaceTest.tearDown(JDBCExtractionNamespaceTest.java:307)
```

**Comment by drcrallen** [comment]
The big question is: Do we want this added to an 0.8.3-rc4 ?

**Comment by fjy** [comment]
@drcrallen I think it is fine for this to wait.

**Comment by xvrl** [comment]
@fjy in that case we should mark roaring as unsafe to use in 0.8.x?

**Comment by gianm** [comment]
I think 0.8.3-rc4 is appropriate, as roaring is not an experimental feature so bug fixes are important.

**Comment by gianm** [comment]
0.8.4 would be cool too.

**Pull request merged**
