### PR TITLE
Sketch cache key should include size, isInputThetaSketch.

### PR DESCRIPTION
**Pull request by gianm**

### CODE REVIEW

**Comment by himanshug** [comment]
@gianm getCacheKey() is a query time concept and not having those two fields in the cache key should be OK? It was intentional to not have those in cache key.
Did you encounter any issues there?

**Comment by gianm** [comment]
@himanshug wouldn't the size of the sketch affect query results? especially if this is run over a field which at query time is a string, not a sketch metric.

**Comment by himanshug** [comment]
@gianm yeah , you are right, size would have impact on accuracy, i stand corrected. but isInputThetaSketch shouldn't change anything at query time.

**Comment by gianm** [comment]
I was thinking that `isInputThetaSketch = false` on a sketch metric should succeed, and `isInputThetaSketch = true` on a string column should fail, so if someone changes it from false to true that should fail (rather than pull from cache)

**Comment by gianm** [comment]
same for the reverse.

**Comment by himanshug** [comment]
isInputThetaSketch is only useful while ingestion if your input data was sketches... at query time it plays no role.
at query time , users would just leave it be default.

**Comment by gianm** [comment]
@himanshug ah I see, you use instanceof at query time to determine the type, not `isInputThetaSketch`. ok, that should be removed from the cache key. will do another pr.

**Comment by gianm** [comment]
https://github.com/druid-io/druid/pull/2899

**Pull request merged**
