### PR TITLE
cache max data timestamp in QueryableIndexStorageAdapter 

### PR DESCRIPTION
**Pull request by himanshug**
so that TimestampCheckingOffset does not have to get it per cursor.

### CODE REVIEW

**Comment by xvrl** [comment]
@himanshug cool, any idea how much of a difference this makes?

**Comment by xvrl** [comment]
:+1:  looks good to me otherwise

**Comment by himanshug** [comment]
@xvrl on a 500M segment containing about 48mn rows, when I ask data at NONE query granularity, it takes forever to go through without this change (completes in abt 5 mins with this change).
It is because sequential access on a [time] column is fast but older code would add a jump in the [time] column access on each cursor boundary.

**Comment by nishantmonu51** [comment]
:+1:

**Comment by gianm** [comment]
:+1:

**Pull request merged**
