### PR TITLE
Fix CachingCostBalancerStrategyFactory's constructor

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by gianm** [comment]
@leventov does this need to be included in 0.11.0? (you have marked it as such but I don't see a reason why in the PR description)

**Comment by leventov** [comment]
@gianm it's a bug that makes `cachingCost` balancer strategy absolutely dysfunctional. BTW all users are encouraged to try `cachingCost` in production in 0.11.0 because the plan is that it's going to become the default balancer strategy in the next release. It's going to replace `cost`, i. e. `cost` and `cachingCost` will mean the same.

**Comment by gianm** [comment]
Thanks for the explanation. Let's then also make sure that the encouragement to try out `cachingCost` makes it into the release notes for 0.11.0. I'll mark this issue as "Release notes" as a reminder.

**Comment by leventov** [comment]
@gianm better #4731 because it has explanations

**Comment by himanshug** [comment]
:+1:

**Pull request merged**
