### PR TITLE
Rename fields in OrderedMergeIterator

### PR DESCRIPTION
**Pull request by jianran**
code readable,the pQueue rename to firstElementComparedPQueue

### CODE REVIEW

**Comment by gianm** [comment]
-0 from me as this change is renaming some variables that I personally do not feel need renaming. But if anyone else is +1 then go for it. Otherwise, @jianran, thanks anyway for the interest!

**Comment by drcrallen** [comment]
Anything that a new set of eyes says makes it easier to read I'll take as reasonable to change.

👍 from my side

http://druid.io/community/cla.html @jianran would you mind filling out the CLA?

**Comment by drcrallen** [comment]
Also can you change the title to be more readable like "Rename fields in OrderedMergeIterator" ?

**Comment by jianran** [comment]
change the title

**Comment by jianran** [comment]
change the title

**Pull request merged**
