### PR TITLE
Make PolyBind to fail if property value is not found (fixes #4369)

### LINKED ISSUE #4369: Guice PolyBind - must fail with error if specified value not found, instead of binding the default
When there is a polyBind:
```java
PolyBind.createChoice(binder, "key", Key.get(Foo.class), Key.get(DefaultFooImpl.class));
```

And the value in config `key=nonFound` couldn't be found in classpath, dependency injection must fail with error instead of using `DefaultFooImpl`.

### PR DESCRIPTION
**Pull request by leventov**
When there is a polyBind:
```java
PolyBind.createChoice(binder, "key", Key.get(Foo.class), Key.get(DefaultFooImpl.class));
```

And the value in config `key=nonFound` couldn't be found in classpath, dependency injection must fail with error instead of using `DefaultFooImpl`. Because it's 100% a error either in classpath or a typo in configuration, and silently consuming this problem may lead to hard-to-find bugs and not met expectations.

Fixes  #4369

### CODE REVIEW

**Comment by b-slim** [comment]
👍 after CI

**Comment by leventov** [comment]
This PR always fails integration tests, probably it is not a transient failure. However I cannot understand how connections failures in Netty related to this PR.

**Comment by jihoonson** [comment]
The problem looks that a coordinator failed to start on a docker machine (https://github.com/druid-io/druid/issues/4359#issuecomment-306661974). Maybe there are some places where a coordinator use the default value?

**Comment by gianm** [comment]
Good job, integration tests 😄

**Comment by leventov** [comment]
Related: #4380

**Comment by leventov** [comment]
@b-slim could you please review the newer version

**Comment by b-slim** [comment]
LGTM

**Comment by leventov** [comment]
@b-slim could this PR be merged?

**Comment by himanshug** [comment]
Just want to note here that this PR appears to have changed behavior of `PolyBind.createChoiceWithDefault(..)` which is used in some custom extensions. On upgrade to 0.10.1, that led to error like...
```
"
Unknown provider[xx] of Key[type=com.MyClass, annotation=[none]], known options[yy]
  at io.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:105) (via modules: com.google.inject.util.Modules$OverrideModule -> com.MyNamespaceExtractionModule)
  at io.druid.guice.PolyBind.createChoiceWithDefault(PolyBind.java:105) (via modules: com.google.inject.util.Modules$OverrideModule -> com.MyNamespaceExtractionModule)
  while locating com.MyClass
  ...
  ...
"
```

and following type of code...
```
        PolyBind.createChoiceWithDefault(
                 binder,
                 TYPE_PREFIX,
                 Key.get(MyExtractionCacheManager.class),
                 Key.get(OnHeapMyExtractionCacheManager.class),
                 "onHeap"
         ).in(LazySingleton.class);

```

was required to be replaced with

```

         PolyBind
                 .createChoiceWithDefault(binder, TYPE_PREFIX, Key.get(MyExtractionCacheManager.class), "onHeap")
                 .in(LazySingleton.class);
          PolyBind
                 .optionBinder(binder, Key.get(MyExtractionCacheManager.class))
                 .addBinding("onHeap")
                 .to(OnHeapMyExtractionCacheManager.class)
                 .in(LazySingleton.class);



```

@leventov does that look expected ?

**Comment by leventov** [comment]
@himanshug it looks like there is a problem with `createChoiceWithDefault()`

**Pull request merged**
