### PR TITLE
fix caching for search results

### PR DESCRIPTION
**Pull request by nishantmonu51**
properly read count when reading from cache.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by fjy** [comment]
@nishantmonu51 after this fix do integration tests all pass?

**Comment by gianm** [comment]
It looks like SearchBinaryFn doesn't check if each incoming searchHit has a null count or not. It looks like it assumes that if one searchHit has a count, then they all will (it will blindly + them together without null checks). So it'll probably NPE.

That could cause a couple of issues,

- with rolling updates, some historicals will report counts, some will report nulls, and broker merging may NPE.
- with network caches, older cached results will have null counts

not sure of the best way to fix this, perhaps have SearchBinaryFn set count to null if any sub-count is null? (Treating as zero is really misleading). That'll help with rolling updates but still cause issues with network caches unless the entries are invalidated by changing the cache key.

**Comment by nishantmonu51** [comment]
@fjy: yeah the integration tests pass after this fix. 
@gianm:  updated the merge function to handle NPE & updated cache key.

**Comment by gianm** [comment]
thanks @nishantmonu51 👍

**Pull request merged**
