### PR TITLE
Faster interval comparator

### PR DESCRIPTION
**Pull request by navis**
This is a part of #3536 but I'm pretty sure that no one will ever interested in it. So I've extracted the most simple and easy part to lessen the burden of coordinator.

Current implementation should make DateTime instance to compare two intervals, which can be huge work when sorting 300K+ segments in coordinator.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
👍

**Comment by jaehc** [comment]
LGTM

**Comment by drcrallen** [comment]
Do you have benchmarks showing the speedup?

**Comment by fjy** [comment]
👍

**Comment by navis** [comment]
@drcrallen not much difference in number itself (694ms vs 1190ms for sorting 1M random intervals) but it substantially reduced gc pressure, as we uses small "druid.coordinator.period" like 5sec.

**Pull request merged**
