### PR TITLE
groupBy v2: Better error message when resources are exhausted.

### LINKED ISSUE #4043: groupBy v2: Better error message when resources are exhausted
See comments:

- https://github.com/druid-io/druid/pull/3953#issuecomment-281823683
- https://github.com/druid-io/druid/pull/3953#issuecomment-281851768

I think this would be a small change, and could go to 0.10.0 (since groupBy v2 is being made default there).

### PR DESCRIPTION
**Pull request by gianm**
Fixes #4043.

### CODE REVIEW

**Comment by gianm** [comment]
Oops, need to fix some tests.

**Comment by himanshug** [comment]
:+1:

**Comment by nishantmonu51** [comment]
👍

**Comment by himanshug** [comment]
@gianm sometimes queries fail and the error message still does not say exactly what was the cause, that makes tuning difficult.
what do you think about the throwing exception approach ( https://github.com/druid-io/druid/pull/3953#issuecomment-281848859 ) so that message is generated where error happens.

**Pull request merged**
