### PR TITLE
Downgrade Netty version 4.1 -> 4.0

### PR DESCRIPTION
**Pull request by leventov**
Because of #4390 and the problems with client: https://github.com/druid-io/druid/pull/4973#issuecomment-342958133, I agree now that it's better to downgrade, as was suggested here: https://github.com/druid-io/druid/issues/4390#issuecomment-307913911

### CODE REVIEW

**Comment by b-slim** [comment]
@leventov should we backport this?

**Comment by leventov** [comment]
If it passes tests...

**Comment by b-slim** [comment]
👍  after testing

**Comment by b-slim** [comment]
@leventov not sure why this PR has a design review tag? seems to me we are reverting to the known working version of Netty.

**Comment by gianm** [comment]
LGTM.

**Comment by himanshug** [comment]
:+1:
a little late to review but we deployed this patch and can confirm that it fixes the problem mentioned in https://github.com/druid-io/druid/pull/4973#issuecomment-342958133

**Pull request merged**
