### PR TITLE
Update Tutorial with new Zookeper Version and instructions

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Follow on https://github.com/druid-io/druid-io.github.io/issues/193#issuecomment-162354625

### CODE REVIEW

**Comment by gianm** [comment]
@AdrieanKhisbe, thanks for the contribution!

Could you please fill out the Druid Individual CLA at http://druid.io/community/cla.html, or if you work for a corporation that has already filled one out could you let us know which one that is?

**Comment by AdrieanKhisbe** [comment]
Hey @gianm! I just filled the form :)

**Comment by gianm** [comment]
@AdrieanKhisbe thanks! :+1:

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

**Pull request merged**
