### PR TITLE
Backport of lookup sync on startup to 0.11.0

### PR DESCRIPTION
**Pull request by a2l007**
Backporting #4758

### CODE REVIEW

**Comment by a2l007** [comment]
@himanshug @leventov

**Comment by himanshug** [comment]
:+1: let us merge after build passes

**Comment by leventov** [comment]
@a2l007 in the future it's better to cherry-pick merge commit: https://github.com/druid-io/druid/commit/c07678b143663dde069569ab77c9803901d78a73

**Comment by gianm** [comment]
@a2l007 could you please update this patch to be based off the most recent 0.11.0 branch? It has #4978 in it, which should help CI pass.

**Pull request merged**
