### PR TITLE
updating thetaSketchSetOp post agg documentation to reflect the possibility of nesting

### PR DESCRIPTION
**Pull request by himanshug**
came up in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/druid-user/QSCM-VN27D4/MKXbsyElCwAJ

### CODE REVIEW

**Comment by b-slim** [comment]
:+1:

**Comment by drcrallen** [comment]
```
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.134 sec <<< FAILURE! - in io.druid.indexing.common.task.RealtimeIndexTaskTest
testRestoreCorruptData[buildV9Directly = false](io.druid.indexing.common.task.RealtimeIndexTaskTest)  Time elapsed: 14.581 sec  <<< ERROR!
java.lang.Exception: test timed out after 10000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.druid.indexing.common.task.RealtimeIndexTaskTest.testRestoreCorruptData(RealtimeIndexTaskTest.java:499)
testRunExistingTaskThatHasntStartedRunning(io.druid.indexing.overlord.RemoteTaskRunnerTest)  Time elapsed: 1.356 sec  <<< FAILURE!
java.lang.AssertionError: expected:<SUCCESS> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.druid.indexing.overlord.RemoteTaskRunnerTest.testRunExistingTaskThatHasntStartedRunning(RemoteTaskRunnerTest.java:160)
```

**Comment by fjy** [comment]
@drcrallen can we file an issue about the failed test?

**Comment by himanshug** [comment]
@fjy filed issue https://github.com/druid-io/druid/issues/2515 

Thanks everyone for watching the build.

**Comment by nishantmonu51** [comment]
:+1:

**Comment by nishantmonu51** [comment]
closed, by mistake. reopened

**Pull request merged**
