### PR TITLE
Add StorageAdapter#getColumnTypeName, and various SegmentMetadataQuery adjustments

### PR DESCRIPTION
**Pull request by gianm**
Added StorageAdapter#getColumnTypeName

Also segmentMetadataQuery stuff:

- Simplify implementation of SegmentAnalyzer.
- Fix type names for realtime complex columns; this used to try to merge a nice type
  name (like "hyperUnique") from mmapped segments with the word "COMPLEX" from incremental
  index segments, leading to a merge failure. Now it always uses the nice name.
- Add hasMultipleValues to ColumnAnalysis.
- Add tests for both mmapped and incremental index segments.
- Update docs to include errorMessage.

### CODE REVIEW

**Comment by fjy** [comment]
Travis seems to be really wacky today...

**Comment by fjy** [comment]
:+1: LGTM

**Comment by fjy** [comment]
@gianm this is failing unit tests

**Comment by gianm** [comment]
@fjy ah sorry will fix

**Comment by gianm** [comment]
@fjy re-pushed

**Comment by gianm** [comment]
AnnouncerTest.testSessionKilled:176 »  test timed out after 60000 milliseconds

**Comment by jon-wei** [comment]
:+1: after travis

**Comment by gianm** [comment]
rebased against master

**Pull request merged**
