### PR TITLE
0.8.3 backports

### LINKED ISSUE #1802: Query cancellation is not properly forwarded by Router
`io.druid.server.AsyncQueryForwardingServlet` does not attempt to make sure a query cancellation is received by proper broker. Instead of forwarding the cancellation DELETE to the proper broker, it will choose the default broker and send the delete to that one.

### PR DESCRIPTION
**Pull request by gianm**
Backport:

#1387  Add special handler to allow logger messages during shutdown [Ease of Use]
#1791 EventReceiverFirehoseMonitor
#1799  Support multiple outer aggregators of same type and provide more help…
#1815  Fix Race in jar upload during hadoop indexing
#1832 add examples for duration and period granularities
#1843  "druid.manager.segment" should be "druid.manager.segments
#1854  Fix documentation about lookup
#1867  fixing hadoop test scope dependencies in indexing-hadoop
#1881  Restorable indexing tasks
#1888  forward cancellation request to all brokers, fixes #1802
#1897  complex aggregator based on http://datasketches.github.io
#1900  fix doc - correct default value for
#1917  RemoteTaskActionClient: Fix statusCode check.
#1920  Update curator to 2.9.1
#1929 separate ingestion and query thread pool
#1932  DataSchema: Exclude metric names from dimension list.
#1935  ForkingTaskRunner: Log without buffering.
#1943 Enable caching on intermediate realtime persists
#1954 EC2 autoscaler: avoid hitting aws filter limits
#1957 Ability to skip Incremental Index during query using query context
#1960 optimize index merge
#1991 datasketches module updates

Additional Release Notes updates:
min/max aggregators are deprecated and will be removed in druid-0.9.0 release. please use [long/double]Min/Max aggregators.

### CODE REVIEW

**Comment by himanshug** [comment]
can you please include https://github.com/druid-io/druid/pull/1991 as well?

**Comment by gianm** [comment]
@himanshug ok, added

**Comment by nishantmonu51** [comment]
can you also add  #1943 #1957 ?

**Comment by gianm** [comment]
@nishantmonu51 added #1957, but there are a lot of merge conflicts with #1943 so maybe we can do that in a separate PR

**Comment by guobingkun** [comment]
#1832 could be included too.

**Comment by pjain1** [comment]
can #1929 be added as well ?

**Comment by gianm** [comment]
@guobingkun added #1832

**Comment by gianm** [comment]
@pjain1 added #1929

**Comment by nishantmonu51** [comment]
@gianm I think we don't need to block 0.8.3 for  #1943 and #1967 since both of them are additional features and not bug fixes, they can wait for 0.9.

**Comment by gianm** [comment]
@nishantmonu51 ok, sounds good. I think this PR is ready to review then.

**Comment by himanshug** [comment]
:+1: for me once the build passes, not sure if we can review all the changes in this PR.

**Comment by gianm** [comment]
@himanshug I mostly just meant the list of patches included :)

**Comment by xvrl** [comment]
@gianm since we're backporting new features (such as restorables tasks) we might as as well backport a few more. You can cherry-pick #1943, #1954, #1955, as well as #1960 from here
https://github.com/metamx/druid/pull/11 and https://github.com/metamx/druid/pull/10

**Comment by drcrallen** [comment]
mmx#10 is just https://github.com/druid-io/druid/pull/1960

**Comment by gianm** [comment]
@xvrl added #1943, #1954, #1960. #1955 was already in

**Comment by xvrl** [comment]
:+1:

**Pull request merged**
