### PR TITLE
Update batch-ingestion.md

### PR DESCRIPTION
**Pull request by loganlinn**
Fix documented type of the `dataGranularity` config

### CODE REVIEW

**Comment by fjy** [comment]
@loganlinn Thanks for this fix. Do you mind signing the CLA really quick? http://druid.io/community/cla.html I'll merge the PR after that.

**Comment by drcrallen** [comment]
@fjy is this correct though? `io.druid.indexer.path.GranularityPathSpec` has it as a `com.metamx.common.Granularity`

**Comment by fjy** [comment]
@drcrallen Oh I thought this was a different granularity.

**Comment by drcrallen** [comment]
@fjy I might be wrong :) I'm trying to dig through the documentation in reverse.... figuring out which of the billion granularities druid has this one is talking about

**Comment by fjy** [comment]
@drcrallen I don't think actual object support is there for java.util granularity

**Comment by loganlinn** [comment]
@fjy CLA signed

The test seems to indicate that it's a string: https://github.com/druid-io/druid/blob/fc0992950326e727e2f586a7594ec661c9e40627/indexing-hadoop/src/test/java/io/druid/indexer/path/GranularityPathSpecTest.java#L174-L176

**Comment by drcrallen** [comment]
Cool. Added test in #2302 to ensure the jackson enum converter is behaving as expected for this setting.

:+1:

**Pull request merged**
