### PR TITLE
upgrade zookeeper client dependency to 3.4.8

### PR DESCRIPTION
**Pull request by xvrl**
Follow-up to #2829

### CODE REVIEW

**Comment by drcrallen** [comment]
👍

**Comment by nishantmonu51** [comment]
Travis Failure with java8 - 
io.druid.curator.announcement.AnnouncerTest
testCleansUpItsLittleTurdlings(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 13.218 sec  <<< FAILURE!
java.lang.AssertionError: expected null, but was:<2,2,1461091070509,1461091070509,0,2,0,0,11,0,5
>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:664)
	at org.junit.Assert.assertNull(Assert.java:646)
	at org.junit.Assert.assertNull(Assert.java:656)
	at io.druid.curator.announcement.AnnouncerTest.testCleansUpItsLittleTurdlings(AnnouncerTest.java:210)
https://travis-ci.org/druid-io/druid/jobs/124264705

**Comment by xvrl** [comment]
@nishantmonu51 I restarted the build, let's see if it passes the second time around.

**Comment by nishantmonu51** [comment]
:+1:

**Pull request merged**
