### PR TITLE
Close out some potential Yielder resource leaks.

### PR DESCRIPTION
**Pull request by drcrallen**
Makes sure all instances of toYielder have their result closed out or returned as a return value.

### CODE REVIEW

**Comment by drcrallen** [comment]
Some of these might be superfluous

**Comment by xvrl** [comment]
we definitely need tests for those

**Comment by drcrallen** [comment]
Yes, and I'm trying to see if there's a reasonable way to test errors

**Comment by nishantmonu51** [comment]
+1 for tests

**Comment by drcrallen** [comment]
I'm going to cancel this for now because I think it is too risky without more thorough investigation.

**Pull request closed without merging**
