### PR TITLE
Update Zookeeper version

### PR DESCRIPTION
**Pull request by nishantmonu51**
one critical fix - 
https://issues.apache.org/jira/browse/ZOOKEEPER-2355

Release Notes - 
https://zookeeper.apache.org/doc/r3.4.11/releasenotes.html

Also, see if this  fixes - https://github.com/druid-io/druid/issues/2373

### CODE REVIEW

**Comment by nishantmonu51** [comment]
https://github.com/druid-io/druid/issues/2373 still seems to be failing intermittently with these changes. 
But this PR is good to be checked in, will look into the failure separately.

**Comment by himanshug** [comment]
@nishantmonu51 will this require users to upgrade their zookeeper servers or client upgrade without upgrading zookeeper server is alright?

**Comment by nishantmonu51** [comment]
Haven't done extensive testing but just ran Integration tests with older version of zookeeper.
They work fine without upgrading zookeeper server.

**Comment by leventov** [comment]
Looks like there are enough approvals and no 👎 , merging

**Pull request merged**
