### PR TITLE
Druid filter extensions

### PR DESCRIPTION
**Pull request by navis**
Originally from #2473 but declined by some reason. But by requests from my colleges, I've moved this to extension. Not expecting to be committed but maybe someone can find usefulness in here.

### CODE REVIEW

**Comment by fjy** [comment]
:+1: because I am refactoring extensions and we're moving towards being extremely lenient in community extensions vs core extensions to speed up how fast code gets in.

@navis I just noticed the thread in #2473 :(

**Comment by gianm** [comment]
@navis, @fjy, IMO the spirit behind this PR (and #2473) is important enough to get into core.

- it's good to be able to filter with ops other than =, without using JS
- it's good for ops like > and < to take advantage of sortedness of the bitmap indexes (bound filter currently in core does not do this)

Would it make sense to address these by modifying the BoundFilter in these ways?

- make it *not* a DimensionPredicateFilter but instead do its own thing
- have it take advantage of sortedness when possible (I think this is possible when `alphaNumeric` is false)

**Comment by i1befree** [comment]
@navis Thnks. It will be very helpful for someone who wants to implement BI like tool.

**Comment by fjy** [comment]
I agree with @gianm's comments. @navis thoughts?

**Comment by navis** [comment]
@fjy @gianm I think this might be better in extension. This is good example of extending `DimFilter` which is currently not possible but now possible with newly introduced `DimFilterExtension` interface in this patch. And also I'm a little concerned of using undocumented semantic of `Indexed.indexOf()`.

**Comment by fjy** [comment]
@gianm thoughts?

**Comment by fjy** [comment]
@navis can we update this PR now that #2713 is  merged?

**Comment by gianm** [comment]
@navis #2727 is the BoundFilter changes I was talking about, it also tightens the contract of GenericIndexed.indexOf (not Indexed, since it has a bunch of impls that do not satisfy that contract)

**Comment by navis** [comment]
@gianm

**Comment by navis** [comment]
If it's preferred way to make an another PR rather than addressing exsiting PR, what's the point of making it for others? I cannot understand that.

**Comment by gianm** [comment]
@navis, sorry, I thought your core need with this PR was wanting a binary operator filter. In my mind that was separate from #2727, where the core need was wanting to optimize the bound filter. So that's why I did a separate PR.

If you still need a binary operator filter then I think it makes sense to keep going with this PR.

**Pull request closed without merging**
