### PR TITLE
Make the Coordinator Cost Balancer thread naming human friendly

### PR DESCRIPTION
**Pull request by drcrallen**
This thread pool has an [old history](https://github.com/druid-io/druid/commits/a049188d23a0a3fd8d6ac531e5e116beca829465/server/src/main/java/io/druid/server/coordinator/CostBalancerMultithreadStrategy.java). This PR is to bring the naming up to scruff with current general ways of naming things.

This has a side-effect of making the threads daemon threads, but the block which defines the executor service has a finally which calls `shutdownNow`, so it should be ok.

### CODE REVIEW

**Comment by drcrallen** [comment]
@leventov is there a way to get teamcity results be visible without a login?

**Comment by leventov** [comment]
@drcrallen the reason of the failure is that you based your post-#4348 PR on a pre-#4348 commit.

**Comment by leventov** [comment]
@drcrallen there is a link "Log in as guest" on the authorization page. It will forward to results without any extra steps.

**Comment by fjy** [comment]
@drcrallen @leventov does this absolutely need to be in 0.10.1?

**Comment by leventov** [comment]
@fjy I think no, but I don't see problems with merging it, since there are still several outstanding PRs and issues in 0.10.1 which are quite far from being merged/resolved.

**Pull request merged**
