### PR TITLE
Add, fix equals, hashCode, toString on various classes.

### PR DESCRIPTION
**Pull request by gianm**
Also allow InDimFilter to accept a Collection.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by navis** [comment]
How about to use `Objects.equals/Objects.hash`? Just an opinion.

**Comment by gianm** [comment]
@navis these are just the IntelliJ defaults. I could switch them I guess. I usually use the IntelliJ defaults because Objects.equals doesn't handle arrays properly and sometimes I forget that when generating code.

**Comment by dclim** [comment]
👍

**Pull request merged**
