### PR TITLE
upgrade curator, fixes #2829

### LINKED ISSUE #2829: Update Curator to 2.10.0
I would be a good idea to update Curator to 2.10.0 because of this bug: [CURATOR-209](https://issues.apache.org/jira/browse/CURATOR-209)

It causes the following exceptions in coordinator and realtime nodes:
**Coordinator stacktrace:**
```
2016-04-13_14:27:40.57990 2016-04-13 14:27:40,579 INFO [main-SendThread(10.76.153.63:2181)] org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.76.153.63/10.76.153.63:2181. Will not attempt to authenticate using SASL (unknown error)
2016-04-13_14:27:40.58457 2016-04-13 14:27:40,580 INFO [main-SendThread(10.76.153.63:2181)] org.apache.zookeeper.ClientCnxn - Socket connection established to 10.76.153.63/10.76.153.63:2181, initiating session
2016-04-13_14:27:40.63265 2016-04-13 14:27:40,627 INFO [main-SendThread(10.76.153.63:2181)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server 10.76.153.63/10.76.153.63:2181, sessionid = 0x253f557d4b8013c, negotiated timeout = 30000
2016-04-13_14:27:40.64640 2016-04-13 14:27:40,646 INFO [main-EventThread] org.apache.curator.framework.state.ConnectionStateManager - State change: RECONNECTED
2016-04-13_14:27:40.64642 2016-04-13 14:27:40,646 WARN [main-EventThread] org.apache.curator.framework.state.ConnectionStateManager - ConnectionStateManager queue full - dropping events to make room
2016-04-13_14:27:40.64649 2016-04-13 14:27:40,646 INFO [main-SendThread(10.76.153.63:2181)] org.apache.zookeeper.ClientCnxn - Unable to read additional data from server sessionid 0x253f557d4b8013c, likely server has closed socket, closing socket connection and attempting reconnect
2016-04-13_14:27:40.76001 2016-04-13 14:27:40,759 INFO [main-EventThread] org.apache.curator.framework.state.ConnectionStateManager - State change: SUSPENDED
2016-04-13_14:27:40.76003 2016-04-13 14:27:40,759 WARN [main-EventThread] org.apache.curator.framework.state.ConnectionStateManager - ConnectionStateManager queue full - dropping events to make room
```

**Realtime stacktrace:**
```
2016-04-13_14:26:46.06347 2016-04-13 14:26:46,061 ERROR [CuratorFramework-0-EventThread] org.apache.curator.framework.imps.CuratorFrameworkImpl - Background operation retry gave up
2016-04-13_14:26:46.06347 org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
2016-04-13_14:26:46.06347       at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
2016-04-13_14:26:46.06348       at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:666)
2016-04-13_14:26:46.06348       at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:479)
2016-04-13_14:26:46.06348       at org.apache.curator.framework.imps.CreateBuilderImpl.sendBackgroundResponse(CreateBuilderImpl.java:526)
2016-04-13_14:26:46.06348       at org.apache.curator.framework.imps.CreateBuilderImpl.access$600(CreateBuilderImpl.java:44)
2016-04-13_14:26:46.06348       at org.apache.curator.framework.imps.CreateBuilderImpl$6.processResult(CreateBuilderImpl.java:485)
2016-04-13_14:26:46.06349       at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:602)
2016-04-13_14:26:46.06349       at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:495)
```

Eventually, this causes realtime nodes to stop ingesting data via Kafka Firehose. Only a restart can fix the problem.

I'm not sure of this, but I think that this also causes the stopping of the handoff: segments from realtime nodes are not handed off to historical nodes.

There is also a similar issue: #2495

### PR DESCRIPTION
**Pull request by xvrl**

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by drcrallen** [comment]
This uses ` <zookeeper-version>3.5.1-alpha</zookeeper-version>` which was mentioned in https://github.com/druid-io/druid/issues/2495 that we shouldn't use an alpha zookeeper version 👎 without a wider discussion on if an alpha version of ZK is desired.

**Comment by gianm** [comment]
@drcrallen I think 2.10 is ok: http://search.maven.org/#artifactdetails%7Corg.apache.curator%7Capache-curator%7C2.10.0%7Cpom. Looks like it uses ZK 3.4.6. IIRC the 3.x Curators are the ones that use alpha ZKs.

So 👍 on this and maybe we should also consider updating to ZK 3.4.8 (the stable release right now).

**Comment by drcrallen** [comment]
https://github.com/apache/curator/blob/apache-curator-2.10.0/pom.xml there it is. Must have mis-typed the version when I was looking around.

**Pull request merged**
