### PR TITLE
generate tarball by mvn package

### PR DESCRIPTION
**Pull request by guobingkun**
Fixes https://github.com/druid-io/druid/issues/2440

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by drcrallen** [comment]
:+1:

**Comment by drcrallen** [comment]
waiting for travis

**Comment by drcrallen** [comment]
@guobingkun will you be able to backport this to 0.9.0?

**Comment by guobingkun** [comment]
@drcrallen  Done by #2499

**Comment by guobingkun** [comment]
I would like to have @xvrl take a look at it before merging since he sent #2440

**Comment by fjy** [comment]
@guobingkun @xvrl is going to be out for awhile

**Pull request merged**
