### PR TITLE
Fix StatsD Emitter with blank character

### PR DESCRIPTION
**Pull request by skyler-tao**
fix [#5043](https://github.com/druid-io/druid/issues/5043)

### CODE REVIEW

**Comment by drcrallen** [comment]
Thanks for the contrib! would you mind filling out the CLA at http://druid.io/community/cla.html ?

**Comment by skyler-tao** [comment]
CLA is done. Please check it.

**Comment by b-slim** [comment]
@skyler-tao  thanks for contribution.

**Comment by b-slim** [comment]
@skyler-tao  can you please update this file with the new property docs/content/development/extensions-contrib/statsd.md

**Pull request merged**
