### PR TITLE
SQL: Make row extractions extensible and add one for lookups.

### PR DESCRIPTION
**Pull request by gianm**
Two main changes here:

- Fold ExpressionConverter into Expressions.toRowExtraction, and make the latter take a DruidOperatorTable so the conversion of SQL expressions to Druid expressions is now extensible.

- Add a LookupExtractionOperator which offers a Druid SQL function `LOOKUP(expression, lookupName)` that hooks into query time lookups.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by fjy** [comment]
@gianm can you reverse this? i had too many tabs open and merged teh wrong PR :P

**Comment by gianm** [comment]
Sure, I'll revert the commit and re-open the PR

**Comment by gianm** [comment]
Reverted in e63eefd7ff51f5b319aa940b111c7cec1a289d27 and reopened in #3991

**Pull request merged**
