### PR TITLE
Pull-deps: correct the library directory in the document

### PR DESCRIPTION
**Pull request by giaosudau**
In `druid 0.9.1` the library directory is `lib` instead of `library`.
This PR just correct the directory to right one.

### CODE REVIEW

**Comment by fjy** [comment]
Thanks @giaosudau. Can you sign the CLA @ http://druid.io/community/cla.html?

**Comment by b-slim** [comment]
@giaosudau thanks, can you fix the one at line 102 as well.

**Comment by giaosudau** [comment]
@fjy sure. done.
@b-slim Thanks. I corrected the line 102.

**Comment by fjy** [comment]
👍

**Pull request merged**
