### PR TITLE
[Backport] Add hashCode and equals to UniformGranularitySpec

### PR DESCRIPTION
**Pull request by drcrallen**
* Also add hashCode != 0 to AllGranularity and NoneGranularity

Backport #1824

### CODE REVIEW

**Comment by nishantmonu51** [comment]
:+1:

**Comment by gianm** [comment]
Is this 0.8.2 or 0.8.3?

**Comment by drcrallen** [comment]
lol, doh... supposed to be 0.8.3 but I guess we don't have a branch yet, huh

**Comment by drcrallen** [comment]
closing for now until there's a proper branch to put the PR to.

**Pull request closed without merging**
