### PR TITLE
fix #1701 - MySQL 5.7 defaults break database character set check

### LINKED ISSUE #1701: MySQL 5.7.6 breaks Druid mysql metadata storage adapter
MySQL version 5.7.6 changed permissions required for `SHOW VARIABLES` (see https://dev.mysql.com/doc/refman/5.7/en/show-variables.html). Druid uses this to check the default database character set. Default MySQL permissions are not enough anymore, causing Druid to fail this check and preventing startup.

**Workaround:** use MySQL <= 5.7.5 or to set `show_compatibility_56 = on` in the MySQL configuration.

### PR DESCRIPTION
**Pull request by xvrl**

### CODE REVIEW

**Comment by fjy** [comment]
:+1: Nice to finally see a fix for this

**Comment by pjain1** [comment]
For some reason, this did not solve the problem for me. I am using mysql 5.7.9 installed using Homebrew, unless I do `set global show_compatibility_56 = on;` I get following exception - 
```
org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'value' in 'where clause' [statement:"SHOW VARIABLES where variable_name = 'character_set_database' and value = 'utf8'", located:"SHOW VARIABLES where variable_name = 'character_set_database' and value = 'utf8'", rewritten:"SHOW VARIABLES where variable_name = 'character_set_database' and value = 'utf8'", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284) ~[jdbi-2.63.1.jar:2.63.1]
	at io.druid.metadata.SQLMetadataConnector$2.call(SQLMetadataConnector.java:108) ~[classes/:?]
	at com.metamx.common.RetryUtils.retry(RetryUtils.java:38) [java-util-0.27.4.jar:?]
	at io.druid.metadata.SQLMetadataConnector.retryWithHandle(SQLMetadataConnector.java:113) [classes/:?]
	at io.druid.metadata.SQLMetadataConnector.createTable(SQLMetadataConnector.java:158) [classes/:?]
	at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:256) [classes/:?]
	at io.druid.metadata.SQLMetadataConnector.createConfigTable(SQLMetadataConnector.java:408) [classes/:?]
	at io.druid.guice.JacksonConfigManagerModule$1.start(JacksonConfigManagerModule.java:56) [classes/:?]
	at com.metamx.common.lifecycle.Lifecycle.start(Lifecycle.java:244) [java-util-0.27.4.jar:?]
	at io.druid.guice.LifecycleModule$2.start(LifecycleModule.java:155) [druid-api-0.3.13.jar:?]
	at io.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:71) [classes/:?]
	at io.druid.cli.ServerRunnable.run(ServerRunnable.java:38) [classes/:?]
at io.druid.cli.Main.main(Main.java:99) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_65]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'value' in 'where clause' [statement:"SHOW VARIABLES where variable_name = 'character_set_database' and value = 'utf8'", located:"SHOW VARIABLES where variable_name = 'character_set_database' and value = 'utf8'", rewritten:"SHOW VARIABLES where variable_name = 'character_set_database' and value = 'utf8'", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1334) ~[jdbi-2.63.1.jar:2.63.1]
	at org.skife.jdbi.v2.Query.fold(Query.java:173) ~[jdbi-2.63.1.jar:2.63.1]
	at org.skife.jdbi.v2.Query.list(Query.java:82) ~[jdbi-2.63.1.jar:2.63.1]
	at org.skife.jdbi.v2.Query.list(Query.java:75) ~[jdbi-2.63.1.jar:2.63.1]
	at io.druid.metadata.storage.mysql.MySQLConnector.tableExists(MySQLConnector.java:81) ~[?:?]
	at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:164) ~[classes/:?]
	at io.druid.metadata.SQLMetadataConnector$4.withHandle(SQLMetadataConnector.java:160) ~[classes/:?]
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281) ~[jdbi-2.63.1.jar:2.63.1]
	... 17 mores
```

**Comment by xvrl** [comment]
@pjain1 you must be running using an old version of the mysql connector code. The current code does not have any `SHOW VARIABLES` statements.

**Comment by pjain1** [comment]
@xvrl Yes you are correct, I was pointing to the wrong extension directory. Thanks.

**Pull request merged**
