### PR TITLE
loading properties not depending specific classloader

### PR DESCRIPTION
**Pull request by navis**
One of my colleague wanted some druid servers(broker and historical?) embedded in his java process but it wasn't work because all servers tried to read the same configuration file.

Current property loading mechanism for servers depends on class loader and we should make class loader for specific server before start. This is generally ok but when using druid server embedded in other process, it makes some trouble for managing it. this is for that.

### CODE REVIEW

**Comment by drcrallen** [comment]
This breaks backwards compatibility and will break our deployments. Instead of completely foregoing the prior methodology of using ClassLoader resources, would it be possible to have a property that contains a list of files to use to create Properties, in ADDITION to pulling from the ClassLoader mechanism as was previously done?

**Comment by navis** [comment]
revised a little. would it better to have single `druid/config` path in classpath rather than adding  `druid/config/_common:druid/config/$SERVER/`?

**Comment by drcrallen** [comment]
@navis that is how we deploy it internally, with a single config path in the classpath that contains both runtime.properties and common.runtime.properties

For the example deployment I think it makes things clearer if there is clear delineation between the node types.

**Comment by navis** [comment]
@drcrallen ok. then I should make alternative way to fix my problem. thanks.

**Pull request closed without merging**
