### PR TITLE
Fix configuration for javaOpts, remove quotation marks

### PR DESCRIPTION
**Pull request by onlychoice**

### CODE REVIEW

**Comment by nishantmonu51** [comment]
+1

**Comment by himanshug** [comment]
@onlychoice did it not work for you with the quotes?

**Comment by onlychoice** [comment]
@himanshug No, it didn't work

**Comment by himanshug** [comment]
@onlychoice yeah, I guess I never noticed it bcoz things worked with default settings for the examples.

thanks for the contrib, can you please sign the cla at http://druid.io/community/cla.html ?

**Comment by onlychoice** [comment]
@himanshug done

**Pull request merged**
