### PR TITLE
Default value for maxRowsInMemory

### PR DESCRIPTION
**Pull request by bjozet**
Maybe some discussion on how to approach this matter is appropriate, I suspect there will be other changes spawning from this one, or at least more clarification.

The documentation for batch-ingestion claims that default value for maxRowsInMemory is 5 million, which is not true. It actually defaults to 80000, which in turn is derived from the default rowFlushBoundary.

> _indexing-hadoop/src/main/java/io/druid/indexer/HadoopTuningConfig.java:113:_
> 
> `this.rowFlushBoundary = maxRowsInMemory == null ? maxRowsInMemoryCOMPAT == null ?  DEFAULT_ROW_FLUSH_BOUNDARY : maxRowsInMemoryCOMPAT : maxRowsInMemory;`
> 
> _indexing-hadoop/src/main/java/io/druid/indexer/HadoopTuningConfig.java:44:_
> 
> `private static final int DEFAULT_ROW_FLUSH_BOUNDARY = 80000;`
> 

Furthermore the value defaults to 500000 for realtime/index tasks. Is it sane to have 2 different defaults values for the same config item depending on if it's used in realtime or batch contexts? 

> _indexing-service/src/main/java/io/druid/indexing/common/task/IndexTask.java:501:_
> 
> `private static final int DEFAULT_ROW_FLUSH_BOUNDARY = 500000;`
> 
> _server/src/main/java/io/druid/segment/indexing/RealtimeTuningConfig.java:40:_
> 
> `private static final int defaultMaxRowsInMemory = 500000;`
> 

Another minor part of this is also that other references to the value contain the info:

> Maximum heap memory usage for indexing scales with maxRowsInMemory * (2 + maxPendingPersists).

This is lacking from batch-ingestion.md, but I'm not sure if this applies to batch-ingestion too, should i add it?

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by fjy** [comment]
not merging yet because I think we should talk about a more reasonable default value for maxRowsinMemory

**Comment by gianm** [comment]
There is also a third default value, which is Tranquility's value of 75000. That takes precedence over the 500000 in RealtimeTuningConfig. It's lower on the grounds that it's better to be somewhat less efficient, and work, than to reach for the stars and possibly OOM.

**Comment by drcrallen** [comment]
> than to reach for the stars and possi`OutOfMemoryError: java heap space`

**Comment by fjy** [comment]
@gianm, do you want to set defaults everywhere to 75k?

**Comment by drcrallen** [comment]
It would be nice if tranquility and druid had consistent defaults. 75k sounds reasonable to me

**Comment by fjy** [comment]
@bjozet do you mind updating this PR to have 75k be the default value across ingestion?

**Comment by bjozet** [comment]
@fjy sure I can give it a go, but this would also include changing the DEFAULT_ROW_FLUSH_BOUNDARY, is that ok, or should [this ](https://github.com/druid-io/druid/blob/master/indexing-hadoop/src/main/java/io/druid/indexer/HadoopTuningConfig.java#L113) line be changed instead, and add a specific default for maxRowsInMemory?

**Comment by fjy** [comment]
@bjozet change DEFAULT_ROW_FLUSH_BOUNDARY

**Comment by bjozet** [comment]
I've updated the occurrences of the defaults which I could find, I hope none slipped past me. An extra set of eyes on this would be nice.

**Comment by fjy** [comment]
:+1:

**Comment by nishantmonu51** [comment]
:+1:, Added release notes label so that this gets added to release notes.

**Comment by nishantmonu51** [comment]
This is ready to be merged. 
@bjozet: can you fix the conflicts ?

**Comment by fjy** [comment]
@bjozet last comment, can we squash commits? after that I will merge

**Comment by bjozet** [comment]
@fjy squashed and ready to go. I shamelessly stole @gianm's comment from this thread for commit message.

**Pull request merged**
