### PR TITLE
Address spurious test failures

### PR DESCRIPTION
**Pull request by drcrallen**
This PR addresses some and will help address other spurious test failures we've been seeing:
- ChainedExecutionQueryRunnerTest made some incorrect assumptions about ordering / concurrency. This is a problem with the test itself and not with the ChainedExecutionQueryRunner itself.
- AnnouncerTest failed sporadically, so we added assertion messages in order to understand where in the test it is failing.

### CODE REVIEW

**Comment by drcrallen** [comment]
Giving it one more kick of the tires

**Comment by drcrallen** [comment]
Seems to be passing now. that's good.

**Comment by drcrallen** [comment]
Fixes #1032

**Comment by fjy** [comment]
@drcrallen Is it possible to provide more of a description of what this PR is doing and the problems it is fixing? Do certain unit tests fail on slow machines?

**Comment by xvrl** [comment]
This PR addresses some and will help address other spurious test failures we've been seeing:
- ChainedExecutionQueryRunnerTest made some incorrect assumptions about ordering / concurrency. This is a problem with the test itself and not with the ChainedExecutionQueryRunner itself.
- AnnouncerTest failed sporadically, so we added assertion messages in order to understand where in the test it is failing.

**Pull request merged**
