### PR TITLE
log the exception on failure to send query response

### PR DESCRIPTION
**Pull request by himanshug**
small follow up on #4169 to print exception to druid logs

### CODE REVIEW

**Comment by pjain1** [comment]
👍

**Comment by drcrallen** [comment]
If I'm reading this correctly it will cause a bunch of double-logging to both the request logger and the application logs on query cancellation / query interrupted (on purpose).

**Comment by himanshug** [comment]
@drcrallen no, this is catching and logging the exception, metrics etc in the anonymous class implementation which are not currently (before #4169 ) caught or logged. For example try sending a query using `curl -m 1 ...` that takes a few seconds , curl will close connection on its side in a sec and druid request log  or metrics would have no trace of this query.

**Comment by gianm** [comment]
@himanshug, after #4169 the `finally` after this catch will still log this failed query to the requestLogger, right? (by default it's ignored, so you wouldn't see it, but you should see it if you turn on request logging)

So it seems to me like what @drcrallen said is accurate, but it's also ok, since we probably want something written to the regular logs too.

If that's all correct then I am 👍

**Comment by himanshug** [comment]
@gianm you're right that this is to capture actual exception in the logs in addition to query stats in request log (after #4169 ) . I think @drcrallen was suspecting that #4169 would end up logging query stats twice in request log which shouldn't happen.

**Pull request merged**
