### PR TITLE
Fix metadata typo and rename default extension directory

### PR DESCRIPTION
**Pull request by guobingkun**
Fix typo
s/metdata/metadata

Rename default extension directory so that it's a bit cleaner.
s/druid_extensions/extensions
s/hadoop_druid_dependencies/hadoop_dependencies

### CODE REVIEW

**Comment by drcrallen** [comment]
Why rename?

**Comment by xvrl** [comment]
@drcrallen see https://github.com/druid-io/docker-druid/pull/14#discussion_r43662742

**Comment by xvrl** [comment]
:+1:

**Comment by gianm** [comment]
:+1:

**Pull request merged**
