### PR TITLE
handle commas in the path before calling MultipleInputs.addInputPaths

### PR DESCRIPTION
**Pull request by himanshug**

### CODE REVIEW

**Comment by xvrl** [comment]
@himanshug is it possible to add some form of unit or integration test for this?

**Comment by himanshug** [comment]
@xvrl sure, that is a todo noted in description.. I wanted to put it up quickly so that Hagen could try it.

**Comment by xvrl** [comment]
@himanshug oops sorry, I missed that

**Comment by xvrl** [comment]
@himanshug do you know if https://issues.apache.org/jira/browse/MAPREDUCE-5061 would affect this?

**Comment by himanshug** [comment]
@xvrl  once  https://issues.apache.org/jira/browse/MAPREDUCE-5061  is fixed, this PR change will not be needed anymore. I will put the bug link in the code comment explaining this. Thanks for finding it, I did a quick search and noted many people had faced the issue but got focused more on fixing the problem :)

**Comment by himanshug** [comment]
@xvrl updated code to handle all kinds of glob paths, added unit tests and updated the "integration test" as well

**Comment by sixtus** [comment]
Awesome, I will try this first thing in the morning :+1:

**Comment by sixtus** [comment]
I have a little batch-up incident to process before I can deploy the patch. This will have to delay my testing until monday.

**Comment by fjy** [comment]
:+1:

**Comment by sixtus** [comment]
Seems to work, tnx for the quick patch

**Comment by sixtus** [comment]
mmh, not sure if this is related, but:
2015-08-24T09:08:45,120 ERROR [task-runner-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[HadoopIndexTask{id=index_hadoop_events_2015-08-24T09:06:55.717Z, type=index_hadoop, dataSource=events}]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.api.client.repackaged.com.google.common.base.Throwables.propagate(Throwables.java:160) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:132) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopIndexTask.run(HadoopIndexTask.java:206) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:235) [druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:214) [druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:129) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	... 7 more
Caused by: java.lang.RuntimeException: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /var/app/druid/storage/task/druid-indexing/classpath/druid-services-0.8.2-SNAPSHOT-selfcontained.jar: File is not open for writing. Holder DFSClient_NONMAPREDUCE_-1211006467_153 does not have any open files.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2960)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:3023)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:3003)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:641)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:484)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)

	at io.druid.indexer.IndexGeneratorJob.run(IndexGeneratorJob.java:207) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:182) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:96) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:259) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:129) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	... 7 more
Caused by: org.apache.hadoop.ipc.RemoteException: No lease on /var/app/druid/storage/task/druid-indexing/classpath/druid-services-0.8.2-SNAPSHOT-selfcontained.jar: File is not open for writing. Holder DFSClient_NONMAPREDUCE_-1211006467_153 does not have any open files.
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2960)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFileInternal(FSNamesystem.java:3023)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:3003)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:641)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTranslatorPB.java:484)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)

	at org.apache.hadoop.ipc.Client.call(Client.java:1410) ~[hadoop-common-2.4.1.jar:?]
	at org.apache.hadoop.ipc.Client.call(Client.java:1363) ~[hadoop-common-2.4.1.jar:?]
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206) ~[hadoop-common-2.4.1.jar:?]
	at com.sun.proxy.$Proxy193.complete(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:404) ~[hadoop-hdfs-2.4.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:190) ~[hadoop-common-2.4.1.jar:?]
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:103) ~[hadoop-common-2.4.1.jar:?]
	at com.sun.proxy.$Proxy194.complete(Unknown Source) ~[?:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.completeFile(DFSOutputStream.java:2116) ~[hadoop-hdfs-2.4.1.jar:?]
	at org.apache.hadoop.hdfs.DFSOutputStream.close(DFSOutputStream.java:2100) ~[hadoop-hdfs-2.4.1.jar:?]
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:70) ~[hadoop-common-2.4.1.jar:?]
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:103) ~[hadoop-common-2.4.1.jar:?]
	at com.google.common.io.Closer.close(Closer.java:214) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:259) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:119) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexer.JobHelper.setupClasspath(JobHelper.java:121) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexer.IndexGeneratorJob.run(IndexGeneratorJob.java:193) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexer.JobHelper.runJobs(JobHelper.java:182) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexer.HadoopDruidIndexerJob.run(HadoopDruidIndexerJob.java:96) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at io.druid.indexing.common.task.HadoopIndexTask$HadoopIndexGeneratorInnerProcessing.runTask(HadoopIndexTask.java:259) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at io.druid.indexing.common.task.HadoopTask.invokeForeignLoader(HadoopTask.java:129) ~[druid-services-0.8.2-SNAPSHOT-selfcontained.jar:0.8.2-SNAPSHOT]
	... 7 more
2015-08-24T09:08:45,175 INFO [task-runner-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_hadoop_events_2015-08-24T09:06:55.717Z",
  "status" : "FAILED",
  "duration" : 43750
}

i.e. still can't use the indexer

**Comment by sixtus** [comment]
Seems to be related to the classpath in HDFS. It's shared and not cleaned up, so certain combination of upgrades seem to leave an unusable state

**Comment by himanshug** [comment]
@sixtus that looks unrelated to this PR
I would guess that you are running multiple hadoop indexing job in parallel and hitting https://github.com/druid-io/druid/pull/1232 due to probably having a *-SNAPSHOT.jar on the classpath.

**Comment by gianm** [comment]
:+1: after travis finishes

**Comment by sixtus** [comment]
Yes, seems to be -SNAPSHOT foo :/

**Comment by xvrl** [comment]
@himanshug does this need to go into 0.8.11? please add to milestone if so.

**Comment by himanshug** [comment]
@xvrl yes it is a fix for regression, it has to go in 0.8.1
@gianm thanks for updating the milestone.

**Comment by gianm** [comment]
@xvrl yes it does, it fixes a regression from 0.8.0. I added the milestone

**Pull request merged**
