### PR TITLE
Rename ExtractionNamespaceCacheFactory to CachePopulator (the last part of #3667)

### PR DESCRIPTION
**Pull request by leventov**
This rename was promised here: https://github.com/druid-io/druid/pull/3651#issue-186923217 and here: https://github.com/druid-io/druid/pull/3697#issue-189894038

The last part of #3667.

### CODE REVIEW

**Comment by jihoonson** [comment]
LGTM

**Comment by gianm** [comment]
There's already a CachePopulator in CachingClusteredClient, although it's a private inner class. Do you think it's fine to use the same name?

**Comment by leventov** [comment]
@gianm good point. Renamed `CachePopulator` to `CacheGenerator`.

**Comment by gianm** [comment]
LGTM.

**Comment by leventov** [comment]
Thanks @gianm @jihoonson for review.

**Pull request merged**
