### PR TITLE
Druid launch script improvements

### PR DESCRIPTION
**Pull request by nishantmonu51**
Improvements to Druid launch scripts - 
1) Adds status command to launch scripts
2) Makes it possible to configure druid config directories using environment variables

### CODE REVIEW

**Comment by drcrallen** [comment]
👍

**Comment by nishantmonu51** [comment]
@drcrallen: added some more changes to this PR, please check again.

**Comment by jon-wei** [comment]
👍

**Comment by gianm** [comment]
👍

**Pull request merged**
