### PR TITLE
SQL: Groundwork for views.

### PR DESCRIPTION
**Pull request by gianm**
Views are implemented using Calcite's TableMacro and ViewTable, which
allows them to be resolved at planning time.

They are not actually exposed to users at this point, but enough is there
to have some test cases in CalciteQueryTest.

### CODE REVIEW

**Comment by fjy** [comment]
👍

**Comment by gianm** [comment]
Hmm, something weird going on with the guice injection test. Looking into it.

**Comment by gianm** [comment]
Pushed a fix.

**Comment by jihoonson** [comment]
@gianm this patch looks good to me, but it looks gone to stale. The compiler complains about ```QueryGranularities.ALL``` in CalciteQueryTest. Please fix it.

**Comment by gianm** [comment]
@jihoonson thanks for looking, I just fixed the conflicts.

**Comment by jihoonson** [comment]
The latest patch looks good to me.

**Comment by gianm** [comment]
Resolved conflicts.

**Comment by jon-wei** [comment]
:+1:

**Pull request merged**
