### PR TITLE
Update bytebuffer-collections to 0.2.5

### PR DESCRIPTION
**Pull request by drcrallen**
* Adds [polygound bound](https://github.com/metamx/bytebuffer-collections/pull/30) for spatial data. Thanks @scusjs
* Fixes cache key collisions for spatial data
* Update roaring to 0.5.18

### CODE REVIEW

**Comment by drcrallen** [comment]
lol, those labels were not at all what I had put on there originally. Github, you are silly

**Comment by gianm** [comment]
@drcrallen I had a similar thing happen to me earlier today and thought I was just losing my mind

**Comment by gianm** [comment]
👍

**Comment by gianm** [comment]
BTW: Why not a newer roaring? Looks like there are newer 0.5.x's, and also 0.6.x's are a thing.

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/CHANGELOG

**Comment by drcrallen** [comment]
@gianm because noone submitted a thing to bytebuffer-collections

**Comment by drcrallen** [comment]
I don't know what the compatibility between 0.5.x and 0.6.x is. Maybe @lemire can comment if there would be any unexpected things happen to things created with 0.5.x roaring if we updated to 0.6.x?

**Comment by drcrallen** [comment]
Filed https://github.com/metamx/bytebuffer-collections/pull/35

**Comment by lemire** [comment]
@drcrallen 

The API and the file format should be considered stable. We are mostly just optimizing performance, reducing memory usage and adding (small) features. Upgrading to the latest version should not be an issue and you should expect performance and memory-usage gains.

If any issue should arise (unlikely), we are there to help.

It is recommended to update to version 0.6 of RoaringBitmap *except* if you need Java 6 support. We deliberately stopped testing Java 6 with version 0.6. But if anyone is using Druid with Java 6, they have other problems, presumably...

**Comment by drcrallen** [comment]
>But if anyone is using Druid with Java 6, they have other problems, presumably...

Yes, like "rejected jars" kind of problems. Thanks!

**Comment by drcrallen** [comment]
```
Tests run: 24, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 37.007 sec <<< FAILURE! - in io.druid.indexing.overlord.TaskLifecycleTest
testResumeTasks[taskStorageType=HeapMemoryTaskStorage](io.druid.indexing.overlord.TaskLifecycleTest)  Time elapsed: 14.16 sec  <<< ERROR!
com.metamx.common.ISE: Where did the task go?!: index_foo_2016-06-08T20:25:54.232Z
	at io.druid.indexing.overlord.TaskLifecycleTest.testResumeTasks(TaskLifecycleTest.java:1070)
```

**Comment by nishantmonu51** [comment]
👍

**Pull request merged**
