### PR TITLE
Remove materialization in chained query runner

### PR DESCRIPTION
**Pull request by navis**
Chained query runner materializes sequences into lists. But seemed not necessary.

### CODE REVIEW

**Comment by nishantmonu51** [comment]
IIRC, the sequences returned by individual query runners are lazy and the actual query processing is done while the sequence is accumulated.  ChainedQueryExecutionRunner materializes the sequences so that the actual query processing happens in processing threads rather than http threads.

**Comment by xvrl** [comment]
@nishantmonu51 is correct, we want to make sure processing happens within processing threads and not outside. We should definitely add a comment to explain the reason the materialization exists.

**Comment by navis** [comment]
I've thought about that but why should it be? and if it should be, should it be done in some wrapper for runner, not in chained runner?

**Comment by xvrl** [comment]
@navis processing has to happen within the number of processing threads for several reasons:
a) we make processing threads configurable so a user is able to define how many cores should be used for querying
b) we need to ensure we don't exceed our max direct memory allocation, which we explicitly ask users to configure according to the number of processing threads they run.

**Comment by navis** [comment]
@xvrl I got that it's possible to use more threads than expected. But it seemed not like to use more direct memory because it will return single Sequence. And still, should it (materialization) be done explicitly by wrapping with something like MaterializingQueryRunner?

**Comment by nishantmonu51** [comment]
@navis memory requirements would change for TopN's which uses the processing buffers, we have 1 processing buffer per processing thread, in case we use jetty threads instead of processing threads to accumulate sequence events in that processing buffer, we would need jetty threads * number of segments being scanned by each query - processing buffers. 
does that makes sense ?

**Comment by navis** [comment]
@xvrl @nishantmonu51 thanks for the explanation, but I think I'm still missing something. Currently it's working like,
```
                       ResultMergeQR      ChainedExecutionQR(3)
                                         |- List (materialized) 
processing(memory) --- combining-seq  ---|- List (materialized)
                                         |- List (materialized)
``` 

But I'm suggesting that it would be ok with below, which can possibly occupy more threads but still not using processing memory.
```
                       ResultMergeQR    ChainedExecutionQR  HTTP-threads
processing(memory) --- combining-seq    --- sequence        --- *(>3)
```

**Comment by nishantmonu51** [comment]
@navis: AFAIU, the current flow is something like where each processing thread uses a processing buffer to accuumate results - 
```
                       ResultMergeQR      ChainedExecutionQR(3)
                                         |- List (materialized)- Segment Scan using processing buffer
 --- combining-seq  ---|- List (materialized) -  Segment Scan using processing buffer
                                         |- List (materialized) -  Segment Scan using processing buffer
``` 

the processing buffer is used by the processing thread and is freed up when the Sequence is fully accumulated and is materialized in the List. 

After the change proposed in the PR, the processing buffer will not get freed up until all the sequences are combined. Since the processing thread will get free as soon as it hands over the sequence the 1:1 mapping of processing threads and processing buffer will get broken.

**Comment by nishantmonu51** [comment]
If you want to see which thread is allocating and releasing the processing buffer to the buffer pool, 
you can add debug logs to the StupidPool class for buffer take and close method. 
In an ideal world, each processing thread should only take 1 processing buffer and release it when its done with the segment scan. and the number of buffers allocated should be equal to the number of processing threads.

**Comment by navis** [comment]
I understand it will possibly occupy off-heap memory "longer" but it will not use "more". But seeing most of the OOM is occurred in heap memory not in off-heap one, I prefer to stick this way. Anyway it's about policy I think and I'm closing this.

**Pull request closed without merging**
